### ISSUE TITLE
Allow SpecialFunctions v0.8

### ISSUE THREAD

**Issue by oschulz** [JuliaStats/Distributions.jl#1007]
Deconvolution is blocking updates of SpecialFunctions to v0.8 (needed by current Zygote v0.4.0).

**Comment by andreasnoack** [comment]
See https://github.com/JuliaStats/Distributions.jl/pull/891

**Comment by oschulz** [comment]
Ah, darn, and I thought it would be just a change to Project.toml ...

**Comment by matbesancon** [comment]
@JuliaRegistrator register()

**Comment by matbesancon** [comment]
@JuliaRegistrator register()

**Comment by matbesancon** [comment]
@JuliaRegistrator register()
