### ISSUE TITLE
Multinomial distribution rand does not support Float32 probability vectors

### ISSUE THREAD

**Issue by darsnack** [JuliaStats/Distributions.jl#1032]
Is there a reason `multinom_rand` is [restricted to Float64 arrays only](https://github.com/JuliaStats/Distributions.jl/blob/147a3718f2dba86607926c09741e28ae2cb637d7/src/samplers/multinomial.jl#L2) as the probability vector?

**Comment by mschauer** [comment]
We can relax that as far as I can see.
