### ISSUE TITLE
Feature request: deterministic (Dirac) distribution

### ISSUE THREAD

**Issue by HenriDeh** [JuliaStats/Distributions.jl#1040]
Following [this](https://discourse.julialang.org/t/distributions-jl-is-there-a-deterministic-distribution/32475) discussion, it appears the package could use a distribution that returns a fixed value. 

In physics it is called a Dirac. It would be defined as 

```
struct Dirac{T<:Real} <: ContinuousUnivariateDistribution
    x::T
end

function rand(dist::Dirac)
    return dist.x
end

dist = Dirac(1.0)
rand(dist) #returns 1.0
```
We should also add a multivariate equivalent where `T<:Array{<:Real}`

**Comment by johnczito** [comment]
A `Normal` with zero variance behaves this way

```julia
julia> d = Normal(4.5, 0.0)
Normal{Float64}(μ=4.5, σ=0.0)

julia> rand(d)
4.5

julia> logpdf(d, 4.5)
Inf

julia> logpdf(d, 5.0)
-Inf
```
So one approach is just to say
```julia
Dirac(x::Real) = Normal(x, zero(x))
```

**Comment by HenriDeh** [comment]
Is it still interesting to define a Dirac struct in the repo ? One would only add the definition you propose and it would suffice

**Comment by nickrobinson251** [comment]
There's an open PR, and I'm sure help getting it over the line would be appreciated :) https://github.com/JuliaStats/Distributions.jl/pull/861/files

**Comment by devmotion** [comment]
Fixed by https://github.com/JuliaStats/Distributions.jl/pull/1231.
