### ISSUE TITLE
What is the current state of empirical univariate distribution?

### ISSUE THREAD

**Issue by juliohm** [JuliaStats/Distributions.jl#1047]
Do we have a distribution type in Distributions.jl with similar behavior? https://github.com/juliohm/GeoStatsBase.jl/blob/master/src/distributions.jl Also, do we have some `transform` API as above to convert samples from one univariate distribution to another?

I don't remember if I asked this question before somewhere, just wanted to double check what are the plans in Distributions.jl.

**Comment by davibarreira** [comment]
Perhaps `DiscreteNonParametric`is what you are looking for.

**Comment by juliohm** [comment]
I was actually looking into something like EmpiricalCDFs.jl: https://github.com/jlapeyre/EmpiricalCDFs.jl

It is the package I use nowadays when I need continuous non-parametric. This functionality should probably be absorbed by Distributions.jl?

**Comment by davibarreira** [comment]
I made a pull request in the past. But didn't fix all the issues.
