### ISSUE TITLE
Checking foo() === NaN is brittle

### ISSUE THREAD

**Issue by KristofferC** [JuliaStats/Distributions.jl#1055]
Tests for Distributions.jl fails on Julia master likely due to the type of NaN that is generated. `===` on NaN will do a bitwise check. It is likely the tests should use `isnan`.

**Comment by matbesancon** [comment]
I see why we should fix this in the package, but on the Julia side, isn't it a breaking change to now return false on `NaN === NaN`?

**Comment by andreasnoack** [comment]
So `NaN === NaN` is still true. I guess we might sometimes receive different kinds of NaNs from our dependencies so we end up with something like
```julia
julia> nan1 = reinterpret(Float64, 0x7ff8000000000000)
NaN

julia> nan2 = reinterpret(Float64, 0x7ff8000000000001)
NaN

julia> nan1 === nan2
false
```
but what have changed in Julia 1.4 that could cause this?

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/34405 might make this not happen anymore.

**Comment by matbesancon** [comment]
interesting, I thought NaN was a unique bit value, well TIL.
