### ISSUE TITLE
limit the values of random sampling from the VonMises distribution to -pi ~ +pi

### ISSUE THREAD

**Issue by SosUts** [JuliaStats/Distributions.jl#1061]
**I want to limit the values of random sampling from the VonMises distribution to -pi ~ +pi.**

I have some circular data which the domain is -pi ~ +pi.
I want to model the data by using Distributions.jl and Turing.jl.
However, the domain of VonMises(mu, kappa) seems to be mu-pi ~ mu+pi.
I could change pdf and cdf to -pi ~ + pi but I couldn't figure out how to change rand.  

**Which part of VonMisesSampler should be changed...?**
Any suggestions are welcomed.
Thank you in advance.

![pdf_cdf](https://user-images.githubusercontent.com/46147087/73121040-24601e00-3fb9-11ea-99c6-92b2acd6ea0f.png)

![hist](https://user-images.githubusercontent.com/46147087/73121078-6d17d700-3fb9-11ea-980a-bb696870d989.png)

**Comment by matbesancon** [comment]
Doesn't it work with mu set to 0?

**Comment by SosUts** [comment]
It does, but in other words, it only works with mu set to 0.
I think it would be nice if it work just like np.random.vonmises().
![npmu3kappa5](https://user-images.githubusercontent.com/46147087/73243440-df233280-41ea-11ea-9c61-904d7cb6e03c.png)

**Comment by matbesancon** [comment]
Ok so you mean a by default constructor VonMises()?
The structure of Distributions.jl is more based on constructing the distribution you want and then operating on it
For more explanation on the rational, you can check this preprint
https://arxiv.org/abs/1907.08611

**Comment by SosUts** [comment]
Yes, a default constructor.
I thought I have to fix the domain to use VonMises for Turing.jl.
I could custom pdf and cdf of default constructor and fix the domain to -pi~+pi whatever the mu is.(1st fig, a distribution I constructed)
But I couldn't find how to custom rand method(2nd fig, default VonMises constructor).
I'm not a native English speaker.
I'm so sorry if my sentence doesn't make sense...

Anyway, it seems VonMises is not available for Turing.jl uses.
Just fixing the domain may not solve the problem.
https://github.com/TuringLang/DistributionsAD.jl/issues/2

**Comment by matbesancon** [comment]
There is already a default constructor:
```julia
VonMises() = VonMises(0.0, 1.0, check_args=false)
```

**Comment by SosUts** [comment]
Usually, von Mises distribution is used for modelling circular data(domain : 0 ~ 2pi, or -pi ~+pi).
The domain of
```Julia
VonMises() = VonMises(0.0, 1.0, check_args=false)
```
is -pi ~ pi just because mu is 0.
But for example, if you change a value of mu using default constructor, the domain will change to mu-pi ~ mu+pi.
I made this issue because I want the domain to be -pi ~ +pi whatever the mu is and I don't know how to realize this.
Usually, the domain of mu is set to 0 ~ 2pi or -pi ~+pi just as von Mises distribution itself is.

**Comment by SosUts** [comment]
@matbesancon
I'm so sorry for my confusing English, thank you for answering many times!
