### ISSUE TITLE
Bernoulli should produce `Bool`

### ISSUE THREAD

**Issue by MikeInnes** [JuliaStats/Distributions.jl#1068]
I'm not clear why this changed in #1048 (apparently because `Int` may be easier to [represent on quantum processors](https://github.com/JuliaStats/Distributions.jl/pull/1046#issuecomment-570532920) than `Bool`, which is not in fact the case.) I agree that it's good to be consistent, but it seems pretty clear that `Bool` is the right type to use here.

It's good to use the narrowest type available to represent an output, because (a) it gives useful information to tools and (b) narrow types can always be upcasted (to Int, Float etc.) but can't automatically be downcasted back to `Bool`, which means more code is convenient to write.

To come at it from the other direction – why use `Int64` here but not `Float64`? Or `BigInt`? Or arbitrary-precision floating point?

**Comment by mschauer** [comment]
I think it is simple: it should be Bool so it works in conditionals.

**Comment by matbesancon** [comment]
@JuliaRegistrator register()

**Comment by matbesancon** [comment]
@JuliaRegistrator register()

**Comment by matbesancon** [comment]
@JuliaRegistrator register()
