### ISSUE TITLE
`MvNormal` constructor reverses the types of its arguments

### ISSUE THREAD

**Issue by ben-schulz** [JuliaStats/Distributions.jl#1069]
in the course of hacking around in `src/multivariate/mvnormal.jl`, i noticed what might be a mistake the source:

https://github.com/JuliaStats/Distributions.jl/blob/d521695bdc1e486b8cac216e3c6c087290eb14db/src/multivariate/mvnormal.jl#L195-L198

this project is new to me, so i don't want to presume -- but it would seem to me that line 197 should be:

```
MvNormal{T, typeof(μ), typeof(Σ)}(μ, Σ)
```

i.e. so that the types used for dispatch appear in the same order as the arguments to the constructor.

is that right?

**Comment by johnczito** [comment]
It's right. Look at the definition:

https://github.com/JuliaStats/Distributions.jl/blob/d521695bdc1e486b8cac216e3c6c087290eb14db/src/multivariate/mvnormal.jl#L179-L182

The type parameters are listed in the order `{T<:Real,Cov<:AbstractPDMat,Mean<:AbstractVector}`, so the constructor passes them in the right order. I guess it would be clerically preferable if the field names of the type were listed in the same order as their corresponding type parameters, but there is nothing technically wrong here.

**Comment by ben-schulz** [comment]
i see now; my mistake. sorry for the confusion; i'll marked this closed.
