### ISSUE TITLE
Feature Request: Add Beta 4 parameters distribution

### ISSUE THREAD

**Issue by guilhermebodin** [JuliaStats/Distributions.jl#1072]
Is it possible to include the Beta four parameters parametrization in the package?
The 4 parameter distribution is described in the section "Four parameters" https://en.wikipedia.org/wiki/Beta_distribution

**Comment by johnczito** [comment]
This is secretly already implemented. In the wiki it says that the 4-parameter beta Y over an interval (a, c) is given by a transformation of an ordinary beta X: 
```
Y = (c - a)X + a. 
```
This means that a 4-parameter beta is a [Location-Scale](https://en.wikipedia.org/wiki/Location%E2%80%93scale_family) transformation of a regular Beta, which [is implemented](https://juliastats.org/Distributions.jl/stable/univariate/#Distributions.LocationScale) via
```julia
a = -1
c = 1
beta = Beta(1, 1)
beta4par = LocationScale(a, c - a, beta)
```

**Comment by johnczito** [comment]
#971 is related to this.

**Comment by guilhermebodin** [comment]
hmm, I knew it was easy to reformulate it thanks a lot!

**Comment by johnczito** [comment]
Any time. Is it okay to close this?
