### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by ablaom** [JuliaStats/Distributions.jl#1083]
From the Erlang docstring:

```julia
Erlang(a, s)   # Erlang distribution with shape parameter a and scale b
```
I assume `b` is meant to be replaced with `s` since `scale(Erlang(a, s))` is indeed `s` (and not the reciprocal as in some implementations).

**Comment by matbesancon** [comment]
yes indeed, PR welcome to change it :)

**Comment by matbesancon** [comment]
@JuliaRegistrator register()

**Comment by matbesancon** [comment]
@JuliaRegistrator register()
