### ISSUE TITLE
Tag a new minor version for StatsBase v0.33 compatibility?

### ISSUE THREAD

**Issue by oschulz** [JuliaStats/Distributions.jl#1099]
We need a new release of Distributions with StatsBase v0.33 compatibility (already in Project.toml) before lots of other packages can move to StatsBase v0.33.

**Comment by andreasnoack** [comment]
It's been out for a while. See https://github.com/JuliaStats/Distributions.jl/blob/b5e3217e17a15e3838d9bb586b184ef1c63322f1/Project.toml#L23

**Comment by andreasnoack** [comment]
The link is to version 0.23.2 which wasn't clear.

**Comment by oschulz** [comment]
Opps, sorry, had an outdated version of Distributions - my bad!
