### ISSUE TITLE
new to julia, and want to implement a log prior

### ISSUE THREAD

**Issue by Rezvious** [JuliaStats/Distributions.jl#1100]
hello everyone, I'm new in Julia and I wanted to implement a function log_prior that computes the log of multivariate normal distribution. would you mind please help me to implement it?

**Comment by andreasnoack** [comment]
Hi Rezvaneh

Welcome to Julia. Please use discourse.julialang.org for questions. We generally reserve the issue tracker for bug reports or to keep track of planned enhancements. Discourse is better suited for questions and it's much more likely that you'd get an answer there.
