### ISSUE TITLE
Comment on Threads

### ISSUE THREAD

**Issue by bartolsthoorn** [JuliaStats/Distributions.jl#1110]
In the documentation I do not see a mention of threads, and I only found this: #573, but I am not sure I understand the statement "per-thread RNGs as the first argument".

So just for clarity, I would like to confirm that this basic example safely produces a matrix of 4x5 normally distributed random numbers? (i.e. equivalent to removing `Threads.@threads`)
```julia
# for example, set JULIA_NUM_THREADS=2
using Distributions
normal_d = Normal(0,1)

data = zeros(Float64, 4, 5)
Threads.@threads for i in 1:4
    data[i, :] = rand(normal_d, 5)
end
print(data)
``` 
Is this correct? I do not see identical numbers appearing.

**Comment by SebastianCallh** [comment]
The way I understand it, "passing per-thread RNG" refers to explicitly constructing a random source for each thread. For instance like

    using Distributions, Random 
 
    # for example, set JULIA_NUM_THREADS=2
    using Distributions
    normal_d = Normal(0,1)

    data = zeros(Float64, 4, 5)
    Threads.@threads for i in 1:4
        rng = MersenneTwister(1234)
        data[i, :] = rand(rng, normal_d, 5)
    end
    print(data)

**Comment by bartolsthoorn** [comment]
Thanks! I wonder if this manual construction is necessary though, as my example also appears to produce different random numbers.

**Comment by jtackm** [comment]
https://julialang.org/blog/2019/07/multithreading/#random_number_generation suggests it's not?

**Comment by bartolsthoorn** [comment]
@jtackm Thank you. Yes, based on that description, my example is safe because each thread is implicitly given a new seed. So I will close this one.
