### ISSUE TITLE
Sampling bug when one of the probabilities for `Categorical` is equal to 1

### ISSUE THREAD

**Issue by ztangent** [JuliaStats/Distributions.jl#1111]
Sampling a specific value from a Categorical distribution with certainty seems to be buggy:
```julia
julia> sum([rand(Categorical([1, 0])) for i in 1:100])
144
julia> sum([rand(Categorical([0, 0, 1])) for i in 1:100])
208
julia> sum([rand(Categorical([0, 0, 0, 1])) for i in 1:100])
262
```
The expected sums in each of those cases should have been 100, 300, and 400 respectively. Once at least one other value has non-zero probability, the issue seems to go away:
```julia
julia> sum([rand(Categorical([0, 0, 0.0001, 0.9999])) for i in 1:100])
400
```
Examples above were tested on `v0.23.2`, i.e. the latest release. It'd be great if this could be fixed, since this is affecting downstream packages (e.g. https://github.com/probcomp/Gen/issues/256)!

**Comment by ztangent** [comment]
Update: things also seem to work if you pass in `Float64`s rather than `Int`s:
```julia
julia> sum([rand(Categorical([0, 0, 0, 1.0])) for i in 1:100])
400
```

**Comment by mschauer** [comment]
This might be the culprit, sampling an `Int`:

https://github.com/JuliaStats/Distributions.jl/blob/345d1e085916134901d6ffac9ed31aeee0d0ee83/src/univariate/discrete/discretenonparametric.jl#L76

**Comment by mossr** [comment]
Just bumping this as
```julia
rand(Categorical([0, 1]))
```
returns uniformly over `[0, 1]`. Of course, I can use floats for now, but this is sneaky...
