### ISSUE TITLE
small docs hiccup

### ISSUE THREAD

**Issue by caseykneale** [JuliaStats/Distributions.jl#1112]
https://juliastats.org/Distributions.jl/stable/multivariate/#Distributions.MvNormal
you cannot use the following command
```MvNormal(d, sig)``

when sig is a covariance matrix. But, you can do the following
```MvNormal(sig)``

Super tiny docs bug

**Comment by matbesancon** [comment]
@JuliaRegistrator register()

**Comment by matbesancon** [comment]
@caseykneale was the bug you reported wrong or should it be fixed?
