### ISSUE TITLE
Should distributions have `==` defined?

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaStats/Distributions.jl#1117]
This took me by surprise, so i wondered if this was intentioned behaviour or if it was a missing feature?
```julia
julia> mv = MvNormal(rand(3), let x=rand(3,3); x*x'+I; end);

julia> mv2 = deepcopy(mv);

julia> mv == mv2
false
```

**Comment by johnczito** [comment]
It's intended in the sense that it's a general phenomenon not specific to distributions: [[1]](https://github.com/JuliaLang/julia/issues/4648), [[2]](https://stackoverflow.com/questions/59274263/why-do-structs-and-a-mutable-structs-have-different-default-equality-operators), [[3]](https://discourse.julialang.org/t/surprising-struct-equality-test/4890).

**Comment by nickrobinson251** [comment]
right, makes sense, so i think we file it under "missing feature"? 

I presume that we want `mv == mv2` in the example above, and it's just that this is a case where Julia doesn't give us it for free.

**Comment by nickrobinson251** [comment]
xref https://github.com/JuliaStats/Distributions.jl/issues/696
