### ISSUE TITLE
Please switch off requirement for Float64

### ISSUE THREAD

**Issue by bionicles** [JuliaStats/Distributions.jl#1120]
For RL, I would like to parameterize a Categorical distribution with the output of a neural net, but the distributions require Float64! Seems there are multiple issues for this. Is there some reason Distributions will not accept the default Float32 used by Flux ? 

find all "Float64" -> replace with "Float" ; done

**Comment by andreasnoack** [comment]
This is covered by https://github.com/JuliaStats/Distributions.jl/issues/1067. The fix is a little more involved that the one you propose but it would be great if you could make some progress on this in a PR.

**Comment by matbesancon** [comment]
@JuliaRegistrator register()

**Comment by bionicles** [comment]
https://github.com/JuliaStats/Distributions.jl/pull/1126
