### ISSUE TITLE
Adding the Soliton distribution

### ISSUE THREAD

**Issue by severinson** [JuliaStats/Distributions.jl#1129]
I've implemented the robust Soliton distribution. It's used primarily for Luby Transform erasure correcting codes. Are you interested in having it be part of Distributions.jl or do you think it's better that it remains a separate package?

https://github.com/severinson/SolitonDistribution.jl

Cheers,

**Comment by nickrobinson251** [comment]
Cool! I think this would be a welcome addition to Distributions.jl, if you're happy to open a PR?

**Comment by severinson** [comment]
I've created a PR; see #1134

**Comment by matbesancon** [comment]
@JuliaRegistrator register()
