### ISSUE TITLE
How to create MixtureModel using distributions from different families 

### ISSUE THREAD

**Issue by krishvishal** [JuliaStats/Distributions.jl#1151]
I want to create a MixtureModel using Normal distribution and Uniform distribution. Is there a way to do this?

**Comment by matbesancon** [comment]
@JuliaRegistrator register()

**Comment by matbesancon** [comment]
@JuliaRegistrator register()

**Comment by matbesancon** [comment]
@JuliaRegistrator register()

**Comment by matbesancon** [comment]
@JuliaRegistrator register()
