### ISSUE TITLE
zeromean field  of GenericMvTDist

### ISSUE THREAD

**Issue by willtebbutt** [JuliaStats/Distributions.jl#1158]
Currently, there is a boolean `zeromean` field in the [GenericMvTDist](https://github.com/JuliaStats/Distributions.jl/blob/253c3a0813e0a08bf41fdf22f83ea540cc89a4c5/src/multivariate/mvtdist.jl#L10) implementation.

I can think of a couple of reasons to remove this:
1. A better solution would be to use `FillArray`'s `Zero` to produce a zero-vauled mean. This would mean that the user wouldn't need to provide it. This would yield improved performance as the user would no longer be obligated to provide a mean vector if they know it's going to be zero.
2. We don't do this in other places, such as `MvNormal`, so it's a bit inconsistent in that sense.

Are there good reasons to keep it that I have missed, or would a PR that implements a solution using `FillArray`s be welcome?

**Comment by mschauer** [comment]
Where are FillArray's living?

**Comment by willtebbutt** [comment]
https://github.com/JuliaArrays/FillArrays.jl

Distributions already depends on them I believe.

**Comment by mschauer** [comment]
Not much love here for the `zeromean` implementation...

**Comment by willtebbutt** [comment]
Great, well I'll make a PR when I get a minute.

**Comment by devmotion** [comment]
Indeed, the field is a bit redundant, in particular since [`FillArrays.Zeros` are already used if no mean is provided](https://github.com/JuliaStats/Distributions.jl/blob/253c3a0813e0a08bf41fdf22f83ea540cc89a4c5/src/multivariate/mvtdist.jl#L34). I guess I should have removed it when switching to FillArrays :grimacing:
