### ISSUE TITLE
`quantile` on Geometric distribution returns a float

### ISSUE THREAD

**Issue by mkborregaard** [JuliaStats/Distributions.jl#1167]
Given that Geometric is a discrete distribution, I would assume it to return an Int, yet it returns a Float. Should this line 
https://github.com/JuliaStats/Distributions.jl/blob/master/src/univariate/discrete/geometric.jl#L135

be replaced with
```julia
max(ceil(Int, lp/log1p(-d.p)) - 1, zero(T))
```
?
This seems to be the root cause of https://github.com/JuliaPlots/StatsPlots.jl/issues/308

**Comment by andreasnoack** [comment]
Yes. I think this would be the right solution.

**Comment by mkborregaard** [comment]
OK I've opened a PR doing that.
