### ISSUE TITLE
Suggestion for logdiffcdf return value when x == y

### ISSUE THREAD

**Issue by MFairley** [JuliaStats/Distributions.jl#1178]
Currently `logdiffcdf` will return an error if `x == y` but since `cdf(x) - cdf(x) = 0`, I think it would make more sense to return `-Inf` rather than an error. Otherwise I need to add if statements to my code to deal with cases when `x` is equal to `y`.

```
julia> d = Beta(1, 1)
Beta{Float64}(α=1.0, β=1.0)

julia> logdiffcdf(d, 0.5, 0.5)
ERROR: ArgumentError: requires x > y.
Stacktrace:
 [1] logdiffcdf(::Beta{Float64}, ::Float64, ::Float64) at /Users/mfairley/.julia/packages/Distributions/5UNuk/src/univariates.jl:408
 [2] top-level scope at REPL[7]:1
```

**Comment by matbesancon** [comment]
that would make sense on my end. pinging @mschauer for a second opinion

**Comment by mschauer** [comment]
Yes, that makes sense.

**Comment by MFairley** [comment]
#1180 closes this
