### ISSUE TITLE
widen qqbuild signature?

### ISSUE THREAD

**Issue by piever** [JuliaStats/Distributions.jl#1196]
I've just noticed that `qqbuild` has a [very tight signature](https://github.com/JuliaStats/Distributions.jl/blob/master/src/qq.jl#L6) and errors with e.g. a `SubArray`. Would it be possible to widen it? (Happy to make a PR if it is.)

I'm asking because, from what I understood, it is the interface to create `QQPair` and AbstractPlotting and StatsPlots use it for QQPlots, but it currently errors if one doesn't pass a concrete `Array`.

**Comment by andreasnoack** [comment]
It should be fine to change that. The code is really old. It would be great with a PR
