### ISSUE TITLE
PDMats doesn't account for pivoting in Cholesky of sparse matrices

### ISSUE THREAD

**Issue by jkbest2** [JuliaStats/Distributions.jl#1200]
See JuliaStats/PDMats.jl#120.

This results in incorrect realizations from `rand(::MvNormalCanon)` when the provided precision matrix is factored by CHOLMOD. It may affect other methods as well.

**Comment by ElOceanografo** [comment]
MWE of this with a Gaussian Markov random field on a grid:

```julia
using Distributions, PDMats
using SparseArrays, LinearAlgebra
using Plots 

r = 0.25
n = 50
J = spdiagm(-n => fill(-r, n*(n-1)),
            -1 => fill(-r, n^2 - 1), 
            0 => fill(1, n^2),
            1 => fill(-r, n^2 - 1),
            n => fill(-r, n*(n-1)))
dsparse = MvNormalCanon(PDSparseMat(J))
ddense = MvNormalCanon(Matrix(J))

x1 = rand(dsparse)
x2 = rand(ddense)
plot(heatmap(reshape(x1, n, n), title="Sparse"), heatmap(reshape(x2, n, n), title="Dense"))
```
![image](https://user-images.githubusercontent.com/1072448/96321769-7e7f9400-0fcb-11eb-856e-337547abe7c7.png)

Fortunately, the pivoting doesn't affect likelihood calculations:
```julia
logpdf(dsparse, x1) ≈ logpdf(ddense, x1) # true
```
As I wrote in #1201, this is an easy code fix, but it requires thinking about how to rewrite some of the tests (which are probably broken currently, see [this comment](https://github.com/JuliaStats/Distributions.jl/pull/855#issuecomment-491640343) on #855).  The Cholesky decomposition is not unique, and the implementations in LinearAlgebra/LAPACK and SuiteSparse/CHOLMOD appear to return different factorizations.  As a result, the samples obtained from a dense and sparse `MvNormalCanon` will be different, even if their precision matrices and the random seeds are identical.  (The samples do have the same distribution, however.)

```julia

z = randn(n^2)
x3 = dsparse.J.chol.PtL' \ z
x4 = ddense.J.chol.U \ z
plot(heatmap(reshape(x3, n, n), title="Sparse"), heatmap(reshape(x4, n, n), title="Dense"))
```
![image](https://user-images.githubusercontent.com/1072448/96322479-12525f80-0fce-11eb-8004-8988f2a55925.png)


@matbesancon @andreasnoack how do you feel about this? How much of a problem is it if the particular samples drawn from a distribution depend on the types of its parameters?
