### ISSUE TITLE
Special functions

### ISSUE THREAD

**Issue by simonbyrne** [JuliaStats/Distributions.jl#121]
In order to move away from Rmath, we're going to require more special functions.  There's already been some discussion of this, but I thought I'd open an issue to keep track of them, please add any we can think of, and note where we might obtain implementations.
- [ ] incomplete gamma function
- [ ] incomplete beta function (some discussion in #98)
- [ ] `log(erfc(x))`: required for the logcdf of Normal (the current implementation using `erfcx` is a bit of a hack).
- [x] `erfcinv(exp(x))`: required for `invlogcdf` of Normal
 * it should be fairly easy to modify the `horner` version in base, as it first takes the log of the argument, but may require using more terms in the series.
 * implemented using Wichura algorithm instead.
- [ ] generalized hypergeometric function: noncentral Beta (discussed in #102)

**Comment by lindahua** [comment]
Moved to StatsFuns. Will create an issue to drive the development over there.
