### ISSUE TITLE
incorrect gradlogpdf for LogitNormal

### ISSUE THREAD

**Issue by briochemc** [JuliaStats/Distributions.jl#1221]
I noticed because it created buggy behaviour in variable transforms for an optimization problem of mine... It struck me when I noticed it is not even symmetric for the default parameters `LogitNormal()`, although it should be.
 
<img width=70% alt="Screen Shot 2020-11-13 at 12 58 44 am" src="https://user-images.githubusercontent.com/4486578/98949110-627bfd80-254b-11eb-9b23-faafc3caebc5.png">

<img width=34% alt="Screen Shot 2020-11-13 at 12 50 58 am" src="https://user-images.githubusercontent.com/4486578/98948308-61969c00-254a-11eb-8b92-91c00736a4d9.png"> <img width=34% alt="Screen Shot 2020-11-13 at 12 50 41 am" src="https://user-images.githubusercontent.com/4486578/98948314-62c7c900-254a-11eb-9a80-e65aa2ea0cdd.png">

Here is the culprit (I guess nobody checked until now!)

https://github.com/JuliaStats/Distributions.jl/blob/ae2d6c5c68abc0aeafdc249ca60df058c19279cb/src/univariate/continuous/logitnormal.jl#L139-L143

This is not symmetric around 0.5 because of the `log(x)` on the left.

Maybe someone with Mathematica or sagemath can do the symbolic derivation from the pdf/logpdf, and correct it?

**Comment by andreasnoack** [comment]
Fixed by https://github.com/JuliaStats/Distributions.jl/pull/1223
