### ISSUE TITLE
Mean and variance for gamma distribution

### ISSUE THREAD

**Issue by Mutaz94** [JuliaStats/Distributions.jl#1240]
https://github.com/JuliaStats/Distributions.jl/blob/530b9e0fe2d07e9a8082eaefdbc42fdcab3b7474/src/univariate/continuous/gamma.jl#L60

Hi! maybe its a naive question, but in the source code you defined the mean as 
```
mean = α * θ 
var = α * θ ^2
```
Isn't that the mean and variance are defined as the following:  
```
E(X) = α /θ ≈ mean
var(X) = α /θ^2
```
A similar pattern is seen in exponential distribution. 

Thank you!

**Comment by andreasnoack** [comment]
See https://en.m.wikipedia.org/wiki/Gamma_distribution, there are a couple of different parameterizations and we use the one with a scale parameter so the current definitions are correct. It's generally better to ask such questions on discourse.julialang.org.

**Comment by Mutaz94** [comment]
Thanks for the clarification!
