### ISSUE TITLE
Add three-parameter version of TDist for consistency

### ISSUE THREAD

**Issue by mattiasvillani** [JuliaStats/Distributions.jl#1247]
I find this inconsistent:

- Normal has a mean and standard deviation as optional arguments.
- MvNormal has a mean vector and covariance matrix as optional arguments.

- TDist has only degrees of freedom as argument.
- MvTDist has a mean vector and covariance matrix as optional arguments.

If fix this myself using the LocationScale function:

TDist(df,μ,σ) = LocationScale(μ,σ,TDist(df))

but maybe this one-liner should be included directly in tdist.jl for consistency? Or is this a design choice: to use the location-scale construction for univariate, but not for multivariate? (and Normal is handled differently since it so often used?).

**Comment by johnczito** [comment]
> Or is this a design choice: to use the location-scale construction for univariate, but not for multivariate? (and Normal is handled differently since it so often used?).

I think that's basically right. This has come up before, sort of: #971, #1072.

**Comment by mattiasvillani** [comment]
Ok, thanks. Still find it inconsistent, but now I know that this has been up for discussion. Closing this issue now to reduce clutter.
