### ISSUE TITLE
Normal(μ,σ) distribution second argument is σ, shouldn't it be σ^2?

### ISSUE THREAD

**Issue by alexboche** [JuliaStats/Distributions.jl#1256]
Normal(μ,σ) distribution second argument is σ, shouldn't it be σ^2? This tripped me up. Just saying I found this confusing since N(μ,σ^2) is the standard in my mathematical experience. Just a thought.

**Comment by johnczito** [comment]
Representing the normal distribution in terms of the standard deviation is standard in statistical computing: [R](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/Normal.html), [MATLAB](https://www.mathworks.com/help/stats/normrnd.html), [Python](https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html), [Stan](https://mc-stan.org/docs/2_25/functions-reference/normal-distribution.html). I'm not sure why, but I am sure that everyone has been tripped up by it at some point.
