### ISSUE TITLE
Rician distribution

### ISSUE THREAD

**Issue by mchitre** [JuliaStats/Distributions.jl#1290]
I've implemented most of the functions in `Distributions.jl` for a Rician distribution. I note that this is a distribution in the _wanted_ list in #124. Would you be open to a PR to bake this into `Distributions.jl`, or should I make a standalone `RicianDistributions.jl` package for it?

**Consideration**:
I am currently using `Roots.jl` and `Optim.jl` in the implementations of `quantile()`, `mode()` and `fit()`. These are not currently dependencies of `Distributions.jl`, so is this a concern?

**Comment by devmotion** [comment]
Maybe you can use one of the algorithms in https://github.com/JuliaStats/Distributions.jl/blob/master/src/quantilealgs.jl instead of depending on Roots and Optim?

**Comment by mchitre** [comment]
yes, that should be doable for `quantile()`, and I can do something similar for `mode()` quite easily. The `fit()` still might need `Optim.jl`, but if that is undesirable, I can manually implement a minimization algorithm (it is only a 1D search, so not hard to do).

**Comment by hdocmsu** [comment]
Hi @mchitre, I am very interested in using the Rician distribution. Looking forward to using it when you have it incorporated into Distributions.jl. Is there a timeline for when this PR will be completed?

**Comment by mchitre** [comment]
I'll try and prepare an initial version over the next week or so, and then we review and take it from there, I guess.

**Comment by hdocmsu** [comment]
> I'll try and prepare an initial version over the next week or so, and then we review and take it from there, I guess.

Great, thanks @mchitre for sharing the tentative timeline. Appreciate that!

**Comment by mchitre** [comment]
I haven't dropped this, but have been delayed due to some emergencies to handle. I should be getting back to this in a couple of weeks time.

**Comment by hdocmsu** [comment]
> I haven't dropped this, but have been delayed due to some emergencies to handle. I should be getting back to this in a couple of weeks time.

Thanks a lot for the heads up, @mchitre! I look forward to using the feature when it is available.

**Comment by MattEttus** [comment]
If this is stalled, is the code that has already been written available anywhere?  I'd love to finish it up and get it in the package.

**Comment by mchitre** [comment]
Thanks for the nudge @MattEttus. I'm on it today, and will submit a PR with the code I have shortly.

**Comment by mchitre** [comment]
PR #1387 raised.

**Comment by MattEttus** [comment]
Thanks, @mchitre !  Looks like you've made a ton of progress.

**Comment by devmotion** [comment]
Fixed by https://github.com/JuliaStats/Distributions.jl/pull/1387.
