### ISSUE TITLE
Consistency of capitalization

### ISSUE THREAD

**Issue by azev77** [JuliaStats/Distributions.jl#1323]
My understanding is: 
types are capitalized: `LogNormal(), Normal(0,1), Cauchy(0,1)` etc 
functions are not: `fit(D, data), fit(Histogram, data), mean(d), median(d), var(d), pdf(d, 2), cdf(d, 2)`

I'm confused about: 
- `MixtureModel([Normal(0,1),Cauchy(0,1)], [0.5,0.5])` is capitalized.
Is that bc it returns a distribution?
- Both `Truncated(Cauchy(0,1), 0.25, 1.8)` & `truncated(Cauchy(0,1), 0.25, 1.8)` return the same thing?
- `convolve(Cauchy(0,1), Cauchy(5,2))` is not capitalized though it returns a distribution
- `product_distribution([Normal(),Cauchy()])` is not capitalized though it returns a distribution

**Comment by mschauer** [comment]
Not saying that everything is consistent, but in general we follow Julia practice, as evidenced in the `Iterators` module: We create a wrapper type `Truncated` with a dedicated constructor function `truncated`.
You can create a truncated distribution directly with
```
julia> Truncated(Normal(), -1, 1)
Truncated(Normal{Float64}(μ=0.0, σ=1.0), range=(-1.0, 1.0))
```
but it is recommended to use `truncated`, as the function may return an appropriate type, for example a truncated uniform is again uniform:
```
julia> truncated(Uniform(0, 10), 0, 1)
Uniform{Float64}(a=0.0, b=1.0)
```

Any remaining issue?

**Comment by azev77** [comment]
Why isn’t ‘convolve()’ capitalized?
Doesn’t it return a distribution? Which is a type

**Comment by mschauer** [comment]
Does my comment clarify it?
