### ISSUE TITLE
Type stable code

### ISSUE THREAD

**Issue by azev77** [JuliaStats/Distributions.jl#1324]
Some distributions don't seem to have [type stable code](https://www.johnmyleswhite.com/notebook/2013/12/06/writing-type-stable-code-in-julia/). 
For example, consider [laplace](https://github.com/JuliaStats/Distributions.jl/blob/master/src/univariate/continuous/laplace.jl).jl:
```julia
var(d::Laplace) = 2d.θ^2
entropy(d::Laplace) = log(2d.θ) + 1
cdf(d::Laplace, x::Real) = (z = zval(d, x); z < 0 ? exp(z)/2 : 1 - exp(-z)/2)
```
Should `0/1/2` be `0.0/1.0/2.0` etc?

**Comment by devmotion** [comment]
There are problems with type instability in some (older) parts of Distributions but these examples are type stable. Code is type stable: the types of the variables in the function body is not changed at some point and the return type is always the same if  the type of the inputs is fixed (and eg not affected by branches that depend on the value of the inputs).

**Comment by azev77** [comment]
I'm not sure I understand. 
If `log(2d.θ)` if a Float and `1` is Int, then `log(2d.θ) + 1` is adding a float & Int? 
Isn't it better to do `log(2.0*d.θ) + 1.0`?

**Comment by devmotion** [comment]
It is completely fine to add floats and integers in Julia, and the code is type stable. Maybe your confusion arises from the following example of type instability:
```julia
x = 1
x += log(42)
```
Here the type of `x` is not stable since it is changed from `Int` to `Float64` in the second line.
