### ISSUE TITLE
Warning on cdf in src/univariate/discrete/betabinomial.jl in v0.25.7

### ISSUE THREAD

**Issue by BoundaryValueProblems** [JuliaStats/Distributions.jl#1356]
With v0.25.7, I ran the test, which was passed without errors, yet generated the following warning message.
The contents of this warning message concerns me, so I want to post it here to ask if this should be OK or not.
Thanks!
```
 Testing Running tests...
WARNING: Method definition cdf(Distributions.BetaBinomial{T} where T<:Real, Int64) in module Distributions at C:\Users\xxx\.julia\packages\Distributions\nSnDu\src\univariate\discrete\betabinomial.jl:96 overwritten 
at C:\Users\xxx\.julia\packages\Distributions\nSnDu\src\univariate\discrete\betabinomial.jl:101.
  ** incremental compilation may be fatally broken for this module **
```

**Comment by devmotion** [comment]
Strangely it seems I am not able to reproduce the error message but https://github.com/JuliaStats/Distributions.jl/pull/1357 should fix the issue.
