### ISSUE TITLE
CI build failure with latest versions

### ISSUE THREAD

**Issue by t-bltg** [JuliaStats/Distributions.jl#1358]
Recent version (changes between `v0.25.6` which was OK and `v0.25.8` continuously fail our CI at https://github.com/JuliaPlots/Plots.jl.

We hit a failure here: https://github.com/JuliaPlots/StatsPlots.jl/blob/fadcdf7f2d9c91798b9a789b68835fa7896a2183/test/runtests.jl#L75

Reproducer
---------------
```julia
using Plots; gr()
using StatsPlots
using Distributions

main() = begin
  plot(Poisson(1))
  png("bug")
end

main()
```
Output
---------
```julia
ERROR: LoadError: MethodError: no method matching UnitRange(::Int64, ::Float64)
Closest candidates are:
  UnitRange(::T, ::T) where T<:Real at range.jl:289
Stacktrace:
  [1] yz_args(dist::Poisson{Float64})
    @ StatsPlots [...]/StatsPlots/yDVtk/src/distributions.jl:22
  [2] macro expansion
    @ [...]/StatsPlots/yDVtk/src/distributions.jl:31 [inlined]
  [3] apply_recipe(plotattributes::AbstractDict{Symbol, Any}, dist::Distribution)
    @ StatsPlots [...]/RecipesBase/92zOw/src/RecipesBase.jl:282
  [4] _process_userrecipes!(plt::Any, plotattributes::Any, args::Any)
    @ RecipesPipeline [...]/RecipesPipeline/a80Nu/src/user_recipe.jl:36
  [5] recipe_pipeline!(plt::Any, plotattributes::Any, args::Any)
    @ RecipesPipeline [...]/RecipesPipeline/a80Nu/src/RecipesPipeline.jl:70
  [6] _plot!(plt::Plots.Plot, plotattributes::Any, args::Any)
    @ Plots [...]/Plots/Bfn5f/src/plot.jl:204
  [7] plot(args::Any; kw::Any)
    @ Plots [...]/Plots/Bfn5f/src/plot.jl:89
  [8] plot
    @ [...]/Plots/Bfn5f/src/plot.jl:83 [inlined]
  [9] main()
    @ Main [...]/bug.jl:6
 [10] top-level scope
    @ [...]/bug.jl:10
in expression starting at [...]/bug.jl:10
```

**Comment by devmotion** [comment]
It seems changing https://github.com/JuliaPlots/StatsPlots.jl/blob/fadcdf7f2d9c91798b9a789b68835fa7896a2183/src/distributions.jl#L22 (which is a heuristic that will be incorrect for any discrete distribution whose support are not unitranges of integers) to
```julia
        lower, upper = default_range(dist)
        return (UnitRange(Int(lower), Int(upper)),)
```
should fix the issue.

**Comment by t-bltg** [comment]
Thanks for the quick reply, I will open a PR there.

**Comment by devmotion** [comment]
I also figured out which change in Distributions provoked the issue, I'll open a PR to fix it in Distributions. Probably it would still be helpful to ensure in StatsPlots that the arguments of `UnitRange` are integers.

**Comment by t-bltg** [comment]
> I also figured out which change in Distributions provoked the issue, I'll open a PR to fix it in Distributions. Probably it would still be helpful to ensure in StatsPlots that the arguments of `UnitRange` are integers.

If you want to open the PR in `StatsPlots` please do, I'm absolutely not familiar with StatsPlots ...

**Comment by t-bltg** [comment]
@devmotion, it's fixed from our side.

I'd like to thank you for the reactivity, it was very much appreciated :wink:
