### ISSUE TITLE
sampletype of Uniform

### ISSUE THREAD

**Issue by jw3126** [JuliaStats/Distributions.jl#1406]
It seems that Uniform always samples `Float64`?
```julia
using Distributions
@show typeof(rand(Normal(0f0, 1f0)))    # Float32 as expected
@show typeof(rand(Uniform(0f0, 1f0)))   # Float64 gotcha
```

**Comment by devmotion** [comment]
Yes, this is intended. Actually, `Normal` is the odd fish here.

I'll close this since it is a duplicate of https://github.com/JuliaStats/Distributions.jl/issues/1071.

**Comment by jw3126** [comment]
Ok thanks!
