### ISSUE TITLE
Generalized Pareto Distribution Fitting

### ISSUE THREAD

**Issue by ParadaCarleton** [JuliaStats/Distributions.jl#1431]
Would Distributions.jl accept a pull request from me adding the method described in [Zhang 2009](https://www.jstor.org/stable/40586625) for `fit(GeneralizedPareto)`?

**Comment by devmotion** [comment]
@sethaxen is already working on a PR: https://github.com/JuliaStats/Distributions.jl/pull/1422

**Comment by ParadaCarleton** [comment]
Ope, didn't notice, thanks!
