### ISSUE TITLE
`rand!(<:AbstractVector,<:Product)` produces a StackOverflowError

### ISSUE THREAD

**Issue by theogf** [JuliaStats/Distributions.jl#1432]
Here is a MWE:

```julia
julia> rand!(rand(3), Product(Normal.(rand(3))))
ERROR: StackOverflowError:
Stacktrace:
 [1] rand!(rng::MersenneTwister, A::Vector{Float64}, X::Product{Continuous, Normal{Float64}, Vector{Normal{Float64}}}) (repeats 79984 times)
   @ Random /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Random/src/Random.jl:266
```

**Comment by devmotion** [comment]
Hopefully `Product` is replaced or even removed soon: https://github.com/JuliaStats/Distributions.jl/pull/1391

**Comment by devmotion** [comment]
Oh I missed that you just used the wrong order here:
```julia
julia> rand!(Product(Normal.(rand(3))), rand(3))
3-element Vector{Float64}:
 1.013230726518833
 1.6283254723430067
 0.04968780335300771
```

**Comment by theogf** [comment]
Oh sorry you're right! I was stuck with the impression that traditionally the first argument of a argument modifying function was either a `function` for higher order function or the modified argument for the rest

**Comment by devmotion** [comment]
Yes, it's a bit weird inconsistency: https://github.com/JuliaStats/Distributions.jl/issues/1316

**Comment by theogf** [comment]
10 steps ahead as always 😂
