### ISSUE TITLE
use gamma(x+1), not factorial(x), for non-integer x

### ISSUE THREAD

**Issue by stevengj** [JuliaStats/Distributions.jl#1436]
This `factorial` method was removed from SpecialFunctions 2.0, since it was type piracy.   You should just call the `gamma` function directly and then update your Project.toml to support SpecialFunctions 2

See https://github.com/JuliaMath/SpecialFunctions.jl/pull/297

**Comment by devmotion** [comment]
I already checked the package, and it seemed we never call `factorial` with non-integer argument in the package itself. In https://github.com/JuliaStats/Distributions.jl/blob/35125579a77b938f8d4a8bd2be23cbf1f2ddf225/src/samplers/poisson.jl#L124 the argument is of type `Int`.

We only have to update the test https://github.com/JuliaStats/Distributions.jl/blob/a20ed4662f01620659668e512e1c4a74cdaf17a8/test/dirichletmultinomial.jl#L55.

**Comment by devmotion** [comment]
I planned to address this but only after fixing some other test errors :slightly_smiling_face:
