### ISSUE TITLE
Was v0.25.34 a breaking release?

### ISSUE THREAD

**Issue by navidcy** [JuliaStats/Distributions.jl#1447]
Was v0.25.34 a breaking one? Would it be better to be released as v0.26.0 following semver conventions?

**Comment by devmotion** [comment]
As far as I can see, none of the changes was breaking: https://github.com/JuliaStats/Distributions.jl/compare/v0.25.33...v0.25.34
It just added a new distribution and removed some internal functions.

**Comment by navidcy** [comment]
Hm... It's something else then! Thanks!
