### ISSUE TITLE
Posterior-predictive distributions

### ISSUE THREAD

**Issue by nfoti** [JuliaStats/Distributions.jl#145]
The interface for dealing with posterior distributions for Bayesian computations should include computing posterior-predictive distributions, that is the distribution of new observations conditioned on previous observations.  These have a variety of uses, for example:
1. Model checking (i.e. posteror-predictive checks).
2. Computing the probability of a new cluster in a Dirichlet Process mixture model.

I'm filing this issue as a reminder to myself to implement this when I have time, but if anyone else wants to take a stab at it that would be great.

**Comment by lindahua** [comment]
Should be moved to ConjugatePriors package.
