### ISSUE TITLE
Distributions over non-numeric sample space

### ISSUE THREAD

**Issue by ingmarschuster** [JuliaStats/Distributions.jl#147]
@StefanKarpinski's comment in issue #126 about discrete distributions on the natural numbers as a core construct also makes sense when trying to implement factor RVs in the R sense - categorical distributions with a sample space that is not necessarily a subset of numbers. Actually a student of mine is just now finishing his bachelors thesis where he implemented contingency tables in Julia (making use of DataFrames.jl actually) to represent distributions over non-numeric sample spaces. Would it make sense to integrate this in a more generic way into Distributions.jl? Most of the rest of what he has done is in representing BayesNets  and doing exact inference in them though.

Just opened a new issue because this was off topic in #126.

**Comment by matbesancon** [comment]
Closing for now, it seems having a different domain is just a "mapping" from a set to the Ints for a discrete non parametric
