### ISSUE TITLE
Median and quantile inconsistent for DiscreteUniform

### ISSUE THREAD

**Issue by sethaxen** [JuliaStats/Distributions.jl#1474]
As noted in the comment thread [here](https://github.com/JuliaStats/Distributions.jl/pull/1470#discussion_r783834396), it seems that the majority of (maybe all) discrete distributions `d` defined with a support `S` use the following implicit definition for `median`: `median = \inf_{x \in S} (cdf(d, x) \ge 1/2)`.

However, `DiscreteUniform` uses a different approach. Also, it's `quantile` implementation seems to be off by 1:

```julia
julia> d0 = DiscreteUniform(1, 4)
DiscreteUniform(a=1, b=4)

julia> cdf.(d0, 1:4)
4-element Vector{Float64}:
 0.25
 0.5
 0.75
 1.0

julia> median(d0)
2.5

julia> quantile.(d0, cdf.(d0, 1:4))
4-element Vector{Int64}:
 2
 3
 4
 5
```

**Comment by mschauer** [comment]
Ref https://github.com/JuliaStats/Distributions.jl/pull/1473
