### ISSUE TITLE
Quantile of Poisson raises error

### ISSUE THREAD

**Issue by sethaxen** [JuliaStats/Distributions.jl#1477]
Requesting the `1` quantile of `Poisson` raises an error, where the answer should be `Inf`, but the result is constrained to be an `Int`:

```julia
julia> quantile(Poisson(20), 1.0)
ERROR: InexactError: Int64(Inf)
```

**Comment by devmotion** [comment]
I'll close this issue since it is a duplicate of https://github.com/JuliaStats/Distributions.jl/issues/1415.
