### ISSUE TITLE
Add confidence interval function

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaStats/Distributions.jl#1481]
A somewhat normal thing to want to do with a distribution, is to compute a confidence interval.
When I first came to the julia statistics ecosystem, I found it very strange that I had to go to `HypothesisTests.jl` in order to find a `confint` function. Moreover, it only works on tests, and not distributions.

It is rather simple to make a `confint` function, at least for the distributions that I have worked with. Something like:
```
"""
    `confint(d, width; tail)`
    `confint(d; α, tail)`


Return a confidence interval of the distribution `d`.

Use the positional argument `width` or the keyword-argument α
to set the width of the interval, where `width=1-α`.

For a one-sided interval, where one "tail" extends to infinity, set
which tail should extend to infinity with the keyword argument `tail`.
Possible values are `:both` (default value), `:left` and `:right`.

Example:
julia> using Distributions

d = Normal();

julia> confint(d, 0.95)
(-1.9599639845400576, 1.9599639845400576)

julia> confint(d, α = 0.05)
(-1.9599639845400592, 1.9599639845400576)
"""
function confint(d::Distribution; α::AbstractFloat, tail::Symbol = :both)
    !(0 ≤ α ≤ 1) && error("The given interval width ($(1-α)) is not between 0 and 1.")
    if tail == :both
        return (quantile(d, α / 2), quantile(d, 1 - α / 2))
    elseif tail == :left
        return (-Inf, quantile(d, 1 - α))
    elseif tail == :right
        return (quantile(d, α), Inf)
    else
        error("Tail not recognized. Chose from :both, :left or :right.")
    end
end
confint(d::Distribution, width::AbstractFloat; kwargs...) = confint(d; α = 1 - width, kwargs...)

```

I feel like it is much more natural for `Distributions.jl` to implement this function, and for other packages, like `HypothesisTesting.jl`, to extend them.
Is there a reason why something like this has not been implemented?

**Comment by mschauer** [comment]
To me it seems  there is an misunderstanding what confidence intervals are. Are you looking for the `quantile` function?

**Comment by KronosTheLate** [comment]
If I was looking for the quantile function, how could I have used it in a function I made?

A quantile is a single number, whereas a confidence interval is defined by a lower and upper bound. They are fundamentally different things...

**Comment by mschauer** [comment]
I will close this with a remark: For the goal of making `Distributions` more accessible we should think of a way which has less friction and frustration than what happened here: you proposing something with good intentions and then us turning it down with equally good intentions.
