### ISSUE TITLE
Support for StaticArrays with MvNormal

### ISSUE THREAD

**Issue by btmit** [JuliaStats/Distributions.jl#1495]
It seems like a matter of adding a new constructor?

https://github.com/JuliaStats/PDMats.jl/issues/151#issuecomment-1022350269

**Comment by devmotion** [comment]
There's already a constructor that takes a pd matrix such as `PDMat`: https://github.com/JuliaStats/Distributions.jl/blob/master/src/multivariate/mvnormal.jl#L185

So you can already use a `PDMat` with static arrays, as explained in the PDMats.jl issue.

**Comment by btmit** [comment]
Yes, I understand you can force it with the incantation in the linked issue.

I was asking if it would be worthwhile to support something like`MvNormal(::SVector, ::SMatrix)` directly?

**Comment by devmotion** [comment]
I think this is an upstream issue and should be fixed not in Distributions but in PDMats by adding a `PDMat(::AbstractMatrix)` constructor. Then it would just work here: https://github.com/JuliaStats/Distributions.jl/blob/master/src/multivariate/mvnormal.jl#L201

**Comment by btmit** [comment]
Closed: https://github.com/JuliaStats/PDMats.jl/pull/131
