### ISSUE TITLE
No bounds checking in Chi distribution

### ISSUE THREAD

**Issue by pdeffebach** [JuliaStats/Distributions.jl#1497]
From discourse [here](https://discourse.julialang.org/t/plotting-two-distributions-on-same-plot/75475)

```

julia> pdf(Chi(3), -.5)
ERROR: DomainError with -0.5:
log will only return a complex result if called with a complex argument. Try log(Complex(x)).
```

Even though pdf should be 0 for `x < 0`. See [wiki](https://en.wikipedia.org/wiki/Chi_distribution). 

The problem is a `logpdf` function that does not check the bounds. See [here](https://github.com/JuliaStats/Distributions.jl/blob/8aea3cc82ee2f8ffe1e8cd754e7fcd99369c7a1c/src/univariate/continuous/chi.jl#L83)

```
logpdf(d::Chi, x::Real) = (ν = d.ν;
    (1 - ν/2) * logtwo + (ν - 1) * log(x) - x^2/2 - loggamma(ν/2)
)
```

**Comment by mschauer** [comment]
Agreed, it should return 0.
