### ISSUE TITLE
Inverse of CDF (quantile) is very different from python output

### ISSUE THREAD

**Issue by khalilT** [JuliaStats/Distributions.jl#1531]
Hi !

I want to estimate the inverse of CDF for a gamma distribution. I am using the `quantile()` function, but I am having results that are very different from the python `scipy.stat.norm.ppf()`.

- Python output (function called through PyCall):
`scipi.norm.ppf(gcdf)
360-element Vector{Float64}:
 NaN
 NaN
   0.2482756853553241
   0.6838618135003663
   1.0982522886339925
   0.8341461040398743
   0.5625941002249993
   0.14298558865505087
  -0.27051206493223956
  -0.5839180443363888
  -2.0253826308063525
 -Inf
  -1.6722849332519918
   ⋮
  -0.9866242147008234
  -0.784518407000245
   1.0758537008632716
   1.0758537008632716
   1.3337112136874723
   0.3783301933763916
   0.9815235926338941
   0.6336882583385112
   0.40684886419817634
  -0.897893175534235
  -0.9866242147008234
  -0.9866242147008234
`

- Julia output:
`Statistics.quantile(g,gcdf)
360-element Vector{Float64}:
 NaN
 NaN
   7.483333333333332
  12.34333333333333
  18.543333333333337
  14.406666666666666
  10.826666666666666
   6.543333333333334
   3.639999999999999
   2.1699999999999986
   0.06666666666666667
   0.0
   0.18999999999999997
   ⋮
   0.9999999999999997
   1.4999999999999998
  18.166666666666757
  18.166666666666757
  22.799999999999983
   8.76666666666667
  16.633333333333358
  11.699999999999946
   9.066666666666668
   1.1999999999999997
   0.9999999999999997
   0.9999999999999997` 

There is something wrong with the quantile output, as it should give the same values as ppf.

**Comment by devmotion** [comment]
The scipy call seems to compute quantiles of a normal distribution (note the `norm` in the function call) whereas the Julia version (could) evaluate quantiles for a gamma distribution.

**Comment by devmotion** [comment]
Please reopen with more information if the error persists if you use `scipy.stats.gamma.ppf`.
