### ISSUE TITLE
Exchangeable non-paramatetric distributions

### ISSUE THREAD

**Issue by malmaud** [JuliaStats/Distributions.jl#154]
Does this package have support for any of the common Bayesian non-parametric distributions, like the Chinese restaurant restaurant or Indian buffet process? Has thought been put into what the API would look like for representing and sampling from those kinds of stochastic objects?

**Comment by YSanchezAraujo** [comment]
Hi, just wondering if there ever was a package created for this? It seems like RandomProcesses didn't end up being maintained.
