### ISSUE TITLE
Sampling from truncated distribution sensitive to domain error

### ISSUE THREAD

**Issue by lf28** [JuliaStats/Distributions.jl#1546]
Random sampling from a truncated e.g. Beta distribution with parameters a=6014, b=2496 with a lower truncation limit set as 0.3 generates DomainError.

A MWE

`rand(truncated(Beta(6014, 2496), lower=0.3))` 

> ERROR: DomainError with -3.5931317534902634e266:
log will only return a complex result if called with a complex argument. Try log(Complex(x)).
Stacktrace:
 [1] throw_complex_domainerror(f::Symbol, x::Float64)
   @ Base.Math ./math.jl:33
 [2] _log(x::Float64, base::Val{:ℯ}, func::Symbol)
   @ Base.Math ./special/log.jl:304
 [3] log
   @ ./special/log.jl:269 [inlined]
 [4] betalogcdf(α::Float64, β::Float64, x::Float64)
   @ StatsFuns ~/.julia/packages/StatsFuns/6HmgG/src/distrs/beta.jl:59
 [5] logcdf
   @ ~/.julia/packages/Distributions/N1Ika/src/univariates.jl:623 [inlined]
 [6] truncated(d::Beta{Float64}, l::Float64, #unused#::Nothing)
   @ Distributions ~/.julia/packages/Distributions/N1Ika/src/truncate.jl:55
 [7] #truncated#549
   @ ~/.julia/packages/Distributions/N1Ika/src/truncate.jl:41 [inlined]
 [8] top-level scope
   @ REPL[10]:1

It seems v0.25.56 works fine.

**Comment by devmotion** [comment]
Sounds like an issue with StatsFuns 1 which replaced the Rmath implementation of `betalogcdf` with a native Julia implementation based on SpecialFunctions and HypergeometricFunctions (https://github.com/JuliaStats/StatsFuns.jl/blob/c8f50cff5c7cce4a455009be1221f020242ab8d5/src/distrs/beta.jl#L49). By downgrading Distributions you probably downgraded StatsFuns implicitly. You can confirm this by checking if it works with the latest Distributions versions and StatsFuns 0.9.

**Comment by lf28** [comment]
Thanks a lot for the quick reply. Yes, downgrading StatsFuns works. the problem indeed lies in StatsFuns.
