### ISSUE TITLE
No power law distribution?

### ISSUE THREAD

**Issue by Zireael07** [JuliaStats/Distributions.jl#1599]
Or should I just use lognormal instead, since the only difference seems to be the length of the tail?

**Comment by cgarling** [comment]
Might the [`Pareto`](https://juliastats.org/Distributions.jl/stable/univariate/#Distributions.Pareto) or [`GeneralizedPareto`](https://juliastats.org/Distributions.jl/stable/univariate/#Distributions.GeneralizedPareto) distributions do what you need? 

I recently used the Pareto distribution to implement a power-law distribution in a form that is more typical in my domain; it sounds like you probably want to do something similar.
