### ISSUE TITLE
`DirichletMultinomial` missing docstring

### ISSUE THREAD

**Issue by ParadaCarleton** [JuliaStats/Distributions.jl#1601]
There's no documentation for `DirichletMultinomial`, and it's also not clear to me what `α0` is supposed to be--the usual parametrization of a `DirichletMultinomial` is just in terms of `n` and `α`.

**Comment by devmotion** [comment]
A PR would be appreciated.

> it's also not clear to me what `α0` is supposed to be--the usual parametrization of a `DirichletMultinomial` is just in terms of `n` and `α`.

`α0` is an internal field that just caches `sum(abs, α)`: https://github.com/JuliaStats/Distributions.jl/blob/b9578723f742635ce5267df1de5bb877b40a2ec0/src/multivariate/dirichletmultinomial.jl#L7 Users shouldn't have to know about it and deal with it, similar to `alpha0` in `Dirichlet`: https://github.com/JuliaStats/Distributions.jl/blob/b9578723f742635ce5267df1de5bb877b40a2ec0/src/multivariate/dirichlet.jl#L25

**Comment by pri1311** [comment]
Hi, is there a way to check that the math I'm adding renders correctly?
