### ISSUE TITLE
zero covariance multivariate distribution

### ISSUE THREAD

**Issue by florian-die** [JuliaStats/Distributions.jl#1602]
Hi,

How can I get a multivariate distribution with a covariance of zero ? 

The following code fails

```julia
julia> Σ = zeros(2,2)
2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0

julia> μ = [1.0 ; 0.0]
2-element Vector{Float64}:
 1.0
 0.0

julia> dz = MvNormal(μ,Σ)
ERROR: PosDefException: matrix is not positive definite; Cholesky factorization failed.
```

but I can get a Normal distribution with zero variance and it does what I expect

```julia
julia> μ = 1.0
1.0

julia> dz = Normal(μ,0.0)
Normal{Float64}(μ=1.0, σ=0.0)

julia> rand(dz,5)
5-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0
```

Have I missed something ?

Thanks in advance for your help.

**Comment by devmotion** [comment]
`MvNormal` uses the interface of PDMats. I.e., internally it stores the positive (semi-)definite covariance matrices in an optimized form which then allows to make use of computational optimizations in the implementations of `rand` etc. automatically. Regular matrices are converted to `PDMats.PDMat` in the `MvNormal`. However, currently PDMats only supports positive definite matrices. Thus to be able to use positive semi-definite matrices you have to use e.g. PDMatsExtras and already provide the optimized form. You can do e.g.
```julia
julia> using Distributions, PDMatsExtras
[ Info: Precompiling Distributions [31c24e10-a181-5473-b8eb-7969acd0382f]

julia> Σ = zeros(2,2)
2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0

julia> μ = [1.0 ; 0.0]
2-element Vector{Float64}:
 1.0
 0.0

julia> dz = MvNormal(μ, PSDMat(Σ))
MvNormal{Float64, PSDMat{Float64, Matrix{Float64}}, Vector{Float64}}(
dim: 2
μ: [1.0, 0.0]
Σ: [0.0 0.0; 0.0 0.0]
)


julia> rand(dz, 5)
2×5 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0
 0.0  0.0  0.0  0.0  0.0
```

Note, however, that unfortunately currently `logpdf` does not support positive semi-definite matrices:
```julia
julia> logpdf(dz, [1.0, 0.0])
NaN

julia> logpdf(dz, [0.0, 0.0])
NaN
```

**Comment by florian-die** [comment]
This works for me, thanks for the help !
