### ISSUE TITLE
Scope of Distributions.jl

### ISSUE THREAD

**Issue by andreasnoack** [JuliaStats/Distributions.jl#162]
I was about to import `loglikelihood` from Stats to avoid the conflict, but I thought it might be better to have discussion about the scope of this package. In particular, I would like to discuss where to draw the line between Stats and Distributions. For me, the natural ordering here is to let Stats depend on Distributions and have all functionality related to statistical analysis in either Stats or a package that depends on Stats, i.e. not have statistical functionality in Distributions at all. As a consequence I think such things as `estimate`, `loglikelihood` and `kde` belong in Stats instead of Distributions. Otherwise we might just abandon Stats and pull all that stuff into Distributions. The current state is kind of messy. Please share your thoughts.

**Comment by lindahua** [comment]
The scope of this package seems to have been quite stable. 

Please feel free to reopen if you feel that we need further discussion.
