### ISSUE TITLE
abstract type AbstractMvNormal -> abstract type AbstractMvNormal{T}?

### ISSUE THREAD

**Issue by btmit** [JuliaStats/Distributions.jl#1621]
Would it be a breaking change to type AbstractMvNormal? 

I'm writing a few functions that dispatch to AbstractMvNormal rather than MvNormal and it would be helpful to have type parameter available.

**Comment by devmotion** [comment]
Can you explain what type parameters you want to dispatch on? Generally, currently a subtype of `AbstractMvNormal` does not have to have any type parameters at all.

Such a change would definitely be breaking as any subtype of `AbstractMvNormal` would be broken, similar to the following example:

```julia
julia> struct A{T} <: AbstractMatrix
       a::T
       end
ERROR: invalid subtyping in definition of A
Stacktrace:
 [1] top-level scope
   @ REPL[5]:1
```
For instance, https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/blob/6ee8549f536c6037a02a1cc445fd35c0811425ef/src/finite_gp_projection.jl#L7 would be broken.

**Comment by btmit** [comment]
You're correct. I had forgotten that it would _require_ ever subtype definition to include a type `T`.
