### ISSUE TITLE
Dirichlet pdf/ logpdf

### ISSUE THREAD

**Issue by banachtech** [JuliaStats/Distributions.jl#1652]
PDF values are > 1 for Dirichlet. Is this a bug?
e.g.

`julia> d = Dirichlet(rand(5))
Dirichlet{Float64, Vector{Float64}, Float64}(alpha=[0.9840238374293314, 0.5896290503027038, 0.6042923620679871, 0.46528579717957175, 0.8162969310390881])

julia> x = rand(d,1)
5×1 Matrix{Float64}:
 0.19013458947619696
 0.15042509250211755
 0.05324793614189979
 0.5513814391030434
 0.054810942776742304

julia> pdf(d, x)
1-element Vector{Float64}:
 10.772912099463028

julia> loglikelihood(d, x)
2.377034844541817

`

**Comment by sethaxen** [comment]
Why do you suspect this is a bug? While probability cannot exceed 1, density can and often does.

**Comment by banachtech** [comment]
That was a brain fart. My bad.

**Comment by sethaxen** [comment]
We've all been there!
