### ISSUE TITLE
Affine distributions with useless requirements ? 

### ISSUE THREAD

**Issue by lrnv** [JuliaStats/Distributions.jl#1653]
Hey, 
Why is it so that i cannot express an affine transformation of a gamma distribution ? 

```julia
julia> X = Normal(0,1)
Normal{Float64}(μ=0.0, σ=1.0)

julia> Y = Gamma(1,1)
Gamma{Float64}(α=1.0, θ=1.0)

julia> -X
ERROR: MethodError: no method matching -(::Normal{Float64})
Closest candidates are:
  -(::UnivariateDistribution, ::Real) at C:\Users\lrnv\.julia\packages\Distributions\gggmX\src\univariate\locationscale.jl:146    
  -(::T1, ::DataValues.DataValue{T2}) where {T1, T2} at C:\Users\lrnv\.julia\packages\DataValues\N7oeL\src\scalar\operations.jl:75
  -(::Any, ::ChainRulesCore.AbstractThunk) at C:\Users\lrnv\.julia\packages\ChainRulesCore\C73ay\src\tangent_types\thunks.jl:35   
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[426]:1

julia> (-1)*X
Normal{Float64}(μ=-0.0, σ=1.0)

julia> -Y
ERROR: MethodError: no method matching -(::Gamma{Float64})
Closest candidates are:
  -(::UnivariateDistribution, ::Real) at C:\Users\lrnv\.julia\packages\Distributions\gggmX\src\univariate\locationscale.jl:146        
  -(::T1, ::DataValues.DataValue{T2}) where {T1, T2} at C:\Users\lrnv\.julia\packages\DataValues\N7oeL\src\scalar\operations.jl:75    
  -(::Any, ::ChainRulesCore.AbstractThunk) at C:\Users\lrnv\.julia\packages\ChainRulesCore\C73ay\src\tangent_types\thunks.jl:35       
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[428]:1

julia> (-1)*Y
ERROR: DomainError with -1:
AffineDistribution: the condition σ > zero(σ) is not satisfied.
Stacktrace:
 [1] #77
   @ C:\Users\lrnv\.julia\packages\Distributions\gggmX\src\univariate\locationscale.jl:53 [inlined]
 [2] check_args
   @ C:\Users\lrnv\.julia\packages\Distributions\gggmX\src\utils.jl:89 [inlined]
 [3] #AffineDistribution#76
   @ C:\Users\lrnv\.julia\packages\Distributions\gggmX\src\univariate\locationscale.jl:53 [inlined]
 [4] AffineDistribution
   @ C:\Users\lrnv\.julia\packages\Distributions\gggmX\src\univariate\locationscale.jl:53 [inlined]
 [5] *(x::Int64, d::Gamma{Float64})
   @ Distributions C:\Users\lrnv\.julia\packages\Distributions\gggmX\src\univariate\locationscale.jl:144
 [6] top-level scope
   @ REPL[429]:1

julia> 
```

It would be usefull to do so in a `MixtureModel`, where each term of the mixture might have a different affine transformation applied to it. In particular, I would expect to be able to do the following: 

```
MixtureModel([Normal(0,1),6 - Gamma(1,1)],[1/2,1/2])
```

Is there another way to express this distribution or do I have to re-implement the mixture by hand ?

**Comment by ParadaCarleton** [comment]
Feel free to make a PR adding these methods, looks like a bug.

**Comment by lrnv** [comment]
And what about the last one ? Looks like the current `AffineDistributions` does not allow multiplication by a negative value of the Gamma distribution, for some reason (while the multiplication by a negative value of the normal distribution is already handeld by the Normal class itself).

**Comment by andreasnoack** [comment]
It's currently assumed that the scaling factor is positive in several of the expressions in https://github.com/JuliaStats/Distributions.jl/blob/432a7f93c0cb096b1852b01ef0abd678eba1bc60/src/univariate/locationscale.jl#L40 which is why there is this check, https://github.com/JuliaStats/Distributions.jl/blob/432a7f93c0cb096b1852b01ef0abd678eba1bc60/src/univariate/locationscale.jl#L42 that makes the Gamma version fails. It can probably be relaxed but will require some adjustments.

The first error looks like a missing method for unary `-`. The Normal distribution is handled without the `AffineTransformation` wrapper because the result is still a Normal.

**Comment by ParadaCarleton** [comment]
I’m writing a PR that should fix this.
