### ISSUE TITLE
`!` for Complementary functions

### ISSUE THREAD

**Issue by ParadaCarleton** [JuliaStats/Distributions.jl#1658]
Would it make sense to overload `!` on `cdf`, `ccdf`, `quantile`, etc. to make `!` return the complement? e.g. have `!cdf` return `ccdf`. I think this makes sense, and there's no risk of confusion since none of these functions return `Bool`.

**Comment by devmotion** [comment]
I think that's somewhat a misuse of `!`. The docstring of `!` says:
```julia
julia> @doc !(::Function)
  !f::Function

  Predicate function negation: when the argument of ! is a function, it returns a function which computes the boolean negation of f.

  See also ∘.

  Examples
  ≡≡≡≡≡≡≡≡≡≡

  julia> str = "∀ ε > 0, ∃ δ > 0: |x-y| < δ ⇒ |f(x)-f(y)| < ε"
  "∀ ε > 0, ∃ δ > 0: |x-y| < δ ⇒ |f(x)-f(y)| < ε"
  
  julia> filter(isletter, str)
  "εδxyδfxfyε"
  
  julia> filter(!isletter, str)
  "∀  > 0, ∃  > 0: |-| <  ⇒ |()-()| < "
```
However, (unsurprisingly) boolean negation is not defined for floating point numbers (or other number types) but only for booleans:
```julia
julia> !0.5
ERROR: MethodError: no method matching !(::Float64)
Closest candidates are:
  !(::Function) at operators.jl:1077
  !(::Bool) at bool.jl:35
  !(::Missing) at missing.jl:101
Stacktrace:
 [1] top-level scope
   @ REPL[4]:1
```

**Comment by ParadaCarleton** [comment]
> I think that's somewhat a misuse of `!`. The docstring of `!` says:

Right, so this would be overloading `!` to do something different on these functions. This should be fine; `!` usually means "Not," but in probability it makes sense to extend it to cover the probabilistic complement.

I just realized `¬` is free, though; if you think `!` is confusing, we can use that instead.

**Comment by sethaxen** [comment]
Why not the letter `c` for `complement` as is currently done? To me this is far preferable than changing the meaning of the `!` operator or introducing a unicode character to the API, which one should be cautious to do anyways.

**Comment by devmotion** [comment]
I'll close this issue as it seems, based on the comments and thumbs up, that currently there's no clear support for changing `ccdf` to `!cdf` or `¬cdf` etc.

**Comment by ParadaCarleton** [comment]
> 

I think a function called `c` would be pretty ambiguous; I was looking for a higher-order function here, to be clear.
