### ISSUE TITLE
Inconsistent (co)variance between `Normal` and `MvNormal`

### ISSUE THREAD

**Issue by Vilin97** [JuliaStats/Distributions.jl#1662]
`Normal` uses `σ` for standard deviation while `MvNormal` uses `Σ` (upper-case `σ`) for (co)variance. While changing `Normal` to use `σ` would be a major breaking change, there could be a warning about this. While it is in the docstring, this behavior is unintuitive enough that I personally missed it.

```
julia> using Distributions

julia> n1=MvNormal([0],2*ones(1,1))
FullNormal(
dim: 1
μ: [0.0]
Σ: [2.0;;]
)

julia> var(n1)
1-element Vector{Float64}:
 2.0

julia> n2=Normal(0,2)
Normal{Float64}(μ=0.0, σ=2.0)

julia> var(n2)
4.0
```

**Comment by Vilin97** [comment]
Looks like this issue has been noted by others, e.g. here: https://github.com/JuliaStats/Distributions.jl/issues/584
Feel free to close this if it does not add anything new.

**Comment by andreasnoack** [comment]
Yeah. I think this is covered by the issue you link to.
