### ISSUE TITLE
`Wishart` `rand` promotes to `Float64`

### ISSUE THREAD

**Issue by bvdmitri** [JuliaStats/Distributions.jl#1666]
The following code should not promote to `Float64`

```julia
julia> Wishart(3f0, [ 1f0;; ]) |> rand
1×1 Matrix{Float64}:
 1.7289491201235807
```

Works fine for other distributions (I didn't check all of them though):
```julia
julia> Normal(0f0, 1f0) |> rand
0.4961709f0

julia> MvNormal([ 0f0 ], [ 1f0 ]) |> rand
1-element Vector{Float32}:
 -0.06129361
```

`logpdf` seems to be fine for `Wishart`:
```julia
julia> logpdf(Wishart(3f0, [ 1f0;; ]), [1f0;;])
-1.4189385f0
```

**Comment by devmotion** [comment]
The weird ones are actually `Normal`/`MvNormal` - generally, samples are not supposed to be related to the type of the parameters, i.e., `eltype` and `partype` are different things.

There are a few related issues (e.g., https://github.com/JuliaStats/Distributions.jl/issues/1071, https://github.com/JuliaStats/Distributions.jl/issues/960) and even an open (but outdated) PR: https://github.com/JuliaStats/Distributions.jl/pull/1433 so I'll close this issue as a duplicate.
