### ISSUE TITLE
TriangularDist: pdf & cdf incorrectly specified

### ISSUE THREAD

**Issue by jwright11** [JuliaStats/Distributions.jl#1673]
I have two cases below of unexpected values w/ v0.25.80

`cdf(TriangularDist(0, 1, 1), 1)`
expecting a value of 1, receiving NaN

`pdf(TriangularDist(0, 1, 1), 1)`
expecting a value of 2 , receiving NaN

Will create a pull request to use the form of pdf & cdf shown on wikipedia which fixes the issue

**Comment by devmotion** [comment]
Fixed by #1674.
