### ISSUE TITLE
Broken `≈` for the Categorical distribution on Julia 1.6

### ISSUE THREAD

**Issue by bvdmitri** [JuliaStats/Distributions.jl#1675]
`isapprox` started to fail for the `Categorical` distribution on Julia 1.6. Works fine on other versions of Julia. Our CI started to fail recently, it check that the result of some computation is equal to some predefine answer with `isapprox`. These tests were working for at least a year as far as I remember, but started to fail recently only on Julia 1.6. 

MWE:

```bash
julia +1.6
```

```julia
julia> using Distributions

julia> Categorical([ 0.5, 0.5 ]) ≈ Categorical([ 0.5, 0.5])
ERROR: ArgumentError: step cannot be zero
Stacktrace:
  [1] steprange_last(start::Int64, step::Int64, stop::Int64)
    @ Base ./range.jl:221
  [2] StepRange
    @ ./range.jl:208 [inlined]
  [3] _rangestyle
    @ ./range.jl:118 [inlined]
  [4] _range
    @ ./range.jl:116 [inlined]
  [5] #range#57
    @ ./range.jl:91 [inlined]
  [6] -
    @ ./range.jl:1107 [inlined]
  [7] isapprox(x::Base.OneTo{Int64}, y::Base.OneTo{Int64}; atol::Int64, rtol::Int64, nans::Bool, norm::typeof(LinearAlgebra.norm))
    @ LinearAlgebra /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/generic.jl:1657
  [8] isapprox
    @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/generic.jl:1657 [inlined]
  [9] isapprox(c1::Categorical{Float64, Vector{Float64}}, c2::Categorical{Float64, Vector{Float64}})
    @ Distributions ~/.julia/packages/Distributions/bQ6Gj/src/univariate/discrete/discretenonparametric.jl:70
 [10] top-level scope
    @ REPL[2]:1
```

```julia
julia> versioninfo()
Julia Version 1.6.7
Commit 3b76b25b64 (2022-07-19 15:11 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```

Works fine on Julia 1.8:

```julia
julia> Categorical([ 0.5, 0.5 ]) ≈ Categorical([ 0.5, 0.5])
true
```

Related CI: https://github.com/biaslab/ReactiveMP.jl/actions/runs/4087611306 (it includes other test failures as well, but I'm not sure if these are related)

**Comment by devmotion** [comment]
It seems the problem is the definition of `isapprox(::Base.OneTo, ::Base.OneTo)` in LinearAlgebra, which is called by https://github.com/JuliaStats/Distributions.jl/blob/b7916c62c4c916cffddb189dc67cbc39c5ea8670/src/univariate/discrete/discretenonparametric.jl#L70 (or more specifically `support(c1) ≈ support(c2)`). In Julia 1.6 it seems to cause problems with ranges: https://github.com/JuliaLang/julia/pull/36656

**Comment by bvdmitri** [comment]
I wonder though, does it make a lot of sense to check the support of the Categorical distribution approximately? Some may argue that the `≈` operation between two Categorical distribution should only check that probabilities are approximate, but the support should not be check with  `≈`, but rather with `==`?

**Comment by devmotion** [comment]
`Categorical` is just a special case but it seems this definition in Distributions is supposed to cover more general discrete non-parametric distributions for which the support can be e.g. vectors of floating point numbers - and checking equality of floating point numbers seems a bit brittle.

**Comment by devmotion** [comment]
More generally, I'd also argue that approximate inequality of distribution corresponds to some distance (Wasserstein, or MMD) between distributions being approximately zero. For distances such as Wasserstein or MMD this does not require the support to be equal. Maybe we should just define `isapprox(...; rtol, atol, ...)` of two univariate `DiscreteNonParametric` distributions via `isapprox(...; rtol, atol, ...)` of their Wasserstein distance to make the approximate equality checks a bit more principled.

**Comment by bvdmitri** [comment]
Well, I agree with you and after thinking about it more I don't see a big problem with the current implementation from a theoretical point of view. The support can indeed be checked for equality approximately.

IMO the problem lies purely in programming domain. As you pointed out, the issue is that `isapprox` is simply broken on `1.6` for ranges, and it doesn't seem that the fix is going to be back-ported. The solution could be just to define a custom method for `Categorical` that does not use `isapprox` on ranges (because in contrast with generic `DiscreteNonParameteric`, the `Categorial` as an alias always uses ranges AFAIU), but rather something like `custom_isapprox` that dispatches and implements custom logic for ranges (this custom logic can be even copy-pasted from the newer Julia versions).

I sometimes also do such hot-fixes in my packages, e.g. [here](https://github.com/biaslab/ReactiveMP.jl/blob/master/src/fixes.jl).

**Comment by devmotion** [comment]
There's no need for a `custom_isapprox`, #1683 fixes the issue (and another related one) by just adding an implementation of `isapprox` for `Categorical`.

**Comment by bvdmitri** [comment]
Thanks for the fix! adding a custom method for `Categorical` is exactly what I've meant.
