### ISSUE TITLE
Reproducibility with global rng & distributions with Julia 1.8.5

### ISSUE THREAD

**Issue by odunbar** [JuliaStats/Distributions.jl#1687]
Hi folks - I'm not sure if this is a `Random` or a `Distributions` issue. It could be either/both. At the very least this may be of interest to you.

### Setup
On Julia `1.8.5` , and `Distributions v0.25.85`

### Issue 
Repeated calls to `rand(...,1)`, `N` times, no longer appears to give the same as `rand(...,N)` . 
```julia
using Random, Distributions, LinearAlgebra
seed = 1000
d = MvNormal(zeros(4),I)

Random.seed!(seed)
X = [rand(d) rand(d)]
Random.seed!(seed)
Y = rand(d,2)

X == Y # false
```

### Odd thing 1: The behaviour depends on the distribution
```julia
using Random, Distributions, LinearAlgebra
seed = 1000
d = MvNormal(zeros(3),I)

Random.seed!(seed)
X = [rand(d) rand(d)]
Random.seed!(seed)
Y = rand(d,2)

X == Y # true
```
i.e. changing to a `<4` dimensional `MvNormal` does not display the same behaviour, here we do get consistency between `rand(...,1)` and `rand(...,N)`. (Is this an artifact from a method change when dim `>3`?)

### Odd thing 2: The behaviour depends on the type of rng
```julia 
using Random, Distributions, LinearAlgebra 
seed = 1000
d = MvNormal(zeros(4),I)
rng = Random.MersenneTwister(seed)
Y = rand(rng,d,3) 
rng = Random.MersenneTwister(seed)
X = [rand(rng,d) rand(rng,d) rand(rng,d)]

X == Y # true
```
i.e. using an explicit rng seems to also resolve this in these settings.

Thanks for your time! 
Cheers, 
Ollie

**Comment by devmotion** [comment]
To me it seems this is not a Distributions issue:
```julia
julia> using Random

julia> Random.seed!(1000);

julia> X = [randn() for _ in 1:20];

julia> Random.seed!(1000);

julia> Y = randn(20);

julia> X == Y
false
```

Generally, Julia does not guarantee this kind of consistency. And I assume, due to #1679 and #1680 we observe the same behaviour in Distributions.

IMO it's fine - and not completely surprising - that the results deviate in this example: for performance reasons I would expect (haven't checked if that's actually the case) `randn(n)` and `randn()` to dispatch to different algorithms.

**Comment by odunbar** [comment]
Thanks for clearing this up. 

It came from a series of unit tests making sure our randomness is safely used, here it was surprising that a couple of them failed, because the "standard" they were testing against changed behaviour, and only in some `Distributions` cases.

**Comment by bvdmitri** [comment]
@odunbar Julia does not guarantee any consistent behaviour for built-in random number generators even between patch versions. It may change suddenly for performance reasons. If you would like consistent behaviour in tests, take a look on https://github.com/JuliaRandom/StableRNGs.jl
