### ISSUE TITLE
branches to ensure that mgf returns something other than NaN

### ISSUE THREAD

**Issue by gjkerns** [JuliaStats/Distributions.jl#173]
Both the Moment Generating Function `mgf(..., t)` and the Characteristic Function `cf(..., t)` should equal `1` when `t = 0`.  When it comes to computer formulas you almost always get this for free, but there are a couple cases where you don't, for example, the `Uniform(a,b)` distribution:

```
julia> mgf(Uniform(0,1), 0)
NaN
``` 

Another example is the `Logistic` distribution.  I got around this in the `prob` package for `R` by adding a special preliminary check for whether `t = 0`, and if so, to return the value `1`.  This may or may be the right way to fix this in Julia. In any case, this issue is to discuss adding branches to ensure that `mgf` returns something other than `NaN`.

**Comment by simonbyrne** [comment]
Closed by 3a1cf22c182f3043a4dd0c32c7acd603b483eddf
