### ISSUE TITLE
Wiener First Passage Time Distribution

### ISSUE THREAD

**Issue by carolfs** [JuliaStats/Distributions.jl#1749]
Are there plans to include the Wiener First Passage Time distribution? For the PDF and CDF, there is already an R package whose code can be translated to Julia: https://github.com/yeagle/RWiener/tree/master

**Comment by mschauer** [comment]
Can you specify the distribution a bit - passage from where to where?

**Comment by carolfs** [comment]
The first time a particle in 1D Brownian motion crosses a boundary. Widely used in Psychology to model binary decisions. For example:

Krajbich, I., & Rangel, A. (2011). Multialternative drift-diffusion model predicts the relationship between visual fixations and choice in value-based decisions. Proceedings of the National Academy of Sciences, 108(33), 13852-13857.

**Comment by mschauer** [comment]
You mean a Levy distribution? The time of hitting a single point, at distance α
from the starting point, by the Brownian motion has the Lévy distribution with parameter α^2  https://juliastats.org/Distributions.jl/stable/univariate/#Distributions.Levy

**Comment by carolfs** [comment]
I don't think so. First, there is a drift, and second, there is an upper and a lower boundary. The particle must hit the upper boundary without hitting the lower one.

**Comment by mschauer** [comment]
That’s why I am asking 
> Can you specify the distribution a bit - passage from where to where?

**Comment by carolfs** [comment]
Here is a full explanation: https://journal.r-project.org/archive/2014-1/vandekerckhove-wabersich.pdf

**Comment by ParadaCarleton** [comment]
> Are there plans to include the [x] distribution?

90% of the time the answer is "yes, as soon as someone makes a PR for it" :smile:

**Comment by carolfs** [comment]
I might convert the R code to Julia eventually ...

**Comment by mschauer** [comment]
If I understand the linked document correctly the implementation of the density involves an approximation which is a bit worse than what we use in Distributions.jl but works for the use case of modelling decision processes - that would suggest a specialised package for this.

**Comment by carolfs** [comment]
Well, if there are no closed analytical formulas for the PDF, all we can do is approximate it.

**Comment by mschauer** [comment]
Yes exactly! That’s makes testing “approximate correctness” not so easy for example

**Comment by carolfs** [comment]
We can test that it is a correct implementation of the approximated formula.

**Comment by DominiqueMakowski** [comment]
You might be interested in https://github.com/itsdfish/SequentialSamplingModels.jl
