### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by spaette** [JuliaStats/Distributions.jl#1753]
dumping strings from the repo exposed a solitary typo

instability

```
$ grep -nr instabililty Distributions.jl
Distributions.jl/src/univariate/continuous/weibull.jl:154:    # first iteration outside loop, prevents type instabililty in α, ϵ
$ 
```
 
fix
 
```
 sed -i "s/instabililty/instability/g" Distributions.jl/src/univariate/continuous/weibull.jl
```

possibly replace `Cumulated` with `Cumulative` here

```
$ ed -s Distributions.jl/src/common.jl <<<'148,155p'
"""
    Distribution{F<:VariateForm,S<:ValueSupport} <: Sampleable{F,S}

`Distribution` is a `Sampleable` generating random values from a probability
distribution. Distributions define a Probability Distribution Function (PDF)
to implement with `pdf` and a Cumulated Distribution Function (CDF) to implement
with `cdf`.
"""
$ 
```
fix

```
sed -i "s/Cumulated/Cumulative/g" Distributions.jl/src/common.jl
```

**Comment by spaette** [comment]
@devmotion 

Regarding the typo I can open a pull.

> possibly replace `Cumulated` with `Cumulative` here

Have you an opinion on this suggested change?

**Comment by devmotion** [comment]
IMO both suggestions are reasonable (I've never encountered the term "cumulated distribution function"). Can you open a PR?

**Comment by spaette** [comment]
these in `#1681` had escaped my attention

**Comment by spaette** [comment]
_cf_: `https://byjus.com/maths/probability-density-function/`

as an afterthought, factually is the language precise

generally Probability Density Function is corresponding to PDF
