### ISSUE TITLE
Why not `Base.in` for the `support` (e.g. `RealInterval`)

### ISSUE THREAD

**Issue by bvdmitri** [JuliaStats/Distributions.jl#1756]
The following fails, but it should not really

```julia
julia> using Distributions

julia> support(Gamma)
RealInterval{Float64}(0.0, Inf)

julia> 1.0 ∈ support(Gamma)
ERROR: MethodError: no method matching iterate(::RealInterval{Float64})

Closest candidates are:
  iterate(::Union{LinRange, StepRangeLen})
   @ Base range.jl:880
  iterate(::Union{LinRange, StepRangeLen}, ::Integer)
   @ Base range.jl:880
  iterate(::T) where T<:Union{Base.KeySet{<:Any, <:Dict}, Base.ValueIterator{<:Dict}}
   @ Base dict.jl:698
  ...

Stacktrace:
 [1] in(x::Float64, itr::RealInterval{Float64})
   @ Base ./operators.jl:1282
 [2] top-level scope
   @ REPL[4]:1
```

The problem is that 
```
julia> Distributions.in === Base.in
false
```

It can be easily fixed if added in the `Distributions`
```
import Base: in 
```

**Comment by bvdmitri** [comment]
This works
```julia
julia> Distributions.in(1.0, support(Gamma))
true
```
but is unnecessarily complex and does not work with supports defined in [DomainSets](https://github.com/JuliaApproximation/DomainSets.jl).

Simply letting `1.0 ∈ support(Gamma)` would be great

**Comment by devmotion** [comment]
Indeed, I think it was just forgotten to qualify this definition when it was added in https://github.com/JuliaStats/Distributions.jl/pull/312 and it has never been tested. Do you want to open a PR?

**Comment by bvdmitri** [comment]
Sure, np. I will prepare a PR during this week.

**Comment by bvdmitri** [comment]
@devmotion So while adding new tests I've noticed that the `support` function does not really work for all distributions.
For example for discrete distributions with unbounded support the `support` function throws an error, because it cannot create a range. 

```julia
julia> support(NegativeBinomial)
ERROR: InexactError: trunc(Int64, Inf)
Stacktrace:
 [1] trunc
   @ ./float.jl:893 [inlined]
 [2] round(#unused#::Type{Int64}, x::Float64)
   @ Base ./float.jl:384
 [3] support(d::Type{NegativeBinomial})
   @ Distributions ~/.julia/packages/Distributions/L19D5/src/univariates.jl:111
 [4] top-level scope
   @ REPL[3]:1
```

This happens because the `support` function for discrete distributions assumes that the support is bounded, which is not always the case.

In my [fork](https://github.com/bvdmitri/Distributions.jl/commit/b6f5ab47529b0b4947793e8e6ee9406bb75d24d8) I created a `DiscreteInterval` structure, however, I'm not sure if you really want this change. Do you want me to fix the failing support (but potentially break some other code which depends on the fact that the support of discrete distributions is of type range), or do you want to keep the current behaviour and throw an error instead?

In my opinion, there is no real reason to throw an error for unbounded discrete distributions and you can return a suitable structure, which, if possible, materializes to a range.  I want to know your opinion on that. I can revert the change and modify tests accordingly.

**Comment by devmotion** [comment]
This is a known bug (there is some open issue already). However, I am not sure if it is desirable to add more types, I wonder if it would be better to just use DomainSets or some other package that already provides such functionalities. Due to these design questions I think it would be preferable to fix this problem separately and not combine it with a fix for `in`.

**Comment by bvdmitri** [comment]
I get you point. I would revert the new structure and only fix the `in` separately for now. 

In my opinion, using the `DomainSets` is an amazing idea. For us personally, we already use the `DomainSets` as a default to describe supports for distributions in our packages, but adding the `RealInterval` as a special case everywhere (because it is not sub-typed from `DomainSets`)
