### ISSUE TITLE
Move `entropy` to StatsAPI.jl and import it from there?

### ISSUE THREAD

**Issue by Datseris** [JuliaStats/Distributions.jl#1759]
Hi there, we are also defining and exporting `entropy` in ComplexityMeasures.jl in different context (by providing ways to discretize data into probability mass functions). Would be great if we can get the same entropy name. There is no conflict because we also define types for each discretization format. 

Would you agree to put entropy into StatsAPI.jl and import it from there?

**Comment by Datseris** [comment]
cc @nalimilan

**Comment by devmotion** [comment]
It's defined in StatsBase, so you don't have to depend on Distributions if you want to use the same function.

**Comment by Datseris** [comment]
Is teh StatsBase version what is imported here? I am hoping to avoid conflicts iwth Distributions,.jl

**Comment by devmotion** [comment]
Yes.
