### ISSUE TITLE
Accept Transducers.jl as a Dependency?

### ISSUE THREAD

**Issue by ParadaCarleton** [JuliaStats/Distributions.jl#1767]
Many functions--e.g. `mean`, `variance`, etc.--could be made parallelizable, faster, shorter, and more general--by accepting Transducers.jl as a dependency, and it would substantially simplify the implementation of some features. I find myself reaching for it but having to use clumsier iterators or broadcasting methods often.

Luckily, Transducers.jl is now being maintained by Mason Protter and the rest of the people working on the JuliaFolds ecosystem.

Should we accept Transducers as a dependency?

**Comment by devmotion** [comment]
We have always be reluctant with adding more dependencies, and Transducers is a heavy dependency. Without any clear benefits I don't think it should be added.

**Comment by ParadaCarleton** [comment]
Ugh, wait, I meant to open this in StatsBase.jl.
