### ISSUE TITLE
`MvNormal` Disrupts Array Types

### ISSUE THREAD

**Issue by ParadaCarleton** [JuliaStats/Distributions.jl#1768]
```julia
julia> using DimensionalData

julia> z = randn(3, 3) |> x->x' * x |> x->DimArray(x, (ax1=[:x, :y, :z], ax2=[:x, :y, :z]))
3×3 DimArray{Float64,2} with dimensions: 
  Dim{:ax1} Categorical{Symbol} Symbol[:x, :y, :z] ForwardOrdered,
  Dim{:ax2} Categorical{Symbol} Symbol[:x, :y, :z] ForwardOrdered
        :x         :y         :z
  :x   3.2005    -0.550321  -0.538308
  :y  -0.550321   2.14419   -2.98709
  :z  -0.538308  -2.98709    5.92229

julia> typeof(MvNormal(z))
ZeroMeanFullNormal{Tuple{OneTo{Int64}}} (alias for MvNormal{Float64, PDMats.PDMat{Float64, Array{Float64, 2}}, FillArrays.Zeros{Float64, 1, Tuple{Base.OneTo{Int64}}}})

julia> rand(MvNormal(z))
3-element Vector{Float64}:
 -0.14355464178021315
  1.076531030969517
 -0.666861987973966

```

**Comment by devmotion** [comment]
This is expected? We don't intend to propagate parameter types to the variates in the current design (it's actually considered a bug where this happens).

(As a side remark, the "problem" here does already happen at an earlier stage in PDMats it seems - the parameters are already dimensionless.)

**Comment by ParadaCarleton** [comment]
> We don't intend to propagate parameter types to the variates in the current design (it's actually considered a bug where this happens).

Wait, what? That seems wrong. It would suggest that Distributions.jl could never work with, say, GPUArrays. The user inputs should determine the output types.

**Comment by ParadaCarleton** [comment]
> (As a side remark, the "problem" here does already happen at an earlier stage in PDMats it seems - the parameters are already dimensionless.)

That seems correct--I'll open the issue there.
