### ISSUE TITLE
Handle SparseArrays via Pkg extention?

### ISSUE THREAD

**Issue by oschulz** [JuliaStats/Distributions.jl#1802]
Can we turn SparseArrays into a weak dependency? It adds quite a bit to the load time of Distributions. From what I can see, we don't use it in methods that don't also have a sparse array as an argument, right?

**Comment by devmotion** [comment]
SparseArrays is only a test dependency, so this is rather a task for the dependencies of Distributions. I'm not sure about other dependencies, but for PDMats there is already an open PR: https://github.com/JuliaStats/PDMats.jl/pull/188

**Comment by oschulz** [comment]
Sorry @devmotion , I misread my `@time_imports` output, overlooked an indent. Sorry for the noise.
