### ISSUE TITLE
`inv*` functions are not really inverses

### ISSUE THREAD

**Issue by aplavin** [JuliaStats/Distributions.jl#1813]
There is an inconsistency between the documentation (and name) of functions like `invlogcdf` and their actual behavior. They are claimed to be inverses (to `logcdf`), so should presumably error when inverting is not possible. However, they still return some result in these cases, which definitely isn't the proper inverse:
```julia
help?> invlogcdf
  invlogcdf(d::UnivariateDistribution, lp::Real)
  The inverse function of logcdf.

julia> d = Uniform(0, 1)

julia> invlogcdf(d, logcdf(d, -5))
0.0
```

**Comment by andreasnoack** [comment]
Please try to outline the behavior that you are proposing? Are you proposing that the `inv` methods error out for all values where the `cdf` isn't one-to-one? Avoiding exceptions is often convenient so I'm not sure the current behavior is undesirable. We could expand the documentation to explain the behavior at the boundary of the support.

**Comment by jaksle** [comment]
I have problems understanding this example and the problem in general. CDF of $\mathcal U(0,1)$ is straight line $x\mapsto x$. So logcdf is $x\mapsto \ln(x)$. Point $x=-5$ is outside of $\mathcal U(0,1)$ support; thus assuming `logcdf(-5) == -Inf` is the most reasonable choice. Note it has nothing to do with invlogcdf which is just $y\mapsto \exp(y)$ both analytically and numerically.

**Comment by jaksle** [comment]
The function `invlogcdf(Uniform(0,1),y)` is just $y\mapsto \exp(y)$ function. You can check what is called when it is used and indeed, `exp(x)` is called. You can make a plot if you doubt it. It is defined for any $y\in \mathbb R$ and mathematically speaking, no other choice is possible.

Value $x = 5$ is also outside support of $\mathcal U(0,1)$. CDF function is not a bijection there its inverse (quantile function) is mathematically defined as a "generalized inverse". This is standard. The Julia behaviour is consistent with this mathematical definition.

**Comment by sethaxen** [comment]
It seems what the docstring for `invlogcdf` fails to do is be explicit about what it means by "inverse". Specifically, what's missing is what `invlogcdf(d, logcdf(d, x))` should return when `x` is not in the support of the distribution or for continuous distributions is the endpoint of an open interval that is not in the support of the distribution. In these cases `logcdf` is not strictly monotonic (it has horizontal line segments), but one can still define a notion of inverse as the minimum point in any such line segment.

I think Distributions uses the definition `invlogcdf: logp → infimum{x ∈ support(d) : logcdf(d, x) ≥ logp}`. As noted in https://en.wikipedia.org/wiki/Quantile_function, this is an "almost sure left inverse" of `logcdf`, i.e. the set of all points where `invlogcdf(d, logcdf(d, x)) != x` has a total probability mass of 0.

I suggest we can resolve this by adding a note in the docstring that `invlogcdf` is the unique function that satisfies `invlogcdf(d, logp) ≤ x` iff `logp ≤ logcdf(d, x)` for all real `x`, although to me the description in terms of the infimum is more intuitive. `quantile` would need a similar note.

**Comment by jaksle** [comment]
@sethaxen I checked before. `Distributions.jl` is not consistent with its behaviour. E.g. `quantile` for `TriangularDist` returns error for $x > 1$, whereas `quantile` for `Uniform` returns $x$ for $x>1$. `Uniform` is not internally consistent here, as `logcdf` returns 0 for $x>1$ not $\ln(x)$. However, as I mentioned above, this leads to a reasonable behaviour of inverse applied to the original in this case.

As written in the Wikipedia article that you mention, quantile function is defined for $0\le x \le 1$ and is a generalized inverse of CDF there. There is no standard agreement what to do for larger domain.

**Comment by sethaxen** [comment]
I don't see any good reason to extend the support of `quantile` to beyond `[0, 1]`. The whole point of the function is to provide in some sense an inverse to `cdf`, and `cdf` cannot produce outputs outside of that range.

> `quantile` for `Uniform` returns x for x>1.

One could definte `quantile` in such a way that this is the right behavior, but I think that would be a very strange way to define it. `cdf`'s outputs are probabilities, and accepting a negative probability as input to `quantile` is very strange.

**Comment by jaksle** [comment]
It is speculation, but the reason for $x\mapsto x$ everywhere was probably just the simplicity of the code and speed. Documentation of `quantile` mentions it is defined on $0 \le x \le 1$ so I guess the philosophy of `Distributions.jl` is to leave it unspecified and the same goes for `invlogcdf` which is internally just `quantile(d,exp(y))`. I doubt it will be changed, though adding that `invlogcdf` has domain $x\le 0$ seems like a good idea.

**Comment by sethaxen** [comment]
I proposed changes to the docs in #1814
