### ISSUE TITLE
Rename `ValueSupport` subtypes to more specific names

### ISSUE THREAD

**Issue by juliohm** [JuliaStats/Distributions.jl#1870]
Currently the subtypes of `ValueSupport` are `Discrete` and `Continuous` as described here:

https://github.com/JuliaStats/Distributions.jl/blob/b356da03a189d023cdb8467c61806a8a11dcb262/docs/src/types.md?plain=1#L34-L50

These names are too generic to export, and conflict with other mathematical packages.

Would you be ok with renaming these two to `DiscreteSupport` and `ContinuousSupport`?

I can work on a PR that includes a deprecation warning.

**Comment by devmotion** [comment]
Is there an actual problem/conflict with some other package? My initial feeling is that we should only make such a change if it's worth it.
