### ISSUE TITLE
Who is maintaining Distributions.jl?

### ISSUE THREAD

**Issue by juliohm** [JuliaStats/Distributions.jl#1871]
There are 316 open issues and 100 open pull requests. If no one is actively maintaining this package, I can help.

**Comment by devmotion** [comment]
Based on https://github.com/JuliaStats/Distributions.jl/commits/master/, a few contributors from JuliaStats such as @andreasnoack, @ViralBShah, @mschauer and me.

**Comment by juliohm** [comment]
Thanks.

**Comment by ViralBShah** [comment]
More maintainers are always welcome. There are a lot of PRs and issues with active discussion. Perhaps where things may be helpful is in tagging folks on stale issues or PRs that can be closed, or others that can be potentially merged.

My contributions have mainly been to help keep the package infrastructure updated (recently).
