### ISSUE TITLE
Multiplication of ScalMat and FillArray is ambiguous

### ISSUE THREAD

**Issue by Wu-Chenyang** [JuliaStats/Distributions.jl#1925]
The following code runs into errors. 
```julia
julia> using PDMats, Distributions, LinearAlgebra
julia> ScalMat(3, 1) * MvNormal(I(3))
ERROR: MethodError: *(::ScalMat{Int64}, ::Falses{1, Tuple{Base.OneTo{Int64}}}) is ambiguous.

Candidates:
  *(a::ScalMat, x::AbstractVector)
    @ PDMats ~/.julia/packages/PDMats/cAM9h/src/scalmat.jl:43
  *(a::AbstractMatrix{T}, b::FillArrays.AbstractZeros{T, 1} where T) where T
    @ FillArrays ~/.julia/packages/FillArrays/lVl4c/src/fillalgebra.jl:103

Possible fix, define
  *(::ScalMat{T}, ::FillArrays.AbstractZeros{T, 1} where T) where T<:Real
```
This is due to the compatibility issue of `ScalMat` and `FillArrays` and can be fixed by, e.g., replacing the `Falses(3)` mean vector with `zeros(3)` or the `ScalMat(3, 1)` with `I(3)`. Maybe I should submit this issue to `FillArrays` or `PDMats`?

**Comment by devmotion** [comment]
Yes, to me this seems to be an issue of FillArrays + PDMats. Note that FillArrays already has an extension for PDMats, so IMO the missing method should be defined there.

**Comment by Wu-Chenyang** [comment]
Thanks for your helpful response! I'll close this issue and submit it to `FillArrays`.
