### ISSUE TITLE
Add RNG argument to rand calls

### ISSUE THREAD

**Issue by simonbyrne** [JuliaStats/Distributions.jl#197]
There seems to have been some recent additions to Base that allows for the RNG to be used as a first argument to `rand` and `rand!`. Once that has been sorted out, we should probably do it here as well: perhaps this could be done in a similar manner to the handling of `IO` objects in `show`?

**Comment by sunoru** [comment]
Hi, I noticed that the dependence on neither Rmath nor dSFMT have been removed, and functions in Base have been made consistent with a first argument of RNG. So is there anyone working on this? If not I want to have a try and will make a PR.

BTW do you think we should store the RNG object in Distribution types or just add an argument when using functions like `rand`?

**Comment by sunoru** [comment]
Oh.. The Rmath stuff was just moved to StatsFuns, so it's still unable to add the RNG argument to every sampling functions..

**Comment by matbesancon** [comment]
should we close this in favour of #606 ? cc @simonbyrne

**Comment by matbesancon** [comment]
awesome thanks
