### ISSUE TITLE
Multivariate observations with missing components

### ISSUE THREAD

**Issue by nfoti** [JuliaStats/Distributions.jl#219]
The current Distributions package seems to be unable to handle multivariate observations where some subset of the components are missing.

A straight-forward way to handle this case would be to implement versions of the multivariate distributions that take `DataArray`s as arguments.  These versions would not include the missing observations in computations.  Unfortunately, this requires reimplementing a lot of the functions for the multivariate distributions with minor modifications (in the ML or posterior functions the number of observations used to update each component is different).

Any alternative ideas to handle this type of data would be great.

**Comment by axsk** [comment]
Since some time has passed, has somebody come across a package handling the above problem?
I also need to evaluate the pdf where the missing values get marginalized out and wrote my own routines, but was wondering whether there was a place to push/compare these to.

**Comment by ararslan** [comment]
Use DataArrays with `filter(!isna, x)` to remove missing values.
