### ISSUE TITLE
MvNormal fails with integers

### ISSUE THREAD

**Issue by setzler** [JuliaStats/Distributions.jl#279]
MvNormal fails if the mean or variance is defined with integers rather than floats. Please include type conversion, as used elsewhere in Julia, for example, [1,1]'*[1.0,1.0] returns Array{Float64,1}, when the first term is Array{Int64,1} and the second is Array{Float64,1}. 

julia> MvNormal([1,0],eye(2))
ERROR: `GenericMvNormal{PDMat}` has no method matching GenericMvNormal{PDMat}(::Array{Int64,1}, ::Array{Float64,2})

julia> MvNormal([1,0.0],eye(2))
GenericMvNormal{PDMat} distribution
Dim: 2
Zeromean: false
Μ:
[1.0,0.0]
Σ: PDMat(2,2x2 Array{Float64,2}:
 1.0  0.0
 0.0  1.0,Cholesky{Float64} with factor:
2x2 Triangular{Float64,Array{Float64,2},:U,false}:
 1.0  0.0
 0.0  1.0)

**Comment by andreasnoack** [comment]
This is fixed
