### ISSUE TITLE
Quantile fallback method for univariate distributions

### ISSUE THREAD

**Issue by BigCrunsh** [JuliaStats/Distributions.jl#284]
The inverse cdf is very useful, e.g., for hypothesis testing (see, e.g., https://github.com/JuliaStats/HypothesisTests.jl/pull/29). Unfortunately, it is not implemented for all distributions. Does it make sense to implement a generic fallback solution for ``quantile`` in analogy to https://github.com/JuliaStats/Distributions.jl/blob/master/src/univariate/noncentralhypergeometric.jl? More efficient solutions can then still be implemented for each specific distribution.

**Comment by simonbyrne** [comment]
I've added some methods for `quantile` and friends based on Newton iterations (see #325): these seem to converge fairly quickly.

**Comment by lindahua** [comment]
Since @simonbyrne has implemented the Newton's method for quantile (see `src/quantilealgs.jl`), can we close this issue?

**Comment by johnmyleswhite** [comment]
Seems reasonable to me.

**Comment by simonbyrne** [comment]
DOne
