### ISSUE TITLE
non-standardized T distribution

### ISSUE THREAD

**Issue by atteson** [JuliaStats/Distributions.jl#286]
It would be nice to have a non-standardized t distribution:

http://en.wikipedia.org/wiki/Student's_t-distribution#Non-standardized_Student.27s_t-distribution

It is a straightforward generalization of the t distribution.  I realize this is a "feature request" rather than an "issue".  Please let me know if there's some other way that I'm supposed to post this.

**Comment by chipkent** [comment]
I just submitted a pull request with this feature implemented.  [Pull-490](https://github.com/JuliaStats/Distributions.jl/pull/490)

**Comment by DominiqueMakowski** [comment]
Sorry to revive this thread, but I was wondering what happened with the shifted (and scaled?) T-distribution, as the current version doesn't seem to accept more than one parameter?
