### ISSUE TITLE
Multivariate Normal  with unknown variance conjugate

### ISSUE THREAD

**Issue by spencerlyon2** [JuliaStats/Distributions.jl#306]
Do we have a conjugate set up for Normal likilhood with Inverse-Wishart prior (known mean, unknown variance)? I don't think we do, but then when I saw `NormalInverseWishart` in `conjugates/mvnormal.jl` I wasn't so sure.

If we don't have it I'm happy to implement it.

**Comment by lindahua** [comment]
The ConjugatePriors package provides `NormalInverseWishart`.
