### ISSUE TITLE
Support for Rationals in discrete distributions?

### ISSUE THREAD

**Issue by ZacCranko** [JuliaStats/Distributions.jl#309]
Are there any plans for supporting `Rational` types for distributions, e.g. `Categorical([2//3,1//3])` ? Seems very natural for these sorts of distributions to take advantage of Julia's amazing rational numbers.

**Comment by andreasnoack** [comment]
I realized that this is also an issue for fixing the empirical distribution in https://github.com/JuliaStats/Distributions.jl/pull/661 since it is discrete but not integer valued.
