### ISSUE TITLE
Negative Binomial parameterization

### ISSUE THREAD

**Issue by willtownes** [JuliaStats/Distributions.jl#323]
The documentation does not specify the parameterization for negative binomial. Due to the ambiguity of this distribution, I suggest writing out the PMF and support set (whether or not zero is possible) explicitly in the documentation rather than just referring to wikipedia. In fact as of this posting the parameterization described on wikipedia appears to reverse the roles of p and (1-p) compared to the distribution in Julia.

**Comment by simonbyrne** [comment]
Yes, we do appear to use a different parametrisation (we use the [same as R](https://stat.ethz.ch/R-manual/R-patched/library/stats/html/NegBinomial.html)), but everything does appear to be well defined. I've changed the notation slightly to make the support set clearer (918b022e3c27eba53eabf09d0c66876e38ecb0f7)
