### ISSUE TITLE
quantile for InverseGaussian

### ISSUE THREAD

**Issue by lindahua** [JuliaStats/Distributions.jl#325]
This takes for ever to run (using current implementation):

```julia
quantile(InverseGaussian(2.0), 0.01)
```

It is stuck within the while loop and never converges.

**Comment by simonbyrne** [comment]
It appears that the first jump is to `Inf`, and then it gets stuck. Getting rid of the multiplicative step doesn't help.

[This paper](http://www.statsci.org/smyth/pubs/qinvgaussPreprint.pdf) makes the suggestion of starting at the mode and doing linear steps, which is provably convergent: it seems to work, and could be a useful fallback.
