### ISSUE TITLE
Vector{Float64} vs Vector{Int64} in parameters confusing

### ISSUE THREAD

**Issue by afniedermayer** [JuliaStats/Distributions.jl#331]
This is a more general issue than #330 and probably more difficult to fix, so I'm submitting it as a separate issue.

It is confusing that `MvNormal([0.0,0.0],1)` and `MvNormal([0.0,0.0],1.0)` both work (i.e. the scalar argument can be both Int64 and Float64), but `MvNormal([0,0],1.0)` fails (vector arguments cannot be Vector{Int64}). This behavior is different than e.g. `max([1.0,3.0],2.0)` and `max([1,3],2.0)`, which both work and give the same result.

The same issue arises with vector parameters of other multivariate distributions, e.g. MvTDist.

**Comment by andreasnoack** [comment]
No longer a problem
