### ISSUE TITLE
Misleading field name in Type Gamma

### ISSUE THREAD

**Issue by adamgld** [JuliaStats/Distributions.jl#340]
src/univariate/continuous/gamma.jl
The  scale parameter named as β, which is the standard name of rate parameter.
See eg.: http://en.wikipedia.org/wiki/Gamma_distribution
Solution is to change the name from β to θ.

**Comment by simonbyrne** [comment]
I see your point, as for some reason beta is always used for rate

It did used to be theta: 92a9570e359e61f144b57b2937d32e5784421f67

@lindahua Any particular reason for the change?

**Comment by lindahua** [comment]
In some other article (e.g. http://en.wikipedia.org/wiki/Exponential_distribution), β is used as the scale parameter. Probably we should have some place to maintain a naming convention that we should stick to over the entire package.

**Comment by lindahua** [comment]
Close this. Discussion about naming is moved to #395.
