### ISSUE TITLE
Inaccurate sampling from TruncatedNormal in tail regions

### ISSUE THREAD

**Issue by jdrugo** [JuliaStats/Distributions.jl#343]
The current quantile-based sampling method is inaccurate for TruncatedNormal when sampling from the tails of the Normal:
```Julia
rand(TruncatedNormal(0,1,35,Inf))
```
always returns ```Inf```.
```Julia
rand(TruncatedNormal(0,1,-Inf,-35))
```
always returns ```-Inf```. This problem can be fixed by re-enabling the Robert (1995) sampler that is currently commented out.

**Comment by lindahua** [comment]
I suppose this was fixed by that commit.

**Comment by jdrugo** [comment]
The TruncatedNormal distribution still features this bug. My pull request that fixes it has yet to be merged.
