### ISSUE TITLE
 Binomial, how to compute ?

### ISSUE THREAD

**Issue by paulanalyst** [JuliaStats/Distributions.jl#345]
I have :
ntrials =10
p =0.5
succprob=5
how to compute discret (or / and cumulated) value of Binomial distibution ? 
Must be 0,246094...
Paul

**Comment by johnmyleswhite** [comment]
There is documentation for this library: http://distributionsjl.readthedocs.org/en/latest/

**Comment by paulanalyst** [comment]
I now, I have, bu no place for 3 parameters
julia> Binomial(10,0.5)
Binomial(n=10, p=0.5)

julia> Binomial(10,0.5)(5)
ERROR: type: apply: expected Function, got Binomial


Binomial()      # Binomial distribution with n = 1 and p = 0.5
Binomial(n)     # Binomial distribution for n trials with success rate p = 0.5
Binomial(n, p)  # Binomial distribution for n trials with success rate p

params(d)       # Get the parameters, i.e. (n, p)
ntrials(d)      # Get the number of trials, i.e. n
succprob(d)     # Get the success rate, i.e. p
failprob(d)     # Get the failure rate, i.e. 1 - p
