### ISSUE TITLE
"Getting started" in documentation?

### ISSUE THREAD

**Issue by cgoldammer** [JuliaStats/Distributions.jl#348]
Many packages have a "getting started" page for their documentation, e.g. http://dataframesjl.readthedocs.org/en/latest/getting_started.html. I feel like this would be nice for this package too. I'd be excited to write (or draft) such a page and submit a pull request, but only if you think it would be useful.

Looking forward to your feedback!

**Comment by simonbyrne** [comment]
Certainly! It sounds like a great idea.

**Comment by cgoldammer** [comment]
Awesome, will put in a pull request soon.
