### ISSUE TITLE
Dimension mismatch error in Julia! 

### ISSUE THREAD

**Issue by KacemHariz** [JuliaStats/Distributions.jl#352]
Here is the code:

w=1;
γ=0.01;
f(x,y)= [y;-w^2*sin(x)-u*w^2*cos(x) -2γ*y];

for i=1:sizeof(Sx)
    x0=Sx[i+2];
    y0=Sy[i+2];
    for j=1:sizeU
        u=U[i];
        t,NX=ODE.ode45(f,[0,0.1],[x0,y0])
    end
end

and here is the error message:

mismatch in dimension 1
while loading In[69], in expression starting on line 5

 in cat at abstractarray.jl:631
 in hcat at abstractarray.jl:671
 in hvcat at abstractarray.jl:966
 in f at In[69]:3
 in oderkf at /home/juser/.julia/v0.3/ODE/src/ODE.jl:208
 in ode45_dp at /home/juser/.julia/v0.3/ODE/src/ODE.jl:303
 in anonymous at no file:10

Please if anyone knows how to fix it, please let me know, I'll be very grateful!

**Comment by simonbyrne** [comment]
@KacemHariz This doesn't appear to be related to the Distributions package

You might be better off posting this on [julia-users](https://groups.google.com/forum/?fromgroups=#!forum/julia-users), though you should probably a full code snippet (i.e. define `Sx`, `Sy` and `U`).
