### ISSUE TITLE
Tag new version

### ISSUE THREAD

**Issue by davidanthoff** [JuliaStats/Distributions.jl#353]
Any plans to tag a new version soon? There are some fixes that have been around for a while and that would be really useful to have in a tagged version (I'm e.g. interested in 9bce2b0b55512246482d2a5dc144462a89c68487).

**Comment by simonbyrne** [comment]
Good point: it looks like @kmsquire has taken care of this: https://github.com/JuliaLang/METADATA.jl/pull/2272.

**Comment by davidanthoff** [comment]
Thanks!
