### ISSUE TITLE
Line 6 of chisq.jl should be new(@compat(Float64(...

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaStats/Distributions.jl#355]
Right now it is
```
@compat new(Float64(...
```
which breaks in 0.3.  Changing the order of the `@compat` resolved the issue for me.  I'm assuming this might be elsewhere too.

**Comment by simonbyrne** [comment]
Hmm, I'm not seeing it: which version of 0.3 are you running?

**Comment by simonbyrne** [comment]
And which version of Compat.jl?

**Comment by andreasnoack** [comment]
I'm puzzled by this. I don't see it on my machine. What do you get from `Pkg.status()`?

**Comment by dlfivefifty** [comment]
Hmm, I can’t reproduce it in a small line.  I suspect what happened was that I did the following incorrect sequence of actions which confused me.  


	#Start Julia
	using Compat
 	Pkg.update()
	using Distributions
	rand(ChiSq…)		# error “can’t create type”
	# Edited chisq.jl
	# Restart Julia
	rand(ChiSq…)	  	#works
	# Posted git issue with change

**Comment by andreasnoack** [comment]
@dlfivefifty Does this work on you machine now? If so, can this issue be closed?

**Comment by dlfivefifty** [comment]
Yes I think it should be closed, sorry for wasting your time!
