### ISSUE TITLE
NormalWishart example not working in latest version (673cabd)

### ISSUE THREAD

**Issue by jaak-s** [JuliaStats/Distributions.jl#367]
The example for `NormalWishart` in test/compoundvariate.jl gives error (tested in julia v0.3.7)
```julia
using Distributions
mu0 = [2., 3.]
kappa0 = 3.
nu0 = 4.
T0 = eye(2)
T0[1,2] = T0[2,1] = .5
nw = NormalWishart(mu0, kappa0, T0, nu0);
# gives: ERROR: NormalWishart not defined
```
Workaround is to switch back to v0.6.3.

**Comment by lindahua** [comment]
This entire thing together with other stuff related to conjugate prior has been migrated out to [ConjugatePriors](https://github.com/JuliaStats/ConjugatePriors.jl).
