### ISSUE TITLE
insupport fallback method

### ISSUE THREAD

**Issue by brian-j-smith** [JuliaStats/Distributions.jl#372]
The [documentation](http://distributionsjl.readthedocs.org/en/latest/extends.html#create-a-univariate-distribution) indicates that ''a generic fallback as ``insupport(d, x) = minimum(d) <= x <= maximum(d)``'' is provided for user-created distributions.  However, I get an error if ``insupport`` is not explicitly defined for a new distribution (see example below).

Is the fallback still implemented?  If not, would you be willing to add it in a future version?   Thanks.

```julia
using Distributions

type NewUnivarDist <: ContinuousUnivariateDistribution
  mu::Float64
  sigma::Float64
end

minimum(d::NewUnivarDist) = -Inf
maximum(d::NewUnivarDist) = Inf

d = NewUnivarDist(1.0, 2.0)
minimum(d)         ## -Inf
maximum(d)         ## Inf
insupport(d, 1.0)  ## error: no matching method
```

**Comment by simonbyrne** [comment]
This makes sense: in fact, I would go further and make this the standard method, and get rid of the individual definitions in the `@distr_support` macro. This would also solve the problem of things like:
```
julia> insupport(Gamma(),NaN)
false

julia> insupport(Normal(),NaN)
true
```

**Comment by brian-j-smith** [comment]
Awesome.  Thanks for implementing all the generic support methods.  Really appreciate it.

**Comment by simonbyrne** [comment]
No worries, thanks for pointing it out. I've merged it now: let me know if there are further problems.
