### ISSUE TITLE
rand( MixtureModel(MvTDist ,...), N) doesn't work

### ISSUE THREAD

**Issue by eford** [JuliaStats/Distributions.jl#376]
> using Distributions
> mm = MixtureModel(MvTDist, [(3.0, ones(2), inv(diagm(randn(2).^2))) for i in 1:2], ones(2)/2.0)
> rand(mm,10)
> ERROR: `randn!` has no method matching randn!(::ContiguousView{Float64,1,Array{Float64,2}})
>  in _rand! at C:\cygwin\home\ebf11.julia\v0.3\Distributions\src\multivariate\mvtdist.jl:143
>  in _rand! at C:\cygwin\home\ebf11.julia\v0.3\Distributions\src\genericrand.jl:20
>  in rand at C:\cygwin\home\ebf11.julia\v0.3\Distributions\src\multivariates.jl:19

**Comment by tawheeler** [comment]
Still a problem in Julia 0.4

```
julia> using Distributions
julia> mix = MixtureModel([MvNormal(eye(2)), MvNormal(eye(2))]);
julia> a = rand!(mix, [0.0,0.0])
ERROR: MethodError: `_rand!` has no method matching _rand!(::Distributions.MixtureModel{Distributions.Multivariate,Distributions.Continuous,Distributions.MvNormal{Float64,PDMats.PDMat{Float64,Array{Float64,2}},Distributions.ZeroVector{Float64}}}, ::Array{Float64,1})
Closest candidates are:
  _rand!(::Distributions.InverseGamma{T<:Real}, ::AbstractArray{T,N})
  _rand!{T<:Real}(::Union{Distributions.DirichletCanon,Distributions.Dirichlet{T<:Real}}, ::AbstractArray{T<:Real,1})
  _rand!{T<:Real}(::Distributions.Multinomial, ::AbstractArray{T<:Real,1})
  ...
 in rand! at /home/tim/.julia/v0.4/Distributions/src/multivariates.jl:8
```

**Comment by matbesancon** [comment]
Fixed, should have been closed
