### ISSUE TITLE
Why is `Normal` defined as `Normal(μ, σ)` instead of `Normal(μ, σ^2)`

### ISSUE THREAD

**Issue by samuela** [JuliaStats/Distributions.jl#381]
Defining a normal distribution by its mean and variance is the standard mathematical notation: `N(μ, σ^2)` or `Normal(μ, σ^2)`. So, why is the calling interface `Normal(μ, σ)` in the package? This has really messed up a lot of my code.

**Comment by johnmyleswhite** [comment]
Here's the precedent in the languages we generally try to emulate:

* http://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.norm.html
* http://stat.ethz.ch/R-manual/R-patched/library/stats/html/Normal.html

**Comment by simonbyrne** [comment]
And
* https://reference.wolfram.com/language/ref/NormalDistribution.html
* http://uk.mathworks.com/help/stats/normal-distribution.html

It turns out that standard deviation is also the more useful quantity in most of the calculations, so it avoids unnecessarily taking a square root each time.
