### ISSUE TITLE
bvn.jl, tvpack.jl - overlap

### ISSUE THREAD

**Issue by smeme** [JuliaStats/Distributions.jl#385]
It seems there are several related genz's programs/files in which `bvn` is repeated. These are repeated in the following julia files as well. 

https://github.com/andferrari/BivarNormalProb.jl/blob/master/src/bvn.jl
https://github.com/JuliaStats/Distributions.jl/blob/master/src/tvpack.jl

It would be useful to add a recent version of 'truncated `mvn: mvnxpb.m` which is more accurate, significantly faster, and more general than `bvn` (http://link.springer.com/article/10.1007%2Fs11222-014-9468-y)

http://www.math.wsu.edu/faculty/genz/software/matlab/mvnxpb.m

Issue also raised here- 
https://github.com/andferrari/BivarNormalProb.jl/issues/1

**Comment by andreasnoack** [comment]
I don't know the reason why @andferrari has a duplicate implementation of sampling code for the bivariate normal distribution. It would be great if we could join our efforts in one implementation. We'd be very open to a contribution of a translation of the Genz' new code if permission has been granted from Genz to do so.

**Comment by smeme** [comment]
I believe each file on Genz' site is independent. Hence, all files have some duplicated functionality  e.g. `\Phi()` and `\phi()`. That being said, newer versions often include minor bug-fixes and/or are more efficient.  `BVN` has been updated several times.

**Comment by andferrari** [comment]
At the time, I didn't know about `tvpack.jl`. I'd be happy to help.

**Comment by lindahua** [comment]
At this point, `tvpack.jl` has been transferred to StatsFuns.
