### ISSUE TITLE
Must change @math_const in constants.jl

### ISSUE THREAD

**Issue by ranjanan** [JuliaStats/Distributions.jl#387]
Recently @math_const has changed to @ irrational in Base. Hence any package using Distributions.jl would get an error (for example, QuantEcon). I also filed an issue in Compat.jl

**Comment by johnmyleswhite** [comment]
A pull request would be really helpful if you know where things need to change.

**Comment by StefanKarpinski** [comment]
Sorry, I should have included a deprecated version of the macro too.

**Comment by spencerlyon2** [comment]
The only thing that needs to change in this package is in [src/constants.jl](https://github.com/JuliaStats/Distributions.jl/blob/master/src/constants.jl)

**Comment by ranjanan** [comment]
Yeah, you're right. I'll just change it up and generate a pull request.

**Comment by spencerlyon2** [comment]
I think a change to Compat (or including a deprecated macro in Base) should happen first so that Distributions can still be supported on 0.3 and 0.4.

**Comment by ranjanan** [comment]
I think it's supported on v0.3.10. @math_const still flies for the latest stable version I suppose. For now, I'm just reflecting changes in constants.jl in Distributions.jl

**Comment by simonster** [comment]
Fixed by #389
