### ISSUE TITLE
Logcdf evaluation at every number

### ISSUE THREAD

**Issue by mes9** [JuliaStats/Distributions.jl#404]
The ``` logcdf(d,x) ``` function can be evaluated at nearly every value of x, while ```log( cdf(d,x) ) ``` quickly goes to zero or ```-inf```. I tried to go through the source code to figure out how they got the ```logcdf``` function to work like that. I need to make some particular tweaks within the ```log``` function but need the flexability that it can be evaluated over a wide range of x.

I greatly appreciate any help/suggestions!

**Comment by johnmyleswhite** [comment]
This isn't really an issue, so it belongs on a mailing list, not a GitHub issue.

You can see an example at https://github.com/JuliaStats/Distributions.jl/blob/master/src/univariate/continuous/pareto.jl#L67
