### ISSUE TITLE
Still exporting distributions moved to ConjugatePriors.jl

### ISSUE THREAD

**Issue by kmsquire** [JuliaStats/Distributions.jl#407]
A number of distributions (and corresponding machinery) were moved out to ConjugatePriors.jl in  4d1b368557a5141.  The function calls were removed in that PR, but (most of?) the distributions themselves still seem to be listed in the Distributions.jl exports.

This happened a while back, but, just curious, why was it that those distributions were moved out?
1. Even if they're mostly (exclusively?) used in Bayesian statistics/ML, they're still distributions.
2. When they're used as conjugate distributions, the posterior distribution (which is arguably more important/interesting) generally takes the same form, so the package name isn't quite accurate.

I never saw any public discussion about it, other than noting that the move broke a number of things (although I suppose the discussion could have taken place offline?).

**Comment by lindahua** [comment]
I thought it was related to several reasons, one being trimming down the package to reduce the loading time (this is no longer necessary with pre-compilation though) and make this part to be more independent, so it can be easier to experiment with different ways of organizing Bayesian related codes.

Now, I think we can revisit this before taking further actions. Should we merge it back to Distributions or just leave it alone as a downstream package?

**Comment by johnmyleswhite** [comment]
I'd be in favor of moving more things back into Distributions now that precompilation is available. We could start by having it be included in an inner module `Distributions.ConjugatePriors` if people are worried about the amount we're exporting.

**Comment by andreasnoack** [comment]
The separation now seems complete
