### ISSUE TITLE
NegativeBinomial(0.5,0.5) gives InexactError()

### ISSUE THREAD

**Issue by augustinyiptong** [JuliaStats/Distributions.jl#408]
Hello,

I am trying to create a negative binomial distribution with a float for the r parameter. The comments at the top of the negativebinomial.jl file lead me to believe this should be possible?

I am using Julia 0.3.11 and Distributions 0.8.3

Thanks, Gus

**Comment by johnmyleswhite** [comment]
https://github.com/JuliaStats/Distributions.jl/blob/a4568d75baa797498983ded6a1e8f0442e326b7a/src/univariate/discrete/negativebinomial.jl#L8 makes it impossible to use a non-integer value of `r`. Perhaps the code would work with that restriction relaxed, but that's an empirical question someone needs to look into.

**Comment by andreasnoack** [comment]
Fixed by b140bf08e9d967bae06f60731981c30cda8252f8
