### ISSUE TITLE
Crash printing Truncated Distribution

### ISSUE THREAD

**Issue by protogeezer** [JuliaStats/Distributions.jl#410]
et-imac-retina:~ sjbespa$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-pre+7105 (2015-08-30 15:16 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 349a4e1* (0 days old master)
|__/                   |  x86_64-apple-darwin14.5.0

julia> using Distributions
INFO: Recompiling stale cache file /Users/sjbespa/.julia/lib/v0.4/Distributions.ji for module Distributions.
INFO: Recompiling stale cache file /Users/sjbespa/.julia/lib/v0.4/PDMats.ji for module PDMats.

julia> rng = Truncated(Normal(0,1),-2.75,2.75);

julia> rng
Truncated(Error showing value of type Distributions.Truncated{Distributions.Normal,Distributions.Continuous}:
ERROR: type DataType has no field names
 in show at /Users/sjbespa/.julia/v0.4/Distributions/src/truncate.jl:104
 in anonymous at show.jl:1269
 in with_output_limit at ./show.jl:1246
 in showlimited at show.jl:1268
 in writemime at replutil.jl:4
 in display at REPL.jl:115
 in display at REPL.jl:118
 in display at multimedia.jl:151
 in print_response at REPL.jl:135
 in print_response at REPL.jl:122
 in anonymous at REPL.jl:624
 in run_interface at ./LineEdit.jl:1610
 in run_frontend at ./REPL.jl:863
 in run_repl at ./REPL.jl:167
 in _start at ./client.jl:453

julia>

**Comment by johnmyleswhite** [comment]
This seems like a bug in Base. Is this happening on Julia master still?

**Comment by protogeezer** [comment]
It is still happening on 0.4.0-rc1.

**Comment by johnmyleswhite** [comment]
Found the source of this and opened #415 in response.
