### ISSUE TITLE
Categorical when length( p ) = 1_000_000

### ISSUE THREAD

**Issue by matthieugomez** [JuliaStats/Distributions.jl#413]
```julia
p = fill(1.0, 1_000_000)
scale!(p, 1/sum(p ))
Categorical(p )
ERROR: ArgumentError: Categorical: the condition isprobvec(p) is not satisfied.
```
The issue is that the sum of `p` never equals 1.0 at 1e-12.
Scaling twice does not improve the situation
```julia
p = fill(1.0, 1_000_000)
scale!(p, 1/sum(p ))
scale!(p, 1/sum(p ))
Categorical(p )
```

Is there a way to solve this issue?

**Comment by lindahua** [comment]
This is due to the way that `sum(p)` is computed in `isprobvec`, which is not accurate enough. I am fixing it.

**Comment by lindahua** [comment]
Fixed in latest master.

**Comment by matthieugomez** [comment]
Thanks!
