### ISSUE TITLE
MvNormal only using 1 core

### ISSUE THREAD

**Issue by michaellindon** [JuliaStats/Distributions.jl#421]
When I generate a random multivariate normal by myself, by taking cholesky of covariance matrix and multiplying a vector of standard normals by a the cholesky, I see my cpu usage ramp up to 800%. For the same problem when using MvNorm I only get 100%.

**Comment by johnmyleswhite** [comment]
Pull request?

**Comment by jiahao** [comment]
It also sounds like multithreading in your BLAS library is kicking in, which is normal if you don't turn it off explicitly.

**Comment by andreasnoack** [comment]
As @jiahao mentioned, this is some difference in how BLAS is called in the two methods. Please provide the exact code to generate this and also the output of `versioninfo()`. A cannot reproduce your result on my MacBook with OpenBLAS.

**Comment by andreasnoack** [comment]
I'm closing because of no response from @michaellindon. We can reopen if we get enough infomation to reproduce.
