### ISSUE TITLE
qq.jl has deprecation warnings, isn't tested

### ISSUE THREAD

**Issue by IainNZ** [JuliaStats/Distributions.jl#424]
I noticed dep warnings coming from Distributions during Gadfly tests, turns out it was coming from `src/qq.jl`. Apparently this code is untested, so it wasn't detected.

**Comment by simonster** [comment]
If this is gonna stay we should also document it

**Comment by johnmyleswhite** [comment]
This method dates from the wild west days when I needed it for plotting. Feel free to delete if no one wants us to maintain it.

**Comment by matbesancon** [comment]
There are now some tests for qqbuild, which pass without warning
