### ISSUE TITLE
Support for DualNumbers

### ISSUE THREAD

**Issue by bdeonovic** [JuliaStats/Distributions.jl#432]
Would it be at all possible to make Distributions work with DualNumbers (or any of the other packages from http://www.juliadiff.org/) so that gradient and hessian can be calculated for logpdfs?

**Comment by johnmyleswhite** [comment]
This is currently being experimented with. Check out the recent pull requests.

**Comment by bdeonovic** [comment]
I see, sounds like it will be awhile though? What are some of the major hurtles?
