### ISSUE TITLE
use non-global rng

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaStats/Distributions.jl#436]
I would like to have the opportunity to do something like this

``` julia
d= Binomial(10,0.1)
rng = MersenneTwister(17)
rand(rng, d)
```

Is there any way to do something similar?

**Comment by simonbyrne** [comment]
Not yet: some distributions such as Binomial utilise the Rmath RNGs, which unfortunately are tied to global state. I'm hoping to fix this in the near future.

**Comment by zsunberg** [comment]
This would be extremely useful to us - we're developing a [framework for decision making under uncertainty](https://github.com/JuliaPOMDP/POMDPs.jl). We use a lot of distributions, but it is really convenient to be able to specify the rng, so using Distributions.jl doesn't work well for us yet. I hope that you can implement this  soon - we would really like to enable more ease-of use and compatibility of code by using this!

**Comment by richardreeve** [comment]
@matbesancon I think this can be closed now.
