### ISSUE TITLE
quantile(Normal(), 0.95) hiccups with directed rounding

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaStats/Distributions.jl#438]
ND=Normal()
set_rounding(Float64,RoundDown)
q95down = quantile(ND, 0.95)
set_rounding(Float64,RoundNearest)
q95near = quantile(ND, 0.95)
set_rounding(Float64,RoundUp)
q95up = quantile(ND, 0.95)
set_rounding( Float64,RoundNearest)

q95near <= q95up
true
q95down <= q95near
false

#          down                                nearest                                up
# 1.644853626951472 > 1.6448536269514715 < 1.6448536269514733

**Comment by JeffreySarnoff** [comment]
oops -- did not intend the big font

**Comment by simonbyrne** [comment]
Rounding modes are only correct for basic arithmetic operations (`+`,`-`,`*`,`/` and `sqrt`): changing the rounding mode can have strange effects on other functions (see [this warning](http://docs.julialang.org/en/release-0.4/manual/integers-and-floating-point-numbers/#rounding-modes)). Given how difficult it is to get correct rounding for other functions (see [CRlibm](http://lipforge.ens-lyon.fr/www/crlibm/)), this isn't something we can realistically aim for.

You could try computing the answers using the `erfc` function with `BigFloat`s?
