### ISSUE TITLE
 Normal: the condition σ > zero(σ) is not satisfied

### ISSUE THREAD

**Issue by michaellindon** [JuliaStats/Distributions.jl#445]
I have the following unexpected error
```jl
ERROR: ArgumentError: Normal: the condition σ > zero(σ) is not satisfied.
 [inlined code] from /home/grad/msl33/.julia/v0.4/Distributions/src/utils.jl:6
 in call at /home/grad/msl33/.julia/v0.4/Distributions/src/univariate/continuous/normal.jl:5
 in sslogdensity at none:31
 [inlined code] from none:33
 in anonymous at no file:32
```
in the following line of code:

```jl
for i=1:n
    if(sqrt(σ²+β*AMAQ[t[i-1]][1,1]*β)<=0)
        println(β*AMAQ[t[i-1]][1,1]*β)
    end
    logdensity=logdensity+logpdf(Normal(μ+β*(A[t[i-1]][1,:]*m[t[i-1]])[1],sqrt(σ²+β*AMAQ[t[i-1]][1,1]*β)),y[t[i]])
end
```

The strange thing is that nothing is printed to the screen. I would have expected that if `sqrt(σ²+β*AMAQ[t[i-1]][1,1]*β)` is zero or negative, as the error suggests, then something would get printed out but in fact it is never triggered.

**Comment by johnmyleswhite** [comment]
Any chance you could provide a simpler reproducible example? What's the value and type of sigma when you trigger this error?

**Comment by michaellindon** [comment]
It turned out that the value was a NaN and NaN<0 is false
