### ISSUE TITLE
Allow Categorical to have different bounds then 1, ncategories?

### ISSUE THREAD

**Issue by jw3126** [JuliaStats/Distributions.jl#449]
How about adding an additional field to the Categorical type with default value 1. What I have in mind is a field Categorical.min such that
- minimum(c) = c.min 
- maximum(c) = c.min + ncategories(c) - 1
- samples are drawn from [minimum(c): maximum(c)] and not [1:ncategories(c)]

There would probably be several benefits, let me just describe the one that motivates me.
What I want to do is create new distributions out of old ones. For example
- The distribution of the minimum, maximum of n draws from the same or several Distributions
- The distribution of the sum/difference of draws from two or more distributions
- etc.

In some cases (e.g. add two binomial same p) one can do so analytically, but more often then not I end up with a distribution which has no better description then a value range and a probability vector.
But this distribution is may not be Categorical because it can assume 0 or even negative values! 
I feel it would be awkward to introduce a new type for this kind of thing and would love to use Categorical instead.

**Comment by johnmyleswhite** [comment]
This is pretty much exactly the use case for location-scale families, which people are already working on.

**Comment by jw3126** [comment]
Ah thanks I see. For what I want to do, I would prefer a discrete version of UnivariateLocationScaleFamily. E.g. if the math preserves discreteness (sum, max...) the code should also. Also iterating constructions is much cleaner if the type does not forget discreteness along the way. 
Would it be reasonable to also have a discrete UnivariateLocationScaleFamily or does such a thing even already exist somewhere?

**Comment by johnmyleswhite** [comment]
Yes, it's totally reasonable. I think one of the essential things we have to get right is making location and scale families respect discreteness when appropriate.

**Comment by jw3126** [comment]
So we should actually have two types

DiscreteUnivariateLocationScaleFamily {T <: UnivariateDistribution} <: DiscreteUnivariateDistribution
ContinousUnivariateLocationScaleFamily{T <: UnivariateDistribution} <: ContinuousUnivariateDistribution

(maybe the first type is parametrized by discrete T only.) And respect discreteness when it can be proven by type reasoning? e.g.

Binomial + 1  discrete
Binomial + 1.0 continuous
Normal * 0 continous

**Comment by adityam** [comment]
Another option is to pass two parameters to `Categorical`: `probabilities` and `values` (and have a constructor that takes only one parameter: `probabilities` and initializes `values` to `[1:length(probabilities)]`. For example:

~~~
d = Categorical([0.2, 0.3, 0.5], [-5,0,5])
~~~
will generate `-5` with probability `0.2`, `0` with probability `0.3`, and `5` with probability `0.5`.

**Comment by cstjean** [comment]
> `d = Categorical([0.2, 0.3, 0.5], [-5,0,5])`

+1; I've got an application that would work great with `Categorial([0.2, 0.3, 0.5], ["apple", "orange", "kiwi"])`. Would such a PR be considered? Obviously, the mean, variance, etc. are not computable on such non-numerical distributions. This would solve #147 if I understand correctly.

**Comment by andreasnoack** [comment]
Related to https://github.com/JuliaStats/Distributions.jl/pull/634

**Comment by matbesancon** [comment]
I would consider this closed with #634 then
