### ISSUE TITLE
LogNormal inconsistent when outside support

### ISSUE THREAD

**Issue by KrisDM** [JuliaStats/Distributions.jl#456]
Behaviour for LogNormal pdf and logpdf for values outside its support is inconsistent (see below). 

This is partly because the @distr_support macro gives a closed rather than open interval (which is required here), and partly because the pdf function does not test the support. I will submit a PR with a fix and tests.

Results should be 0.0 for pdf, and -Inf for logpdf, when testing values outside the support. 

Not NaN, and not the DomainError generated by a call to log(-1.0), as below:

```
julia> d = LogNormal(0.0,1.0)
Distributions.LogNormal(μ=0.0, σ=1.0)

julia> pdf(d,0.0)
NaN

julia> pdf(d,-1.0)
ERROR: DomainError:
 in pdf at C:\Users\kris\.julia\v0.4\Distributions\src\univariate\continuous\lognormal.jl:56

julia> logpdf(d,0.0)
NaN

julia> logpdf(d,-1.0)
-Inf
```

**Comment by KrisDM** [comment]
When I started fixing this, the problem was much bigger than I thought: several distributions had similar inconsistencies. PR #457 fixes all of them.

**Comment by matbesancon** [comment]
@JuliaRegistrator register()
