### ISSUE TITLE
negative non-centrality parameter for NoncentralT

### ISSUE THREAD

**Issue by Ph0non** [JuliaStats/Distributions.jl#462]
If I'm not missing something, it's not neccessary for the noncentral-T-distribution to have only positiv noncentrality parameter.

`@check_args(NoncentralT, λ >= zero(λ))`

**Comment by andreasnoack** [comment]
No. I agree with you here. This is probably an error. Have you checked R?

**Comment by Ph0non** [comment]
In R it's well defined. Also Wikipedia states, that the noncentrality parameter may be negative. I can't see any consequences for the rest of NoncentralT for a negative parameter.

It should only be checked, if λ is real.

**Comment by andreasnoack** [comment]
@Ph0non Would you mind opening a PR with a fix for this?
