### ISSUE TITLE
Remove 0.3 support

### ISSUE THREAD

**Issue by simonbyrne** [JuliaStats/Distributions.jl#465]
I'm in the process of moving docs to docstrings. As this is much easier to do in 0.4, would there be any opposition to removing 0.3 support?

**Comment by kmsquire** [comment]
+1

**Comment by simonbyrne** [comment]
I've just tagged a new version (containing the updates to PDMats.jl):
https://github.com/JuliaLang/METADATA.jl/pull/4575
