### ISSUE TITLE
Hacking a version without GPL dependencies 

### ISSUE THREAD

**Issue by JockLawrie** [JuliaStats/Distributions.jl#471]
Hi all,

I experimenting building Julia with USE_GPL_LIBS set to 0.
Of all the packages I use regularly, only PDMats is affected by this, and anything that depends on it, including Distributions.jl. The result is that Distributions.jl won't load.

I only need univariate distributions, so to enable Distributions.jl to load I've simply excluded some lines from Distributions.jl (the file not the package). Specifically, I've wrapped each of the following lines with `if Base.USE_GPL_LIBS  end` (hacky but it works):
```
using PDMats
import PDMats: dim, PDMat, invquad
include("multivariates.jl")
include("matrixvariates.jl")
```

Does this mean that the resulting version of Distributions.jl is not GPL?

(My language is a little imprecise - I understand that the Julia code is MIT but that the package has GPL dependencies. Please correct me where possible)

Cheers,
Jock

**Comment by simonbyrne** [comment]
The code in Distributions.jl is all MIT licensed, however it depends on StatsFuns.jl, which in turn uses routines from the Rmath library, which is GPL (for historical reasons, Rmath is bundled with Julia, despite the fact that it isn't actually used there, and this will be disabled with `USE_GPL_LIBS=0`.

**Comment by JockLawrie** [comment]
This license stuff confuses me. Do you mean the following:
- Setting USE_GPL_LIBS to 0 will exclude Rmath from the Julia build, which therefore the will be non-GPL.
- But Rmath remains a dependency of StatsFuns.jl and therefore StatsFuns.jl is still effectively GPL.
- Therefore using StatsFuns.jl or anything that depends on it makes the entire Julia environment GPL.
- Conversely, not using StatsFuns.jl or anything that depends on it leaves the Julia environment non-GPL.

**Comment by ViralBShah** [comment]
Perhaps this is more appropriate for the mailing list. Your understanding is correct. Whether using StatsFuns.jl that uses RMath makes everything GPL or not depends on your interpretation of the GPL. We will be shortly removing the RMath build from Base altogether and JuliaStats will have its own way to get RMath.

**Comment by simonbyrne** [comment]
At the moment, if you build Julia with `USE_GPL_LIBS=0`, then the parts of Distributions that depend on Rmath (e.g. cdf of Gamma) simply won't work.
