### ISSUE TITLE
Beta-Binomial Distribution

### ISSUE THREAD

**Issue by kkmann** [JuliaStats/Distributions.jl#472]
Hey,

I was just wondering if there are any plans to include the beta binomial distribution in the package. This would come in handy for Bayesian models involving the binomial distribution.

Best Kevin

**Comment by simonbyrne** [comment]
It already is there:
http://distributionsjl.readthedocs.org/en/latest/univariate-discrete.html#BetaBinomial

**Comment by kkmann** [comment]
jeez thanks, so sorry I was looking for it under continuous distributions ;)
