### ISSUE TITLE
invcdf function does not exist

### ISSUE THREAD

**Issue by aoboturov** [JuliaStats/Distributions.jl#489]
Seems like there is no `invcdf` function provided in the package [docs](http://distributionsjl.readthedocs.org/en/latest/univariate.html).

Although it is provided within the [StatsFuns](https://github.com/JuliaStats/StatsFuns.jl) package for all of the classes of random variables. So something like this:

    using Distributions
    α = .05
    invcdf(beta(a, b), α/2)

is not possible.

**Comment by johnmyleswhite** [comment]
FYI: this question belongs on the julia-users mailing list, not the issue tracker.

**Comment by simonbyrne** [comment]
You want the quantile function

**Comment by dpsanders** [comment]
Maybe an alias `invcdf` should be added? Arrived here because I was looking for it.
