### ISSUE TITLE
Truncated normal sampler returns Inf

### ISSUE THREAD

**Issue by mewo2** [JuliaStats/Distributions.jl#493]
A while back, I wrote some specialized code for a truncated normal sampler. This code was later commented out, as there was no performance improvement over the standard rejection/quantile samplers. However, these samplers give incorrect results when used on highly truncated problems.

For example:
```
julia> rand(TruncatedNormal(0.0, 1.0, 10.0, Inf))
Inf
```

versus (with the original code)

```
julia> randnt(10.0, Inf)
10.235267044368612
```

**Comment by jdrugo** [comment]
I have filed that as issue #343 a while back. It was closed without being fixed.
