### ISSUE TITLE
Inconsistent  parameter names in documentation

### ISSUE THREAD

**Issue by RossBoylan** [JuliaStats/Distributions.jl#495]
## http://distributionsjl.readthedocs.io/en/latest/univariate-continuous.html says

 Gamma(α, θ)

```
The Gamma distribution with shape parameter α and scale θ has probability density function
f(x;α,β)=xα−1e−x/βΓ(α)βα,x>0
```

Gamma()          # Gamma distribution with unit shape and unit scale, i.e. Gamma(1.0, 1.0)
Gamma(a)         # Gamma distribution with shape a and unit scale, i.e. Gamma(a, 1.0)
Gamma(a, b)      # Gamma distribution with shape a and scale b

---

The headline and initial text refer to alpha and theta; the formula immediately after the text uses alpha and beta, and then the code-like lines that follow use a and b.

Greater consistency would be a virtue.  At least with respect to the initial description using Greek letters and the text examples not using them this seems to be a general problem.  Perhaps it's a holdover from before using non-ASCII in code was easy?

I would like to thank you for making the documentation, which is very helpful compared to that of StatsFuns.  The gamma distribution in particular has several common parameterizations, and so it is difficult to be sure what  one is getting without such documentation.

**Comment by nalimilan** [comment]
Thanks for the report. Would you make a pull request to fix this? (Use the letters retained by the actual functions in the code.)

**Comment by RossBoylan** [comment]
Are you talking about fixing the text before the code snippets, or the code snippets too?  In the latter case, there are other distributions affected.

**Comment by nalimilan** [comment]
Both. It's better to have everything be consistent. In particular, the code snippets should reflect the actual signatures of the real code.

**Comment by matbesancon** [comment]
Believe this was fixed
