### ISSUE TITLE
Possible Performance Regression Between .3 and .4

### ISSUE THREAD

**Issue by itsdfish** [JuliaStats/Distributions.jl#496]
A while back I documented a possible performance regression in Julia Users. No one responded. So I figured I would follow up with a  post here. It appears that rand() is faster in .4 compared to .3, but many distribution functions are much slower. Here is the link with my examples:

https://groups.google.com/forum/#!searchin/julia-users/distributions$20slower/julia-users/5oTO76hCbWA/vjWB9fdlCQAJ

**Comment by ViralBShah** [comment]
Pasting the numbers here:

````

#Version .4

@time rand(10^8);

  0.380916 seconds (9 allocations: 762.940 MB, 20.19% gc time)


@time rand(Normal(0,1),10^8);

  1.393181 seconds (8 allocations: 762.940 MB, 4.37% gc time)





@time rand(Logistic(0,1),10^8);


  3.473583 seconds (8 allocations: 762.940 MB, 1.81% gc time)





#Version .3



@time rand(10^8);


elapsed time: 0.750139665 seconds (800000168 bytes allocated)



@time rand(Normal(0,1),10^8);


elapsed time: 1.145922441 seconds (800000168 bytes allocated)



@time rand(Logistic(0,1),10^8);


elapsed time: 2.867426166 seconds (800000168 bytes allocated)

````

**Comment by andreasnoack** [comment]
Just compared 0.3 to master and there is still a slowdown. However, the versions of `Distributions` are also quite a bit different because we don't support 0.3 anymore.

**Comment by matbesancon** [comment]
don't think this is relevant to measure anymore
