### ISSUE TITLE
Fix Signature of MvNormal to allow integer arguments

### ISSUE THREAD

**Issue by jsams** [JuliaStats/Distributions.jl#498]
I'm not sure how many functions this effects, but I've come across it at least in MvNormal.

Anyway, if you give MvNormal an Array of some integer type, it gives a Method convert error:

```
MvNormal([1; 2], [1 0.5; 0.5 3])
ERROR: MethodError: `convert` has no method matching convert(::Type{Distributions.MvNormal{Cov<:PDMats.AbstractPDMat{T<:Real},Mean<:Union{Array{Float64,1},Distributions.ZeroVector{
Float64}}}}, ::Array{Int64,1}, ::Array{Float64,2})
This may have arisen from a call to the constructor Distributions.MvNormal{Cov<:PDMats.AbstractPDMat{T<:Real},Mean<:Union{Array{Float64,1},Distributions.ZeroVector{Float64}}}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  Distributions.MvNormal(::Array{Float64,1}, ::Array{Float64,2})
  call{T}(::Type{T}, ::Any)
  convert{T}(::Type{T}, ::T)
  ...
 in call at essentials.jl:57
```

But converting those to floats works fine:

```
julia> MvNormal([1.; 2.], [1 0.5; 0.5 3])
FullNormal(
dim: 2
μ: [1.0,2.0]
Σ: 2x2 Array{Float64,2}:
 1.0  0.5
 0.5  3.0
)
```

I'm new to Julia, but I suspect that the types accepted should be something like T <: Real?

**Comment by nalimilan** [comment]
Yes, I think that's the goal, but it might require a bit more work than just changing the signature (since e.g. integer arrays cannot store the result of a division in general). It would be great if you could give it a try with some tests that it works.

**Comment by jmxpearson** [comment]
@jsams Are you sure you're using the latest version? [This constructor](https://github.com/JuliaStats/Distributions.jl/blob/master/src/multivariate/mvnormal.jl#L86) seems like it should handle your use case.

**Comment by sivapvarma** [comment]
@jsams On Distributions v0.9.0  `MvNormal([1; 2], [1 0.5; 0.5 3])` works as expected without any errors.

I think this issue can be closed now.
