### ISSUE TITLE
What is everyone's opinion on parameter types for distributions?

### ISSUE THREAD

**Issue by esproff** [JuliaStats/Distributions.jl#510]
I've noticed significant discrepancies in how the constructors for various distributions deal with parameters of type `T <: Real`.

Speaking specifically for those distributions with parameters that are allowed to be floating point, some require that the parameter be inputted as `Float64`, some allow it to be entered as any `Real` and then convert/promote it to `Float64`, and still others are parametric and allow the field to be any concrete subtype of `Real`.

Clearly the first way is sub-optimal, since there's no reason to disallow integer or lower precision arguments when in theory the parameter can be any float, and it seems like between approaches 2 and 3 that approach 3 is probably the best, since it uses less memory when the user has decided they don't need all that extra precision.

So what does everyone think?  I could go through all the distributions and make it so they're all parametric where applicable if that's acceptable to everyone, especially since maintaining some modicum of uniformity in the code is probably desirable in order to avoid the creeping in of anti-patterns.

**Comment by jmxpearson** [comment]
This is work in progress. The plan is to make all distributions parametric. For some cases, integers won't work (e.g., even if both constructor inputs are integer, one of the parameters calculated by the inner constructor will end up Float).

Please see #475 #478 #501 #503 and references therein.

Expect a massive PR for almost all the univariate distributions this week.

**Comment by esproff** [comment]
Ok great!  I just wanted to make sure people were aware of it, sounds good.  I'll close this issue.
