### ISSUE TITLE
ERROR: UndefVarError: Rmath not defined

### ISSUE THREAD

**Issue by reworkhow** [JuliaStats/Distributions.jl#513]
Got this error with `rand(Chisq(2))` after `Pkg.update()` today.

I guess this is because StatsFun.jl committed "Use the Rmath package since libRmath is gone in 0.5 (#10)" one day ago.

**Comment by ararslan** [comment]
Yes, that change broke all existing versions of Distributions. Once https://github.com/JuliaStats/Distributions.jl/pull/512 is merged I'll tag a new release which should fix this. I'm hoping to get all of that done ASAP today. Sorry for the inconvenience!

**Comment by tpoisot** [comment]
The temporary solution is `Pkg.add("StatsFuns", v"0.2.3", v"0.3.0")`

**Comment by tpoisot** [comment]
Didn't saw it got downgraded.

**Comment by ararslan** [comment]
Yes, StatsFuns v0.3.0 has been temporarily set to Julia 0.5 only.

**Comment by bdeonovic** [comment]
I'm still getting 

```julia
ERROR: LoadError: ArgumentError: Rmath not found in path
```

**Comment by ararslan** [comment]
What version of Julia are you on, 0.4? Distributions will have a new tag soon, and once that's available then hopefully this will all be fixed after another `Pkg.update()`.

**Comment by bdeonovic** [comment]
Thanks for the comment, I just had to add Rmath manually, not sure why the Pkg updator was forcing the add.

**Comment by ararslan** [comment]
Probably because you have StatsFuns 0.2.2, and Rmath is only required by StatsFuns 0.3.0. That'd be my guess, anyway.

**Comment by bdeonovic** [comment]
Well clearly something needed to require it.
