### ISSUE TITLE
Accidentally lost functionality with parametric types?

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaStats/Distributions.jl#516]
This may be an insoluble design problem, but I believe we have lost some functionality by introducing parametric distributions. In the past, the following code worked because of automatic conversion to `Float64`:

```jl
using Distributions

quantile(Normal(0, 1), 1)
```

But now it generates a `MethodError` because we don't have all the required fallbacks in place:

```jl
julia> using Distributions

julia> quantile(Normal(0, 1), 1)
ERROR: MethodError: `quantile` has no method matching quantile(::Distributions.Normal{Int64}, ::Int64)
```

**Comment by andreasnoack** [comment]
My fault https://github.com/JuliaStats/StatsFuns.jl/commit/758b2d0a3b5eea64c1dd13d92a7f388249941286. Should be fixed in https://github.com/JuliaStats/StatsFuns.jl/pull/14

**Comment by johnmyleswhite** [comment]
Thanks for fixing this!
