### ISSUE TITLE
How to ensure usability of ForwardDiff with custom distributions

### ISSUE THREAD

**Issue by bdeonovic** [JuliaStats/Distributions.jl#527]
Piggybacking off of the previous questions: https://github.com/JuliaStats/Distributions.jl/issues/525, is there anything specific that must be specified for custom distributions so that ForwardDiff will be able to computer derivatives etc with them?

**Comment by jmxpearson** [comment]
Fields in the distribution that are continuous parameters should be parametric with the type parameter a subtype of Real. For instance
```julia
immutable NewDist{T<:Real}
  a::T
  b::T
end
```
Note that it's nice if `T`, the parameter type, is the *first* type parameter (in case you have more than one). This is just so it's easier to restrict method definitions
```julia
foo{T<:Real}(d::NewDist{T})
```
when you need access to `T` inside the method body. You would also want to specify
```julia
@inline partype{T<:Real}(d::NewDist{T}) = T
```

There are some other functions you might want to provide like `convert` methods between distributions with different partypes. And it's a bit of a pain to make sure that your constructors wind up with a single `T` for both `a` and `b` (you don't strictly need all the fields to be the same type for ForwardDiff to work, but that's the convention we decided on). All the univariate and multivariate distributions now follow these conventions, so there should be plenty of examples.

Oh, and if you want to see how it works in practice, there are some tests using ForwardDiff [here](https://github.com/jmxpearson/distribution_diff_tests).

**Comment by andreasnoack** [comment]
@bdeonovic Can this issue be closed? Any specific things we can do?
