### ISSUE TITLE
pdf and rand do not work on Beta with Dual type parameters

### ISSUE THREAD

**Issue by xukai92** [JuliaStats/Distributions.jl#541]
For example the following code fails:

```
using Distributions
using ForwardDiff: Dual
pdf(Beta(Dual(2.), Dual(2.)), 1)
```

Error:

```
ERROR: MethodError: `convert` has no method matching convert(::Type{Float64}, ::ForwardDiff.Dual{0,Float64})
This may have arisen from a call to the constructor Float64(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T<:AbstractFloat}(::Type{T<:AbstractFloat}, ::Real, ::RoundingMode{T})
  call{T}(::Type{T}, ::Any)
  convert(::Type{Float64}, ::Int8)
  ...
 in pdf at /Users/kai/.julia/v0.4/Distributions/src/univariates.jl:320
```

**Comment by jmxpearson** [comment]
This is a known failure. `Beta` is defined using `_delegate_statsfuns`, which defines `pdf`, `cdf`, etc. in terms of the functions from StatsFuns.jl. Unfortunately, StatsFuns [imports these from Rmath](https://github.com/JuliaStats/StatsFuns.jl/blob/master/src/distrs/beta.jl). As a result, they're still only designed for Float64.

It would be great to fix this, but we need StatsFuns to be upgraded. My understanding is that people are working on removing RMath dependency (#294), but that's not finished.

**Comment by devmotion** [comment]
This is fixed in recent versions of Distributions and StatsFuns:
```julia
julia> pdf(Beta(ForwardDiff.Dual(2.), ForwardDiff.Dual(2.)), 1)
Dual{Nothing}(0.0)

julia> pdf(Beta(ForwardDiff.Dual(2.), ForwardDiff.Dual(2.)), 0.5)
Dual{Nothing}(1.5)
```

**Comment by oschulz** [comment]
Thanks for this, I ran into that multiple times ... would it be possible to make `cdf` and `quantile` of `Beta` compatible with `Dual` as well, with what we have? Would be very helpful for variate transformation chains.

**Comment by devmotion** [comment]
Currently, we use Rmath for cdf and quantile of basically anything that is handled via StatsFuns. There are plans to change this (https://github.com/JuliaStats/StatsFuns.jl/pull/113) and eg for the cdf of the beta distributions we can use `SpecialFunctions.beta_inc`. However, `SpecialFunctions.beta_inc` only supports arguments of type `T` for which `float(T)` is `Float16`, `Float32` or `Float64`, so it would still not be possible to pass a `ForwardDiff.Dual`. I assume one has to add a rule to DiffRules to add support for `Dual`.

**Comment by devmotion** [comment]
Related: https://github.com/JuliaMath/SpecialFunctions.jl/pull/337

**Comment by oschulz** [comment]
Thanks!

**Comment by oschulz** [comment]
I wonder if we could just allow dual numbers in the beta_inc... functions, at least `Dual{Float64}` (is there any precision-specific code in there?).

**Comment by devmotion** [comment]
The implementation is optimized for `Float64` (`Float32`, `Float16`, and other argument types are only supported by converting them to `Float64`): https://github.com/JuliaMath/SpecialFunctions.jl/blob/a1df96daaeae3ec663593a7c2d76f4245725ac5e/src/beta_inc.jl#L727-L879

**Comment by oschulz** [comment]
Ah - but shouldn't `Dual{Float64}` work too, then?

**Comment by oschulz** [comment]
Or does the implementation do some low-level bit magic or so?
