### ISSUE TITLE
Multinomial distribution throws error on n=0

### ISSUE THREAD

**Issue by ajdunlap** [JuliaStats/Distributions.jl#543]
Why does the multinomial distribution require n > 0? It seems like it should be fine to take n = 0, in which case it would always just return the all-zeroes vector?

**Comment by brethvoice** [comment]
Please specify, is n the number of outcomes (n=2 for binomial)? If so, then n>0 makes sense, right?

**Comment by ajdunlap** [comment]
Sorry, I meant n to mean the number of trials. E.g.:

```
julia> rand(Multinomial(200000,[1/2,1/4,1/4]))
3-element Array{Int64,1}:
 99983
 50087
 49930
julia> rand(Multinomial(1,[1/2,1/4,1/4]))
3-element Array{Int64,1}:
 1
 0
 0
```

My proposal is that `
julia> rand(Multinomial(0,[1/2,1/4,1/4]))` return the all-zeroes array deterministically rather than throwing an error.

**Comment by simonbyrne** [comment]
That seems reasonable. Would you mind opening a PR?
