### ISSUE TITLE
Probably not a Distributions problem, but....

### ISSUE THREAD

**Issue by sbromberger** [JuliaStats/Distributions.jl#546]
```
ERROR: Cannot clone Distributions from https://github.com/JuliaStats/Distributions.jl.git. SSL error: ffffffff - UNKNOWN ERROR CODE (0001)
```

from https://travis-ci.org/JuliaGraphs/GraphPlot.jl/jobs/168653499#L183

Grasping at straws here. Any ideas?

**Comment by ararslan** [comment]
Yeah, not related to Distributions. I think it's an SSL certificate issue on 0.6 that's currently being worked on in Base.

**Comment by sbromberger** [comment]
Thanks for the quick response. Sorry to have bugged you.

**Comment by ararslan** [comment]
No problem! Hopefully it'll get resolved soon.
