### ISSUE TITLE
ERROR: InexactError() for BetaBinomial n > 66

### ISSUE THREAD

**Issue by cjprybol** [JuliaStats/Distributions.jl#547]
```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.1-pre+2 (2016-09-20 03:34 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit f0d40ec* (29 days old release-0.5)
|__/                   |  x86_64-apple-darwin16.1.0

julia> using Distributions

julia> pdf(BetaBinomial(66, 2, 2));

julia> pdf(BetaBinomial(67, 2, 2));
ERROR: InexactError()
 in binomial(::Int64, ::Int64) at ./intfuncs.jl:410
 in copy!(::Array{Float64,1}, ::Base.Generator{UnitRange{Int64},Distributions.##15#16{Int64}}) at ./abstractarray.jl:477
 in pdf(::Distributions.BetaBinomial{Float64}) at /Users/Cameron/.julia/v0.5/Distributions/src/univariate/discrete/betabinomial.jl:94
```

Is there a limit to how large n can be when generating a beta-binomial distribution? I've only come across `ERROR: InexactError()` before when casting Floats to Ints.

following the error to line 410 in intfuncs.jl shows `x >>= 4` as the offending line (if I'm interpreting the traceback correctly)
```
function hex(x::Unsigned, pad::Int, neg::Bool)
    i = neg + max(pad,(sizeof(x)<<1)-(leading_zeros(x)>>2))
    a = Array{UInt8}(i)
    while i > neg
        d = x & 0xf
        a[i] = '0'+d+39*(d>9)
        x >>= 4
        i -= 1
    end
    if neg; a[1]='-'; end
    String(a)
end
```

behavior is the same for current release and master

**Comment by andreasnoack** [comment]
Using `binomial` in https://github.com/JuliaStats/Distributions.jl/blob/master/src/univariate/discrete/betabinomial.jl#L85 is not going to work for large `n`. Just using the beta function might be sufficient in practice. Using `lbeta` would solve overflow problem generally but then we might introduce some precision issues. It would be great if you could try to prepare a PR with `beta` instead of `binomial`.

**Comment by cjprybol** [comment]
Could you elaborate on that? I've been reading into this for a few hours and I'm not making the connection on how to replace `binomial` with `beta`.

I did find that the `beta` function is related to the `gamma` function, and that `gamma(x+1) = x!`. It seems that `gamma(n+1)/(gamma(k+1) * gamma(n-k+1))` is a drop in replacement for `Float64(binomial(n,k))` that tolerates larger values.
```
julia> for n = 1:66
               k = Int(round(n/2))
               # should be true in all cases
               if ~isapprox(Float64(binomial(n,k)), gamma(n+1)/(gamma(k+1) * gamma(n-k+1)))
                       println("not true")
               end
       end

julia> n = 67
67

julia> Float64(binomial(n,k))
ERROR: InexactError()
 in binomial(::Int64, ::Int64) at ./intfuncs.jl:410

julia> gamma(n+1)/(gamma(k+1) * gamma(n-k+1))
1.4226520737620285e19
```

This handles `n <= 170`, and after that it returns `Inf` and eventually `NaN`
```
julia> n = 170; gamma(n+1)/(gamma(k+1) * gamma(n-k+1))
1.6672788518212936e35

julia> n = 171; gamma(n+1)/(gamma(k+1) * gamma(n-k+1))
Inf

julia> n = 200; gamma(n+1)/(gamma(k+1) * gamma(n-k+1))
NaN
```

would this behavior be preferable to the current behavior?

**Comment by ararslan** [comment]
Nice work. 🙂 You can simplify it slightly as `1 / ((n+1) * beta(k+1, n-k+1))`, which avoids a division operation.

**Comment by cjprybol** [comment]
addressed via https://github.com/JuliaStats/Distributions.jl/pull/549
