### ISSUE TITLE
Cannot clone Distributions.jl in Travis CI build

### ISSUE THREAD

**Issue by juliohm** [JuliaStats/Distributions.jl#548]
Can you please confirm this is some random error in the build not related to `Distributions.jl`? https://travis-ci.org/juliohm/ImageQuilting.jl/jobs/168806147

**Comment by andreasnoack** [comment]
Did you try to restart the build before you posted here?

**Comment by juliohm** [comment]
I don't have any particular commit to push right now, I will close the issue and reopen if the build fails again.

**Comment by andreasnoack** [comment]
It shouldn't be necessary to push anything. The should be a restart button. See
<img width="1076" alt="screen shot 2016-10-19 at 2 27 43 pm" src="https://cloud.githubusercontent.com/assets/505001/19532133/60b1fbfc-9608-11e6-80e2-7d7d8033aba6.png">

**Comment by juliohm** [comment]
First time I see this button! Very useful, just pressed it.

**Comment by juliohm** [comment]
The error persists: https://travis-ci.org/juliohm/ImageQuilting.jl/jobs/168806147

**Comment by ararslan** [comment]
AFAIK it's not an issue specific to Distributions, it's an SSL certificate issue on 0.6 that's currently being addressed in Base.

**Comment by juliohm** [comment]
@ararslan do you have a reference for the issue?

**Comment by ararslan** [comment]
https://github.com/JuliaLang/julia/issues/18871

**Comment by ararslan** [comment]
Closing since the issue isn't addressable here.
