### ISSUE TITLE
NoncentralChisq is undocumented

### ISSUE THREAD

**Issue by nbecker** [JuliaStats/Distributions.jl#550]

**Comment by ararslan** [comment]
I believe this is one of several things that are undocumented in this package. I think the best course of action would be to go through and update docstrings, then switch over the doc system to Documenter.jl. That should be easier to maintain going forward.

**Comment by lbollar** [comment]
I would be interested in writing some doc strings on this and possibly in other places where it might be needed. For this one, would I just need to follow the example in the Normal Distribution docstring?

**Comment by ararslan** [comment]
@lbollar That would likely be a good place to start. I'm glad someone is interested in taking this on, thanks!

**Comment by lbollar** [comment]
@ararslan Does this need to be closed out?

**Comment by ararslan** [comment]
Yes it does, thanks for the reminder!
