### ISSUE TITLE
DirichletMultinomial

### ISSUE THREAD

**Issue by joshday** [JuliaStats/Distributions.jl#552]
Hi all.  When I have time, I'd be happy to contribute the multivariate extension of `BetaBinomial`.  Before I start putting a PR together, has anyone started work on this?

The MLE algorithm I would use is in section 3.1 here, unless someone has a pointer to a better approach.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2945396/pdf/nihms205488.pdf

**Comment by ararslan** [comment]
I don't know of any work currently being done on that. A PR would be great.

**Comment by joshday** [comment]
closed by https://github.com/JuliaStats/Distributions.jl/pull/553
