### ISSUE TITLE
Documentation on implementing custom distributions out of date?

### ISSUE THREAD

**Issue by kkmann** [JuliaStats/Distributions.jl#558]
Hey,

I just tried to implement a minimal custom distribution according to http://distributionsjl.readthedocs.io/en/latest/extends.html#create-a-univariate-distribution (i.e., provide rand, pdf, cdf, minimum, maximum, quantile methods).
This does not seem to be sufficient though as mean etc. throw error about the distribution object not being iterable (base.start()...). Is is possible that the documentation is out of date on this point, could you be more specific about what needs to be implemented in order to get a working distribution object? 
If I get this running I might compile a short minimal working example for the docs...

**Comment by joshday** [comment]
I think you missed part of the docs on the page you linked:

> It is also recommended that one also implements the following statistics functions:
> - mean: compute the expectation.
> - var: compute the variance. (A generic std is provided as std(d) = sqrt(var(d))).
> ...
