### ISSUE TITLE
Add list of supported distributions to the documentation

### ISSUE THREAD

**Issue by juliohm** [JuliaStats/Distributions.jl#562]
I couldn't find a list of distributions in the docs, did I miss it?

**Comment by ararslan** [comment]
> did I miss it

Yes

* http://distributionsjl.readthedocs.io/en/latest/univariate-continuous.html
* http://distributionsjl.readthedocs.io/en/latest/univariate-discrete.html
* http://distributionsjl.readthedocs.io/en/latest/multivariate.html
* http://distributionsjl.readthedocs.io/en/latest/matrix.html

**Comment by juliohm** [comment]
Indeed, still missing sections in the readthedocs template from MkDocs. Thank you.

**Comment by ararslan** [comment]
No problem. It might be nice to have a page that lists all supported distributions in one place, with links to the primary doc sections for each. If you think that'd be worthwhile, a PR would be welcome.
