### ISSUE TITLE
Cannot take multiple samples from Categorical unless parameter is of type Vector{Float64}

### ISSUE THREAD

**Issue by ericproffitt** [JuliaStats/Distributions.jl#567]
For example:

```
d = Categorical(Float32[0.5,0.5])
rand(d, 2)
```

and

```
d = Categorical([1,0])
rand(d, 2)
```

both result in an error.

**Update**

I changed the `make_alias_table!` function in the file `~/v0.5/StatsBase/src/sampling.jl` from

```
function make_alias_table!(w::AbstractVector{Float64}, wsum::Float64,
                           a::AbstractVector{Float64},
                           alias::AbstractVector{Int})
```

to

```
function make_alias_table!{T<:Real}(w::AbstractVector{T}, wsum::Float64,
                           a::AbstractVector{Float64},
                           alias::AbstractVector{Int})
```

and this seemed to fix it, but I'm not familiar enough with this package to know if this will cause side effects in other parts of the package.

**Comment by sivapvarma** [comment]
+1 I too got that error when I tried to get multiple samples.

**Comment by xukai92** [comment]
Maybe you can just use a Multinomial distribution for this purpose?

**Comment by devmotion** [comment]
The issue was fixed by https://github.com/JuliaStats/StatsBase.jl/pull/499. With StatsBase 0.33.12 both examples work.
