### ISSUE TITLE
distributions.jl parallel safe?

### ISSUE THREAD

**Issue by kkmann** [JuliaStats/Distributions.jl#573]
Hi,

are the random numbers parallel safe, i.e. independent over multiple threads? If not are there any plans of getting there eventually?

Best,

Kevin

**Comment by simonbyrne** [comment]
They should be safe for multiple processes, but I would suspect not for multiple threads (mostly because of the Rmath library, which uses static variables internally).

**Comment by richardreeve** [comment]
They are now if you use per-thread RNGs as the first argument, so maybe this can be closed? That's certainly what I'm doing in my code now, and I can't see why there would be a problem.

**Comment by kkmann** [comment]
cool, thx!
