### ISSUE TITLE
Types of Categorical distribution

### ISSUE THREAD

**Issue by lindahua** [JuliaStats/Distributions.jl#575]
The current definitions/constructors for ``Categorical`` allows constructing ``Categorical{Int}`` that hosts an integral probability vector.

```julia
julia> d = Categorical([1, 0])
Distributions.Categorical{Int64}(K=2, p=[1,0])
```

This would lead to various issues like #567. To me, an integral probability vector makes no sense (except in few extreme cases, e.g. ``p`` being an indicator vector). Therefore, I think it is better to restrict ``T`` to ``T<:AbstractFloat``. Of course, the constructor can continue to accept integral arguments like ``Categorical([2, 3])``, but it should produce ``Categorical{Float64}(K=2, p=[0.4, 0.6])``.

If no objection, I can quickly make a PR.

**Comment by johnmyleswhite** [comment]
Do dual numbers descend from `AbstractFloat`? My impression is that the current parameter rules are overly loose to allow duck-typing in the absence of traits.

**Comment by lindahua** [comment]
This is the current definition:

```julia
immutable Categorical{T<:Real} <: DiscreteUnivariateDistribution
    # ...
end
```

I just checked, ``Dual{Float64}`` is not even a descendant of ``Real``.

I guess we need to establish some guideline on how to specify the parameter types of the distributions.

**Comment by johnmyleswhite** [comment]
I think the implementation in ForwardDiff is a descendant of `Real`: https://github.com/JuliaDiff/ForwardDiff.jl/blob/6c80759000d44c4ef5b9951a2bb625103d606712/src/dual.jl#L7

Agree that we need to document these kinds of design decisions in a wiki or something else that developers of this package can share.

**Comment by andreasnoack** [comment]
The current approach is to restrict parameters to `Real`. I don't think we win much by restricting the types more. We just exclude `ForwardDiff` types as pointed out by John. I think many of the constructors already convert `Integer` input to `Float64` and we could follow that approach here as well.

**Comment by matbesancon** [comment]
Closing this one, we can re-open if still considered an issue
