### ISSUE TITLE
VonMisesFisher pdf values in Julia are not the same as in R

### ISSUE THREAD

**Issue by AngelBerihuete** [JuliaStats/Distributions.jl#580]
Using  package ‘movMF’ version 0.2-0 (R) and Distributions version 0.12.1 (Julia) something strange happens:

```julia
using Distributions
d = VonMisesFisher([1,0])
pdf(d, [1,0])
```
obtaining ```0.34171048862346315```. But using R

```R
library(movMF)
x <- t(matrix(c(1,0)))
dmovMF(x, theta = c(1,0), alpha = 1, log = FALSE)
```
obtaining ```2.14703```. But, If I understood well, both distributions are the same.

**Comment by johnmyleswhite** [comment]
How sure are you that you're understanding what the comparison with R means?

The following sanity checks suggest the current PDF method is correct:

```
using Distributions
d = VonMisesFisher([1,0])

# PDF integrates to 1
quadgk(θ -> pdf(d, [cos(θ), sin(θ)]), 0, 2 * π)

# Check entropy against formula from https://en.wikipedia.org/wiki/Von_Mises_distribution
n = 1_000_000
x = rand(d, n)

I0 = quadgk(x -> (1 / π) * exp(d.κ * cos(x)) * cos(0 * x), 0, π)[1]
I1 = quadgk(x -> (1 / π) * exp(d.κ * cos(x)) * cos(1 * x), 0, π)[1]

analytic_entropy = -d.κ * (I1 / I0) + log(2 * π * I0)
monte_carlo_entropy = -loglikelihood(d, x) / n
analytic_entropy, monte_carlo_entropy
# In one run, this generates (1.6274014590200032,1.6267325801779862)
```

**Comment by AngelBerihuete** [comment]
I've checked the function in Julia and definitively it works. People of movMF package have parametrized the von Mises-Fisher distribution using "the confluent hypergeometric limit function" (which is related to the modified Bessel function of the first kind). I'll ask them about this function.
