### ISSUE TITLE
Error in kurtosis formula of F distribution

### ISSUE THREAD

**Issue by Planeshifter** [JuliaStats/Distributions.jl#590]
Thanks for this library! 
I would like to report a bug: 
The [code](https://github.com/JuliaStats/Distributions.jl/blob/master/src/univariate/continuous/fdist.jl#L82) implementing the kurtosis for the Fisher F distribution seems to contain a typo. 
The current code for the denominator is `ν1 * (ν2 - 6) * (ν2 - 8) * (ν2 - 2)`, whereas the correct formula is `ν1 * (ν2 - 6) * (ν2 - 8) * (ν1 + ν2 - 2)`, see [1](https://en.wikipedia.org/wiki/F-distribution) or [2](http://www.math.uah.edu/stat/special/Fisher.html).

**Comment by johnmyleswhite** [comment]
Thanks for the report. I confirm this is a bug. If you're up for it, you can make small changes like this using the GitHub UI by clicking on the edit button while looking at the source file. That will generate a pull request based on your edits, which is easy to merge.

**Comment by johnmyleswhite** [comment]
To be clear: since this was so basic, I wrote a pull request myself for this one.

**Comment by Planeshifter** [comment]
Thank you very much for the quick reply! The pull request suggestion is noted for the future.
