### ISSUE TITLE
Error in CDF of Cosine distribution

### ISSUE THREAD

**Issue by Planeshifter** [JuliaStats/Distributions.jl#598]
The CDF of the cosine distribution incorrectly returns values outside of [0,1] for values not inside of its support. For example

``` 
dist = Cosine( 2, 4 );
cdf( dist, 10 );
```

returns `1.5`. 

The current implementation looks as follows:

```
function cdf(d::Cosine, x::Real)
    z = (x - d.μ) / d.σ
    (1 + z + sinpi(z) * invπ) / 2
end
```

To correct this error, the function should be amended to return zero for `x < μ − σ` and one for `x > μ + σ` (see the [Wikipedia article][wikipedia]). The problem applies to `ccdf`, too.

[wikipedia]: https://en.wikipedia.org/wiki/Raised_cosine_distribution

**Comment by andreasnoack** [comment]
Thanks for reporting this. It would be great if you could open a pull request to fix the issue.

**Comment by Planeshifter** [comment]
Created a pull request.

**Comment by Planeshifter** [comment]
Closing this issue as the pull request has been merged. Thank you!
