### ISSUE TITLE
Error in logPDF and PDF of beta prime distribution 

### ISSUE THREAD

**Issue by Planeshifter** [JuliaStats/Distributions.jl#604]
The support of the beta prime distribution is the interval `[0,∞ )`. For input values smaller than `0`, the PDF currently throws a domain error. It should return zero. Similarly, the logpdf should return negative infinity for input values smaller than zero.

**Comment by andreasnoack** [comment]
I don't get a domain. I just get a wrong result.
```julia
julia> cdf(BetaPrime(), -2)
1.0
```

**Comment by andreasnoack** [comment]
Never mind. I read it as `cdf` and I have just seen your other issue.

**Comment by ararslan** [comment]
Fixed by #607
