### ISSUE TITLE
Error in cdf/ccdf/logcdf/logccdf of beta prime distribution 

### ISSUE THREAD

**Issue by Planeshifter** [JuliaStats/Distributions.jl#605]
For `x < 0`, the beta prime CDF currently returns `1.0`. This is clearly incorrect as every CDF has to be non-decreasing and right-continuous. The other functions mentioned in the title return wrong results as well due to this. We have to manually handle inputs smaller than zero.

**Comment by ararslan** [comment]
Fixed by #607
