### ISSUE TITLE
Feature Request: Various measures of "inequality"

### ISSUE THREAD

**Issue by ptoche** [JuliaStats/Distributions.jl#617]
This is a feature request: as far as I know ``Distributions.jl`` does not currently provide standard measures of inequality, e.g. __Lorenz curve__,  __Theil entropy index__, __Atkinson index__, that sort of thing. Or have I missed it? Or is there a dedicated package? 

For the sort of inequality measures that social scientists use, see here: http://darp.lse.ac.uk/papersDB/Cowell_measuringinequality3.pdf, particularly section 2.2 on page 23.

To plot a Lorenz curve, compute a GINI coefficient would be great.

For the sort of convenience functions provided by statistical software, see here for ideas: http://repec.sowi.unibe.ch/files/wp15/jann-2016-lorenz.pdf

(A gist by ZacNugent has some of this done here:
https://gist.github.com/ZacLN/fd34052b6a17ea9274f1e92cf82d6472
I read about it here:
https://discourse.julialang.org/t/inequality-fairness-measures-in-julia/1732
And I have no idea about license issues relating to this code.)

**Comment by ararslan** [comment]
Providing functions like that is beyond the scope of this package. I'm not familiar with any of those measures, but you may want to have a look at [Distances](https://github.com/JuliaStats/Distances.jl).

**Comment by ptoche** [comment]
Or perhaps a future package specifically dedicated to ``Inequality.jl``  along the lines of [python](http://pysal.readthedocs.io/en/latest/library/inequality/)   or [R](https://cran.r-project.org/web/packages/ineq/ineq.pdf). :-)

**Comment by ararslan** [comment]
I encourage you to make and publish such a package. 🙂

In the meantime I'll close this issue, since the mentioned functionality is beyond the scope of this package.

**Comment by ptoche** [comment]
Maybe as a summer project, if I have learned enough Julia by then!
