### ISSUE TITLE
TruncatedNormal with Inf mean hangs

### ISSUE THREAD

**Issue by cossio** [JuliaStats/Distributions.jl#624]
Just try this example:

```
rand(Distributions.TruncatedNormal(Inf, 1., 0., 1.))
```

It hangs forever. I am using Julia 0.5.

It should raise an error somewhere instead.

**Comment by matbesancon** [comment]
Oh man this hasn't been touched in ages. The fault is on `randnt` here, untested. The algorithm seems not to have termination guarantees, we may had a timeout or maxiter

**Comment by cossio** [comment]
In this case I think a simple check `@assert -Inf < mu < Inf` would suffice.

**Comment by matbesancon** [comment]
yes sure, although it is very likely to hang for large non-Inf numbers too right?

**Comment by matbesancon** [comment]
Anyhow PR welcome

**Comment by cossio** [comment]
> yes sure, although it is very likely to hang for large non-Inf numbers too right?

No. It just hangs because when the mean is infinite we end up calling `randnt(Inf, Inf)` which never terminates.
