### ISSUE TITLE
Migrate documentation to Documenter

### ISSUE THREAD

**Issue by ararslan** [JuliaStats/Distributions.jl#629]
It is the future

**Comment by rofinn** [comment]
@ararslan I could probably do that if you don't have time, as I'm reasonably familiar with Documenter. I'd just need someone in JuliaStats to setup the travis and github keys.

**Comment by ararslan** [comment]
Hey Rory, thanks for volunteering! If you want to take this on I certainly won't stop you. 😉 I've set up the requisite keys on GitHub and Travis. Note that you'll need to `git mv doc docs` because Documenter wants the latter for whatever reason. Let me know if there's anything you need from me as you go along and I'd be happy to help.

**Comment by rofinn** [comment]
For sure, thanks for setting up the keys.
