### ISSUE TITLE
posterior function is missing

### ISSUE THREAD

**Issue by ValdarT** [JuliaStats/Distributions.jl#633]
The [documentation](http://distributionsjl.readthedocs.io/en/latest/conjugates.html) covers a posterior() function that seems to be missing in the package and the examples in the documentation do not work.

Perhaps it was moved to [ConjugatePriors.jl](https://github.com/JuliaStats/ConjugatePriors.jl) at some point but that package seems outdated.

**Comment by andreasnoack** [comment]
Yes, it was moved to ConjugatePriors.jl so the documentation here needs to be updated.

**Comment by matbesancon** [comment]
Removed from documentation
