### ISSUE TITLE
Likelihood functions

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaStats/Distributions.jl#646]
While the `fit` function is nice, in many applications the likelihood function itself is needed. It would be nice if a user could give a `Distribution` and there was a way to directly calculate the likelihood function for a given set of observations and parameters. This would be useful for algorithms which internally have generalized likelihood estimation since then these can easily extend to more distributions by using Distributions.jl.

**Comment by Ayush-iitkgp** [comment]
Adding onto Chris's point, we want to generate the maximum likelihood cost function for our model like explained [here](https://bmcsystbiol.biomedcentral.com/articles/10.1186/s12918-015-0219-2) for Normal Distribution. And this cost function can be passed to different optimizers such as Optim, NLopt to find the maxima and the corresponding value of the parameters of the differential equations.

**Comment by joshday** [comment]
There's already `loglikelihood`?

```julia
julia> using Distributions

julia> loglikelihood(Normal(), randn(100))
-125.55856854256659
```

**Comment by ChrisRackauckas** [comment]
Ah, didn't see that. Is there a reason there's only the log likelihood? We can use that though, thanks.

**Comment by joshday** [comment]
Numerical stability, I suppose.  loglikelihood is a sum and likelihood is a product.
