### ISSUE TITLE
`MvNormal` different matrix types

### ISSUE THREAD

**Issue by simonbyrne** [JuliaStats/Distributions.jl#652]
It would be nice if `MvNormal` supported more matrix types, particularly `Diagonal` and `Symmetric`. In the longer term, I would also like to see support for StaticArrays.jl.

**Comment by andreasnoack** [comment]
I think we should separate out the multivariate distributions to a separate package and start experimenting with support for `StaticArrays`.

**Comment by mschauer** [comment]
`Distribution` should just be parametrized by eltype...  locally I work with https://github.com/mschauer/Bridge.jl/blob/master/src/gaussian.jl when using `StaticArrays`s

**Comment by mschauer** [comment]
There has been progress here as well.

**Comment by tpapp** [comment]
In the meantime, while these experiments pan out, made a PR with a trivial fix for the original issue.
