### ISSUE TITLE
Support for initializing distribution with array of parameters

### ISSUE THREAD

**Issue by yoavram** [JuliaStats/Distributions.jl#663]
Allowing creation of distribution objects from arrays of parameters is very efficient in terms of both expression and computation.

### Example:

This is standard in NumPy/SciPy:
```py
import numpy as np
import scipy.stats

n = 100
x = np.linspace(0, 1, 10)
scipy.stats.binom.rvs(n, x) # -> array([  0,  11,  18,  36,  42,  61,  62,  73,  90, 100])
```

However it is not possible in Julia/Distributions:
```jl
using Distributions

n = 100
x = linspace(0, 1, 10)
rand(Binomial(n, x)) # -> MethodError: no method matching Distributions.Binomial(::Int64, ::StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}})
```
so instead I need to replace the last line with
```jl
[rand(Binomial(n, x_)) for x_ in x] # ->  10-element Array{Int64,1}: 0  7  19  38  45  64  58  74  88  100
```
which is less succinct.

Also, in terms of running time, I measured 0.174 sec for the Python version
```py
x = np.linspace(0, 1, 1000000)
%timeit scipy.stats.binom.rvs(n, x)
```
and ~0.25 sec for the Julia version, probably because of the list comprehension (?):
```jl
x = linspace(0, 1, 1000000)
@benchmark [rand(Binomial(n, x_)) for x_ in x]
```
but this is can be fixed by putting the list comprehension in a function - then it's faster than Python:
```jl
x = linspace(0, 1, 1000000)
bin_rand(n, x) = [rand(Binomial(n, x_)) for x_ in x]bin_rand(n, x)
bin_rand(n, x); # first pass
@benchmark bin_rand(n, x)
```
which gives ~0.11 sec.

**Comment by andreasnoack** [comment]
The way to do this in Julia is
```julia
rand.(Binomial.(n, x))
```
On my machine it is faster than SciPy.

**Comment by yoavram** [comment]
Thx @andreasnoack I appreciate the help.

This Julia version on the same machine as above takes 0.11 sec, same as the function wrapping the list comprehension above:
```jl
n = 100
x = linspace(0, 1, 1000000)
@benchmark rand.(Binomial.(n, x))
```
