### ISSUE TITLE
logpdf on mixture of multivariate normals segfaults

### ISSUE THREAD

**Issue by ludkinm** [JuliaStats/Distributions.jl#669]
MWE:
```

using Distributions
K=4
G = MixtureModel([MvNormal(x*ones(K), 1e-6*ones(K,K) + 1e-5I) for x in 1:K])
X = ones(K,10)
logpdf(G,X)

```
I get a segmentation fault on the last call, with signal 11.
julia: 0.6.0
Distributions: 0.14.2

**Comment by nalimilan** [comment]
Doesn't crash it with the same versions. What OS are you using?

**Comment by ludkinm** [comment]
manjaro 17.0.5 (running linux kernal 4.9)

**Comment by nalimilan** [comment]
I assume 64-bit? How did you install Julia?

**Comment by ludkinm** [comment]
Yes 64bit. Installed via the pacakge manager gui.
It is running as a VirtualBox on win10 host.

**Comment by ludkinm** [comment]
After reading the release pages I realize that installing from binary is recommended. 
Installing from source and re-installing packages has fixed the problem.

I think the issue may have been the llvm.
The packaged version on arch has the arch package "llvm39-libs" as a dependency.
However, by installing from source, I assume that julia is using the (already installed) llvm-5.0.so under /usr/lib.

Thanks for pointing me in the right direction.

**Comment by nalimilan** [comment]
Good to hear, but it would be worth reporting the problem to your distribution. This is bad advertisement for Julia if it crashes when people install it from packages.

FWIW, llvm-5.0.so has the version in the name, so it is unlikely to be the source of the problem.
