### ISSUE TITLE
For Atom-Julia, it says could not load library

### ISSUE THREAD

**Issue by ebbythomas** [JuliaStats/Distributions.jl#689]
I use atom-julia. When i tried to work out a problem using TensorFlow, it says me  the following

could not load library "C:\Users\uqethom9\.julia\v0.6\TensorFlow\src\..\deps\usr\bin\libtensorflow" The specified module could not be found.  

I did try Pkd.build("TensorFlow"), but it is not helping
Any help is greatly appreciated.
Ebby

**Comment by ChrisRackauckas** [comment]
Is this posted on the wrong library? This is Distributions.jl, not TensorFlow.jl. 

For TensorFlow.jl, you have to install TensorFlow first.
