### ISSUE TITLE
Mean and variance of truncated normal far from the mode fails

### ISSUE THREAD

**Issue by cossio** [JuliaStats/Distributions.jl#690]
```
julia> d = Distributions.TruncatedNormal(0,1, 100, 115)
Truncated(Distributions.Normal{Float64}(μ=0.0, σ=1.0), range=(100.0, 115.0))

julia> mean(d)
NaN
```

**Comment by andreasnoack** [comment]
I don't really see how that could be different unless you special cased the distribution in that area. If the calculation is based on the untruncated version then you'll need some probability mass in the included region. If not I think `NaN` is a reasonable result. What we should do is to parameterize `Truncated` on the element type in https://github.com/JuliaStats/Distributions.jl/blob/master/src/truncate.jl such that you could do the calculation in `BigFloat`s.

**Comment by cossio** [comment]
I think it can be done in ordinary Floats, see https://github.com/cossio/TruncatedNormal.jl. I am testing it a bit more first, then I'll try to PR here.

**Comment by cossio** [comment]
@andreasnoack I have setup a PR, https://github.com/JuliaStats/Distributions.jl/pull/691.
