### ISSUE TITLE
Chernoff distribution is not covered

### ISSUE THREAD

**Issue by NittanyLion** [JuliaStats/Distributions.jl#692]
Hello,

The Chernoff distribution is not covered: see [http://www.tandfonline.com/doi/pdf/10.1198/10618600152627997?needAccess=true](http://www.tandfonline.com/doi/pdf/10.1198/10618600152627997?needAccess=true) for its computation.

Thanks!

**Comment by NittanyLion** [comment]
I've written the necessary code myself.  How do I upload it/get it included in the package?

**Comment by andreasnoack** [comment]
Great. Have you contributed to GitHub project previously? You should fork the package on GitHub, check out latest master of the package, commit your changes, push to the fork, and finally open a PR against the main repo.

**Comment by NittanyLion** [comment]
Thanks Andreas.  No, I have not.  I'll try to figure this out some time this week.

**Comment by dmbates** [comment]
@NittanyLion [This manual section](https://docs.julialang.org/en/stable/manual/packages/#Package-Development-1) gives a suggested approach to creating pull requests for existing packages.
