### ISSUE TITLE
MLE for GEV distribution

### ISSUE THREAD

**Issue by juliohm** [JuliaStats/Distributions.jl#698]
It would be great to have maximum likelihood fits implemented for the generalized extreme value family. I can try tackle it myself if I find the time, but if someone has done it in the past, please let me know and I can try reuse the code.

**Comment by juliohm** [comment]
Would it be ok to make Optim.jl a dependency for this or is it too much?

**Comment by andreasnoack** [comment]
I don't think we should have general support for fitting in this package so I'd say no. It is better to have estimation specific functionality elsewhere.

**Comment by juliohm** [comment]
Agree, where should estimation functionality exist?

Next quarter I will be a teaching assistant and I was hoping to show students a simple `fit(GEV, data)`. If there is a package where these things are being developed, I can submit a PR there instead.

The issue with GEV specifically is that it requires constrained optimization, and Optim.jl would come in handy as a dependency. I don't want to reinvent the wheel.

**Comment by andreasnoack** [comment]
I agree that `Optim.jl` would be a natural dependency for such a package. I don't know if there are any current efforts to generally support fitting distributions beyond what is in this package. Maybe a new package should be initiated.

**Comment by juliohm** [comment]
@andreasnoack can this package be initiated in the organization by some of you? I can submit PRs there instead.

**Comment by juliohm** [comment]
Thinking more carefully about it, I think extreme value theory deserves a separate package. I will provide the students with Jupyter notebooks this quarter, and will try to organize the material in a package in the future.
