### ISSUE TITLE
define methods for StatsBase.mean_and_std and mean_and_var

### ISSUE THREAD

**Issue by tpapp** [JuliaStats/Distributions.jl#715]
For distributions which have both `mean` and `std`, a method for `StatsBase.mean_and_std` would be useful. Similarly `mean_and_var` when applicable.

This would help with compact code like
```julia
μ, σ = mean_and_std(some_distribution)
```

**Comment by andreasnoack** [comment]
When computing `mean_and_std` from a data vector you can save a little bit by computing both quantities in the same function but that is not really the case for `Distributions`. The function also has a really ugly name so wouldn't
```julia
X = some_distribution
μ, σ = mean(X), std(X)
```
?

**Comment by tpapp** [comment]
Good point. I was working on a function which would take both data and distributions, where a generic `mean_and_std` would have been convenient, but I refactored since; closing the issue.
