### ISSUE TITLE
PDMats Type Error?

### ISSUE THREAD

**Issue by chelseas** [JuliaStats/Distributions.jl#719]
There seems to be some kind of error in PDMats. See minimal example attached. It seems like I'm using the function properly. I passed in a 2-element column vector for the mean, and a 2-D matrix for the covariance. 

[GaussiansMinimalExample.pdf](https://github.com/JuliaStats/Distributions.jl/files/1975546/GaussiansMinimalExample.pdf)

**Comment by alejandromerchan** [comment]
I solved your issue by changing 0 to 0. in the 2-D matrix for the covariance. Actually, it looks like just changing any of the values inside the matrix to floating point solves the issue (also works by changing 1 to 1.) Probably another method should be add to PDMats that accepts Int values?
