### ISSUE TITLE
Numerical issues with Beta Binomial

### ISSUE THREAD

**Issue by jonathanBieler** [JuliaStats/Distributions.jl#738]
```julia
julia> pdf(BetaBinomial(5000,1/1000,1),200)
NaN
```

It seems that the definition in terms of the [Gamma function](https://en.wikipedia.org/wiki/Beta-binomial_distribution#Motivation_and_derivation) works better:

```julia
julia> function pdf(d::BetaBinomial{T}, k::Int)  where T 
           x, n, a, b   = k, d.n, d.α, d.β
           exp(lgamma(n+1) + lgamma(x+a) + lgamma(n-x+b) + lgamma(a+b) - (lgamma(x+1) + lgamma(n-x+1) + lgamma(a) + lgamma(b) + lgamma(n+a+b)))
       end

julia> pdf(BetaBinomial(5000,1/1000,1),200)
4.98391853943159e-6
```

**Comment by mvihola** [comment]
Would it be possible to add some domain checks to logpdf (or pdf); now there are three different things that can happen if the point is not in the domain:
```julia
julia> logpdf(BetaBinomial(10,2,2),11)
-Inf

julia> logpdf(BetaBinomial(10,2,2),12)
NaN

julia> logpdf(BetaBinomial(10,0.5,0.5),11)
ERROR: DomainError with -0.5:
`gamma(x)` must be non-negative
Stacktrace:
 [1] loggamma at /Users/mvihola/.julia/packages/SpecialFunctions/5QYEE/src/gamma.jl:666 [inlined]
 [2] logbeta(::Float64, ::Float64) at /Users/mvihola/.julia/packages/SpecialFunctions/5QYEE/src/gamma.jl:812
 [3] logpdf(::BetaBinomial{Float64}, ::Int64) at /Users/mvihola/.julia/packages/Distributions/dTXqn/src/univariate/discrete/betabinomial.jl:97
 [4] top-level scope at none:0
```

**Comment by devmotion** [comment]
> It seems that the definition in terms of the Gamma function works better:

It seems it's sufficient to define
```julia
pdf(d::BetaBinomial, k::Int) = exp(logpdf(d, k))
```
since
```julia
julia> exp(logpdf(BetaBinomial(5000,1/1000,1),200))
4.983918539418416e-6
```

I'm wondering why it's the default for multivariate distributions to use the fallback `pdf(dist, x) = exp(logpdf(dist, x))` (see https://github.com/JuliaStats/Distributions.jl/blob/20c91d9efcc5f96913bf8e38be2e3fb14b21942b/src/multivariates.jl#L190) whereas it's the other way around for univariate distributions (see https://github.com/JuliaStats/Distributions.jl/blob/20c91d9efcc5f96913bf8e38be2e3fb14b21942b/src/univariates.jl#L342-L343).

**Comment by devmotion** [comment]
This issue was fixed by https://github.com/JuliaStats/Distributions.jl/pull/1171. On master I get
```julia
julia> using Distributions

julia> pdf(BetaBinomial(5000,1/1000,1),200)
4.983918539418416e-6
```
