### ISSUE TITLE
failprob / succprob

### ISSUE THREAD

**Issue by matbesancon** [JuliaStats/Distributions.jl#747]
These methods don't seem generic but specific to success/failure cases, should it really be defined for all `UnivariateDistribution` if the support is only {0,1}?

**Comment by simonbyrne** [comment]
We could probably deprecate them.

**Comment by matbesancon** [comment]
If it's from the interface, no need to move to deprecations, just delete from the interface part of the doc and leave them as-is in Bernoulli. If someone implements it, nothing will change for them

**Comment by matbesancon** [comment]
Closed by #753
