### ISSUE TITLE
Create Zenodo for Distributions

### ISSUE THREAD

**Issue by matbesancon** [JuliaStats/Distributions.jl#765]
Following [this](https://discourse.julialang.org/t/publication-doi-on-juliastats-package/14479) thread on discourse, a zenodo-generated DOI for Distributions would be great and necessary for properly citing all contributors of Distributions

**Comment by matbesancon** [comment]
See this interesting link
http://blog.chrisgorgolewski.org/2017/11/sharing-academic-credit-in-open-source.html

**Comment by Nosferican** [comment]
See an example of a package using Zenodo: https://github.com/Nosferican/NCEI.jl.

**Comment by jtackm** [comment]
Thanks for the quick response, then I will use that for now.

**Comment by matbesancon** [comment]
@jtackm how to cite is now in the README and there is a DOI link
