### ISSUE TITLE
Univariate distributions still not broadcastable?

### ISSUE THREAD

**Issue by mkhlee** [JuliaStats/Distributions.jl#767]
Hi, I've been trying to use 'Distributions.cdf' as follows:

```
using Distributions
x = randn(10);
y = cdf.(Normal(0,1),x);

ERROR: MethodError: no method matching iterate(::Normal{Float64})
Closest candidates are:
  iterate(::Core.SimpleVector) at essentials.jl:578
  iterate(::Core.SimpleVector, ::Any) at essentials.jl:578
  iterate(::ExponentialBackOff) at error.jl:171`
```

This is supposed to be a fixed issue as per https://github.com/JuliaStats/Distributions.jl/pull/760.

I am a new user, is there something I'm missing? I've updated Julia and Distributions all the way. Should I be adding something else to the command `cdf.`? Thanks!

When a pull request is accepted, do I need to wait until the package releases a new version? I'm also new to this whole github world, sorry if it's a simple question.

**Comment by simonbyrne** [comment]
The fix should be on the current release (v0.16.3). I assume you figured that out though.
