### ISSUE TITLE
binomial logpdf won't work with Dual

### ISSUE THREAD

**Issue by tpapp** [JuliaStats/Distributions.jl#770]
```julia
julia> using Distributions

julia> import ForwardDiff

julia> l1(α) = logpdf(Binomial(10, α), 2)
l1 (generic function with 1 method)

julia> ForwardDiff.derivative(l1, 0.1)
ERROR: MethodError: no method matching Float64(::ForwardDiff.Dual{ForwardDiff.Tag{typeof(l1),Float64},Float64,1})
```
I think this happens because it uses the R library implementation, but this could be remedied by implementing it in pure Julia, similarly to [`logpdf(::Multinomial, ...)`](https://github.com/JuliaStats/Distributions.jl/blob/1edffc7f07e508e556cf6d595c564b6854f5c258/src/multivariate/multinomial.jl#L143).

**Comment by matbesancon** [comment]
I'm not sure what the derivative of the PMF for a discrete function should look like, is it even defined?

**Comment by matbesancon** [comment]
Oh sorry, read the issue too quickly.
Two possibilities:
1. Post this issue on StatsFuns.jl (and close this one)
2. Wait for #138 to get merged

**Comment by devmotion** [comment]
This issue is fixed in recent versions of Distributions and StatsFuns:
```julia
julia> l1(α) = logpdf(Binomial(10, α), 2)
l1 (generic function with 1 method)

julia> ForwardDiff.derivative(l1, 0.1)
11.11111111111111
```
