### ISSUE TITLE
Is this not available for 1.0.0?

### ISSUE THREAD

**Issue by nstgc** [JuliaStats/Distributions.jl#772]
I enter the REHL package manager with `]` as it says to in the Julia docs. I then type `add Distributions`.

My thought is that either the package manager is broken or this package isn't compatible with my version.

**Comment by simonbyrne** [comment]
What OS are you using? Can you paste the output?

**Comment by nstgc** [comment]
Of course. Sorry.

Arch Linux, up to date.
pkg> add Distributions
ERROR: no active project

**Comment by simonbyrne** [comment]
In either case, you would probably be better off asking on [discourse](http://discourse.julialang.org).
