### ISSUE TITLE
Random seed and Categorical distribution

### ISSUE THREAD

**Issue by konkam** [JuliaStats/Distributions.jl#779]
I have the impression that setting a random seed to 0 and sampling from a Categorical distribution does not have the same effect with these two versions of Julia and package Distribution.

Same observation with another seed. But no problem with other distributions (such as the Multinomial, or the Uniform), I cannot reproduce the discrepancy.

The marginals of the Categorical distribution seem ok in both cases.

Do you have an explanation, by any chance ?

Thanks,

With Julia Version 0.7.0 (2018-08-08 06:46 UTC)  x86_64-pc-linux-gnu
Distributions v0.16.4

```
julia> using Random, Distributions    
julia> Random.seed!(0)    
julia> rand(Categorical([0.3,0.2,0.3, 0.1, 0.1]), 5)    
5-element Array{Int64,1}:
 1
 2
 1
 1
 1
```

With Julia Version 0.6.4 (2018-07-09 19:09 UTC) x86_64-pc-linux-gnu
Distributions v0.15.0

```
julia> using Distributions
julia> srand(0)
julia> rand(Categorical([0.3,0.2,0.3, 0.1, 0.1]), 5)
5-element Array{Int64,1}:
 1
 5
 5
 5
 1
```

**Comment by matbesancon** [comment]
is `srand` the same as `seed!` Maybe the RNG was changed

**Comment by hac-kerman** [comment]
Hi! can you please tell why is rand(Categorical(p)) is giving integers, what does it mean?
