### ISSUE TITLE
Incorporate Expectations.jl

### ISSUE THREAD

**Issue by Nosferican** [JuliaStats/Distributions.jl#780]
Proposal to have [Expectations.jl](https://github.com/econtoolkit/Expectations.jl) incorporated into Distributions.

**Comment by Nosferican** [comment]
This file should give an idea of the interface and features it would be adding:
https://github.com/econtoolkit/Expectations.jl/blob/master/test/iterable.jl

The only dependency change would be to add [FastGaussQuadrature](https://github.com/ajt60gaibb/FastGaussQuadrature.jl)

**Comment by Nosferican** [comment]
Currently the package is at an organization that will be deprecated. We are trying to find an organization that can welcome it. We initially thought of having it as a separate package in JuliaStats since it is an extension of Distributions, but there wasn't much interest to have it as a separate package in the organization even when offered with willing dedicated maintainers. Our last resort is to move it to QuantEcon, but it might lose some generality and be distant from Distributions.jl.

**Comment by ararslan** [comment]
> but it might lose some generality and be distant from Distributions.jl.

This argument doesn't make sense to me. First, I'm not sure how "distance" is a problem: for example, I have a package that extends HypothesisTests under my personal account. I'm also not sure how being in a different organization affects the generality of the package in any way. It's still the same package, the URL is just different.

**Comment by Nosferican** [comment]
Is not about the URL, but the kind of contributors and maintainers close to the project. For example, if a package is in a niche circle it might not evolve to accommodate the needs of its general users. It is that disconnect what I make reference to. For example, plotting backends are close to the people and organizations related (e.g., PyPlot in PyJulia), but are glued together by the Plots API and functionality that extends it lives in JuliaPlots (e.g., StatsPlots). Forcing extension projects for Distributions farther in the developing arena increases the likelihood that the project evolves by a niche group/needs rather than the general needs of Distributions.jl users. [HypothesisTests.jl](https://github.com/JuliaStats/HypothesisTests.jl) is under JuliaStats. I do believe that the organization holder does affect the development of projects and is not just the URL which for released packages most users don't even see.

We can move it to QuantEcon and just try to keep it tightly linked to the Distributions community.

**Comment by simonbyrne** [comment]
Where was the discussion about moving it to JuliaStats.jl?

**Comment by Nosferican** [comment]
Slack mostly. A few weeks back and yesterday.

**Comment by simonbyrne** [comment]
Slack is not great for that sort of thing, as the discussion gets lost into the noise. Perhaps open an issue on the repo (then post the issue to slack)

**Comment by simonbyrne** [comment]
Also, might be better on the #statistics channel.

**Comment by Nosferican** [comment]
Sorry, I meant #statistics. There isn't a organizational repository for applications to include in the organization, no? Would Discourse be the place?
