### ISSUE TITLE
EmpiricalUnivariateDistribution assumption that cdf is a function doesn't match StatsBase

### ISSUE THREAD

**Issue by evanfields** [JuliaStats/Distributions.jl#797]
https://github.com/JuliaStats/StatsBase.jl/pull/429 changes the output of `StatsBase.ecdf` from a function to a callable type. However, `EmpiricalUnivariateDistribution` requires that the `cdf` field has type `Function`. As a result, the convenience constructor `EmpiricalUnivariateDistribution(x::Vector)` is broken with recent versions of StatsBase. (There, the type of `ecdf(x::Vector{Float64}` is `ECDF{Array{Float64,1}}`)

**Comment by andreasnoack** [comment]
Thanks for bringing that up. Notice https://github.com/JuliaStats/Distributions.jl/pull/661/files though. That specific distribution is already pretty broken.

**Comment by iamed2** [comment]
@andreasnoack Is it possible to get a version of that PR in to mitigate this issue?

**Comment by andreasnoack** [comment]
The problem is that the current design of Distributions assumes that discrete distributions have outcomes on the none-negative integers. Hence, fixing the empirical distributions requires that we change the abstract types and hence it's a bit involved.

**Comment by ararslan** [comment]
The distribution has been removed entirely.
