### ISSUE TITLE
ZeroVector is not a vector

### ISSUE THREAD

**Issue by matbesancon** [JuliaStats/Distributions.jl#801]
`ZeroVector` should probably be a subtype of `AbstractVector{T}` or even `StaticVector{T,S}`.
As such, it should also implement the abstract array interface, including `getindex`.

Bonus: since it is used quite a bit in Distributions, it should be documented with at least a docstring

**Comment by andreasnoack** [comment]
I would think that `AbstractVector` should suffice. Are there any known benefits from making it a `StaticVector`?

**Comment by matbesancon** [comment]
Just signaling immutability, except if some methods are defined on the abstract `StaticVector` already

**Comment by simonbyrne** [comment]
Note that the defining property of `StaticVector` is that [it is statically-sized](https://github.com/JuliaArrays/StaticArrays.jl):
> Note that here "statically sized" means that the size can be determined from the type, and "static" does not necessarily imply immutable.

(`SArray` is an implementation that is immutable).
