### ISSUE TITLE
Use AbstractVector for isprobvec

### ISSUE THREAD

**Issue by maxmouchet** [JuliaStats/Distributions.jl#812]
It would be nice if [`isprobvec`](
https://github.com/JuliaStats/Distributions.jl/blob/master/src/utils.jl) could accept an `AbstractVector` instead of a `Vector`.  
This would require to use abstract types for `isfinite`, `allfinite`, `allzeros`, etc.

Is there any drawbacks of doing this ?

**Comment by matbesancon** [comment]
Sorry for the delay. No there isn't, we are trying to generalize the types used the whole code base, PRs are welcome :)

**Comment by matbesancon** [comment]
Fixed by #874
