### ISSUE TITLE
Product of (PDF's of) MvNormal's (edited)

### ISSUE THREAD

**Issue by caldwellshane** [JuliaStats/Distributions.jl#820]
I'm using a function
```
function *(N1::MvNormal, N2::MvNormal)::MvNormal
    μ1, Σ1 = mean(N1), cov(N1)
    μ2, Σ2 = mean(N2), cov(N2)
    Σ = inv(inv(Σ1) + inv(Σ2))
    μ = Σ * (inv(Σ1)*μ1 + inv(Σ2)*μ2)
    return MvNormal(μ, Σ)
end
```
to compute the normalized product of two MvNormal distributions, which is another MvNormal. Would this be a useful addition?

I notice that this would run counter to the definition that seems to follow the definition of `+` in Issue #142, where `*` would rather be the distribution of the product of the random variables. I could use some guidance on how folks would like this to fit in, if at all.

**Comment by simonbyrne** [comment]
Do you mean the distribution with the same normalised product of the densities? It's not really a product, but I agree it is a useful operation, since it pops up in posterior updates and Kalman filters.

It may be better in https://github.com/JuliaStats/ConjugatePriors.jl though?

**Comment by mschauer** [comment]
Yeah. One could spare a unicode operator for this, in https://github.com/mschauer/GaussianDistributions.jl/blob/master/src/GaussianDistributions.jl#L100 for example we use a unicode operator for the independent sum of gaussian random variables.

**Comment by caldwellshane** [comment]
Ok, thanks for the suggestions. It looks like the function indeed could fit nicely in either of those packages. It seems like `GaussianDistributions.jl` is the better fit, since there are operations already defined there that are very similar. If no one speaks up to the contrary, I'll aim there.

@simonbyrne Yes, that's what I mean.

**Comment by mschauer** [comment]
In any case, it is welcome at GaussianDistributions.jl

**Comment by matbesancon** [comment]
Closing this for now, since seems out of scope for Distributions
