### ISSUE TITLE
Add alias `Gaussian` for `Normal` and `MvGaussian` for `MvNormal`

### ISSUE THREAD

**Issue by juliohm** [JuliaStats/Distributions.jl#828]
Could you please consider adding these type alias in the package?

```julia
const Gaussian = Normal
const MvGaussian = MvNormal
```

In some fields the name `Gaussian` is more widespread than `Normal`. I can submit a PR adding the type alias and exporting the names if it is ok.

**Comment by juliohm** [comment]
I just realized that `const Gaussian = Normal` is already present in the package. I will add a similar line for `MvNormal` and export these names in a PR.

**Comment by mschauer** [comment]
Exporting would make my life more complicated if that counts: https://github.com/mschauer/GaussianDistributions.jl

**Comment by juliohm** [comment]
How would it make your life more complicated @mschauer ? You mean that you would need to qualify the name `Gaussian` in user code that imports both `Distributions.jl` and `GaussianDistributions.jl`?

**Comment by mschauer** [comment]
Yes, or I would have to come up with a new name to avoid that. It might also come in handy to have the name `Gaussian` free to solve the problem `GaussianDistribution` solves for Distributions without breaking code.

**Comment by juliohm** [comment]
It seems that this change is not seen with good eyes by many people according to the thumbs down. Please feel free to close the PR and the issue.

I just feel that `Gaussian` is a quite popular name, and that everyone uses it.
