### ISSUE TITLE
MvNormal with AbstractMatrix and AbstractVector

### ISSUE THREAD

**Issue by aterenin** [JuliaStats/Distributions.jl#831]
It'd be good to implement `MvNormal(mu::AbstractVector{T<:Real}, sig::AbstractMatrix{T<:Real})`.

This would allow Flux.jl and other automatic differentiation packages to differentiate through `MvNormal` without converting a `TrackedArray{Float64}` into `Array{TrackedReal{Float64}}` as an intermediate step.

**Comment by matbesancon** [comment]
Fixed in #837
