### ISSUE TITLE
AliasTable method is not working for unbalanced values

### ISSUE THREAD

**Issue by s271** [JuliaStats/Distributions.jl#832]
Here is comparison of AliasTable and sample. sample working properly, AliasTable produce wrong result for values ~1e5 and more
```julia
using StatsBase
using Distributions
Random.seed!(1)

priorities = collect(1:1000) .* 1.
priorities[1:50] .= 1e8

isample = sample(1:1000, Weights(priorities), 16; replace=false)
_at = Distributions.AliasTable(priorities)
iat = rand(_at, 16)

println("sample ", priorities[isample])
println("AliasTable ", priorities[iat]) 
```
Results:
sample [1.0e8, 1.0e8, 1.0e8, 1.0e8, 1.0e8, 1.0e8, 1.0e8, 1.0e8, 1.0e8, 1.0e8, 1.0e8, 1.0e8, 1.0e8, 1.0e8, 1.0e8, 1.0e8]
AliasTable [94.0, 923.0, 388.0, 529.0, 334.0, 930.0, 630.0, 407.0, 396.0, 959.0, 215.0, 688.0, 704.0, 825.0, 524.0, 565.0]
AliasTable ignoring high-probability samples.

**Comment by simonbyrne** [comment]
The priorities need to be normalised first:
```
_at = Distributions.AliasTable(priorities / sum(priorities))
```
gives the correct result.

We should check this.
