### ISSUE TITLE
Functions for kurtosis excess are backwards

### ISSUE THREAD

**Issue by michaelTucci** [JuliaStats/Distributions.jl#839]
The functions 'isplatykurtic' and 'isplatykurtic' are backwards:

**-**_isleptokurtic(d)_: Return whether d is leptokurtic (i.e kurtosis(d) < 0)  ->  **Should be: kurtosis(d)>0**
**-**_isplatykurtic(d)_:  Return whether d is platykurtic (i.e kurtosis(d) > 0)  ->   **Should be: kurtosis(d)<0**

http://mathworld.wolfram.com/KurtosisExcess.html

**Comment by mschauer** [comment]
Yes, for example, "the most platykurtic distribution of all is the Bernoulli distribution with p = 1/2, for which the excess kurtosis is −2." (https://en.wikipedia.org/wiki/Kurtosis)

Then
```
julia> kurtosis(Bernoulli(0.5))
-2.0
```
but
```
julia> isleptokurtic(Bernoulli(0.5))
true
```


```

**Comment by matbesancon** [comment]
it's very strange that we got this the other way around
