### ISSUE TITLE
Sparse matrix inversion when sampling MvNormalCanon

### ISSUE THREAD

**Issue by ElOceanografo** [JuliaStats/Distributions.jl#841]
After finding a [separate issue](https://github.com/JuliaStats/PDMats.jl/issues/87) in PDMats, I noticed that generating random samples from an `MvNormalCanon` with a `PDSparseMat` precision matrix currently does a dense inversion of the precision matrix, which is potentially very expensive and [shouldn't be necessary](https://math.stackexchange.com/questions/1845132/sample-points-from-a-multivariate-normal-distribution-using-only-the-precision-m/2489142)...it looks like there's no `unwhiten_winv!` method for sparse matrices, so it falls back to the one for `AbstractPDMat`: https://github.com/JuliaStats/Distributions.jl/blob/a6a9ef2799e8772feb0809b4396149d5b6e9a244/src/multivariate/mvnormalcanon.jl#L174

I was wondering if this was a conscious design decision, or an oversight?  Desired working example is  below, though note this doesn't actually work at the moment because of https://github.com/JuliaStats/PDMats.jl/issues/87

```julia
using LinearAlgebra, SparseArrays
using Distributions
using PDMats

J = sprand(10, 10, 0.05)
J = J'J
J[diagind(J)] .= 1
μ = randn(10)
h = J \ μ
d = MvNormalCanon(μ, h, PDSparseMat(J))
rand(d)
```

**Comment by matbesancon** [comment]
Closed by #855

**Comment by matbesancon** [comment]
@JuliaRegistrator register()

**Comment by matbesancon** [comment]
@JuliaRegistrator register()
