### ISSUE TITLE
Test.jl not in dependencies

### ISSUE THREAD

**Issue by JeffFessler** [JuliaStats/Distributions.jl#864]
fyi, precompiling the latest version (v0.19.1) gives this warning:

 Warning: Package Distributions does not have Test in its dependencies:
│ - If you have Distributions checked out for development and have
│   added Test as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with Distributions
└ Loading Test into Distributions from project dependency, future warnings for Distributions are suppressed.

**Comment by simonbyrne** [comment]
Did you try `Pkg.resolve()`? Anyway, we should fix this by adding a Project.toml

**Comment by mschauer** [comment]
See #863

**Comment by JeffFessler** [comment]
oops sorry - i had searched the issues but not the pull requests...  thanks.
