### ISSUE TITLE
Register v0.19.2

### ISSUE THREAD

**Issue by ararslan** [JuliaStats/Distributions.jl#868]
@JuliaRegistrator `register()`

**Comment by ararslan** [comment]
?? Why does it need to be in `[deps]`? It's a test dependency, so it's in `[extras]`. Halp @fredrikekre

**Comment by fredrikekre** [comment]
Registrator bug, it should not error, just filter it out and not propagate it to the registry.

**Comment by ararslan** [comment]
Okay thanks. What should I do in the meantime, just wait for that to be fixed?

**Comment by fredrikekre** [comment]
File an issue, remove the compat entries for test-only deps and try again.

**Comment by ararslan** [comment]
@JuliaRegistrator `register()`
