### ISSUE TITLE
rand(Categorical) is not safe for Float32

### ISSUE THREAD

**Issue by xukai92** [JuliaStats/Distributions.jl#872]
When I do `rand(::Categorical)`, I meet error saying that `cp += p[i +=1]` is visiting an index out of the range of `p` (when `eltype(p)` is `Float32`), in this function https://github.com/JuliaStats/Distributions.jl/blob/master/src/univariate/discrete/discretenonparametric.jl#L79-L89

```julia
function rand(rng::AbstractRNG, d::DiscreteNonParametric{T,P}) where {T,P}
    x = support(d)
    p = probs(d)
    draw = rand(rng, P)
    cp = zero(P)
    i = 0
    while cp < draw
        cp += p[i +=1]
    end
    x[i]
end
```

I'm guessing when `eltype(p)` is `Float32`, `cp < draw` has chance of being never `true` thus give this bound error. I tried to convert `p` to `Vector{Flaot64}` and re-normalise, and I didn't see this error after doing so.

**Comment by matbesancon** [comment]
I tried to think of it in different terms and cannot make sense of this. For lower precisions, we have a reasonable chance of falling on `draw = zero(P)`, in which case we never reach `cp < draw`.

**Comment by mschauer** [comment]
We can just return
```
    x[max(i,1)]
```
Because to cover [0,1] you need e.g. `n-1` half open and `1` closed interval
```
[     ] ( ] (    ] ( ]
```
so special casing the first interval is expected.

**Comment by matbesancon** [comment]
@xukai92 would you have time for a PR on this?

**Comment by xukai92** [comment]
@matbesancon On it.

**Comment by matbesancon** [comment]
awesome thanks
