### ISSUE TITLE
Correct PGeneralizedGaussian sampler

### ISSUE THREAD

**Issue by jsmithnh09** [JuliaStats/Distributions.jl#895]
Within #886 , one of the suggested changes had incorrectly modified the sampler in the source file; on line 127, the sampler ought to be:
```julia
b = (-1) ^ (Float64(rand(Bernoulli())))
```
This would provide the behavior that was originally required, (S ~ 0.5[S=1] + 0.5[S=-1]). For reference, in the appendix of [2]:

[1] https://sccn.ucsd.edu/wiki/Generalized_Gaussian_Probability_Density_Function
[2] Gonzalez-Farias, G., Molina, J. A. D., & Rodríguez-Dagnino, R. M. (2009). Efficiency of the approximated shape parameter estimator in the generalized Gaussian distribution. IEEE Transactions on Vehicular Technology, 58(8), 4214-4223.

I hope opening an issue is the right approach, wasn't sure if opening another branch on my fork and making a pull request would have been the right approach - thanks!

**Comment by matbesancon** [comment]
hi, thanks for pointing it out. Since the PR has been merged, you can make a new one to fix this

**Comment by matbesancon** [comment]
also in the new PR, you can add the reference to the paper in the rand method

**Comment by jsmithnh09** [comment]
Sampler has been fixed! Thanks for the help.
