### ISSUE TITLE
Build docs using a docs/Project.toml

### ISSUE THREAD

**Issue by taqtiqa-mark** [JuliaStats/Distributions.jl#898]
I've hit this because I'm preparing to add to the docs.

Apparently the recommended way to build docs is with a doc/Project.toml:
https://discourse.julialang.org/t/psa-use-a-project-for-building-your-docs/14974

PR to follow once I have it working - unless this issue gets closed.

**Comment by matbesancon** [comment]
I'll do this in the current doc PR thanks

**Comment by taqtiqa-mark** [comment]
No worries.

**Comment by matbesancon** [comment]
Fixed in #893
