### ISSUE TITLE
Inconsistent Behavior of quantile

### ISSUE THREAD

**Issue by lindahua** [JuliaStats/Distributions.jl#90]
`quantile` sometimes generate out-of-support values, and the behavior is inconsistent across distributions:

``` julia
julia> quantile(Bernoulli(), 1)
NaN

julia> quantile(DiscreteUniform(0, 2), 1)
3

julia> quantile(Normal(), 1)
Inf
```

We should agree on a consistent behavior in implementing this ..

**Comment by lindahua** [comment]
Following the convention of Julia Base, we should throw a `DomainError`. Will enforce this next time I go through the distributions.

**Comment by matbesancon** [comment]
Behavior seems fixed, should this one be closed?
