### ISSUE TITLE
DiscreteNonParametric not found

### ISSUE THREAD

**Issue by giadasp** [JuliaStats/Distributions.jl#907]
Dear developers,
I'm trying to use the Distributions.jl features that sample from a DiscreteNonParametric distribution but Julia says that DiscreteNonParametric is not defined. I tried to install the 0.20.0 version but still doesn't work.
How can I do it?
Thanks

**Comment by Peiffap** [comment]
I'm assuming your input types were not correct; I just tried this
```julia
julia> d = DiscreteNonParametric([1, 2, 3, 4], [0.1, 0.2, 0.3, 0.4])
DiscreteNonParametric{Int64,Float64,Array{Int64,1},Array{Float64,1}}(support=[1, 2, 3, 4], p=[0.1, 0.2, 0.3, 0.4])
```
and as you can see it worked just fine.

Which version of Julia are you running?

**Comment by giadasp** [comment]
I'm sorry. I removed, readd the package and now it works!
Thank you for the support.

Giada

Il giorno mar 21 mag 2019, 13:28 Gilles Peiffer <notifications@github.com>
ha scritto:

**Comment by mschauer** [comment]
Great. 

We use GitHub for the development of the Julia package `Distributions` itself. 
For support and questions, please use the [Julia Discourse forum](https://discourse.julialang.org).
Also, for casual conversation and quick questions, there are the channels `#helpdesk` and `#statistics` in the official _Julia Slack_.  To join the _Julia Slack_, please visit [slackinvite.julialang.org](slackinvite.julialang.org).
