### ISSUE TITLE
pdf. for Multivariate distributions

### ISSUE THREAD

**Issue by paschermayr** [JuliaStats/Distributions.jl#923]
Hi guys, 

I am implementing something where I need a pdf evaluation for generic distributions. I can evaluate univariate samples/observations easily via:

```
###########UNIVARIATE  
obs_univ = zeros(10,1)
distr_univ = Normal()
#easily evaluate
pdf.(distr_univ, obs_univ)
```

I would like to do the same for the multivariate case, but this somehow doesnt work as intended:

```
###########MULTIVARIATE
obs_multiv = zeros(10,2)
distr_multiv = MvNormal([0.,0.],[1.,1.])
#NOT being able to evaluate
pdf.(distr_multiv, obs_multiv)
pdf.(distr_multiv, obs_multiv')
```

I can do the same for multivariate distributions via
```
#Somehow works
pdf(distr_multiv, obs_multiv')
```
but then I am wondering why I need to transpose the observations to rows while in the univariate case the pdf happily took the column observations. Moreover, for the univariate case I get a warning that `pdf(distr_multiv, obs_multiv)` is depreciated, but I cannot even use the broadcasted version `pdf.(distr_multiv, obs_multiv)` in the multivariate case. Is this intentional?

Thank you for your time and guidance!

Edit: I could use `pdf(distr_univ, obs_univ')` to mimic the behaviour of the multivariate pdf evaluation,but then I get a depreciation warning and a row- instead of a column vector back.

**Comment by matbesancon** [comment]
thanks @jkbest2 for the explanation, closing here
