### ISSUE TITLE
rand( TDist(Inf) ) gives NaN in v0.20.0

### ISSUE THREAD

**Issue by atteson** [JuliaStats/Distributions.jl#929]
I noticed that `rand( TDist(Inf) )` gives NaN in v0.20.0 but gives a value in v0.16.4 (which I assume corresponds to a standard normal variate).

`pdf( TDist(Inf), 1.0 )` works fine in both versions.

**Comment by matbesancon** [comment]
Several issues here, the distribution parameter should not be taking a real type but an integer value. The type parameter could capture in some sense the infinite / finite thing and dispatch accordingly.

The documentation is also pointing to the "student" wikipedia page, which is not the Student distribution page.
PR welcome

**Comment by atteson** [comment]
Actually, the t distribution is perfectly well defined for integer values of nu and I (and others) use it that way.

**Comment by johnczito** [comment]
What's the preferred behavior, here? Throw an error at construction if you supply `Inf` degrees of freedom? Or effectively have `TDist(Inf)` be a `Normal` constructor?

**Comment by johnczito** [comment]
I think the change happened [here](https://github.com/JuliaStats/Distributions.jl/commit/817bd83326f9d562ec88c0e782e60d25d64862ad), where
```julia
rand(d::TDist) = StatsFuns.RFunctions.tdistrand(d.ν)
```
became
```julia
rand(rng::AbstractRNG, d::TDist) = randn(rng) / sqrt(rand(rng, Chisq(d.ν))/d.ν)
```
The denominator becomes `sqrt(Inf/Inf) = NaN`. So do we want something like this?
```julia
rand(rng::AbstractRNG, d::TDist) = randn(rng) / isinf(d.ν) ? 1 : sqrt(rand(rng, Chisq(d.ν))/d.ν)
```

**Comment by atteson** [comment]
My preference is to allow for the nu=Inf to mean the normal distribution since this is always the limiting behavior.  I like the way the R function works.  However, there are other limiting cases which are not handled in Distributions.  For example, a normal with sigma=0 doesn't become a delta distribution.

**Comment by johnczito** [comment]
Right, so you want `TDist(Inf)` to simply return `Normal(0,1)`. That makes sense, though I'm not sure what the type stability implications of that are.

**Comment by atteson** [comment]
Actually, my intent is that TDist( Inf ) remain that type but act like Normal(0,1) in rand, pdf, cdf, etc.  I think that's probably better because of type stability as you mention.  Someone might assign these to a Vector{TDist} or some such.

The bigger question is "what's the policy of Distributions for edge cases"?  Some approache that I see are:

1.  Make the distribution behave as the limiting distribution in the edge cases (at least when there is a limiting distribution under no other conditions).

2.  Have the distribution fail in the edge cases.

3.  Have the functions of the distribution return NaN.

#1 is what TDist(Inf) used to do.  #2 is what Normal(0,0) does.  #3 is what TDist now does.

My preference is for #1 though this becomes subtle for multivariate distributions.  A multivariate normal with a singular covariance matrix is a normal on a lower dimensional linear subspace.

**Comment by johnczito** [comment]
That all sounds right to me. You said `pdf` is behaving. So for `rand` we could do something like this and it should work again:
```julia
rand(rng::AbstractRNG, d::TDist) = randn(rng) / ( isinf(d.ν) ? 1 : sqrt(rand(rng, Chisq(d.ν))/d.ν) )
```

**Comment by atteson** [comment]
Sounds good.
