### ISSUE TITLE
New patch release?

### ISSUE THREAD

**Issue by glennmoy** [JuliaStats/Distributions.jl#974]
I the most recent release was July 31. If others agree maybe it's time for another patch release? Which PRs would need to be merged for that can happen?

Thanks

**Comment by matbesancon** [comment]
I'll release after #976 which should be today, a new minor will be released after #951

**Comment by matbesancon** [comment]
@JuliaRegistrator register()

**Comment by matbesancon** [comment]
@JuliaRegistrator register()

**Comment by matbesancon** [comment]
@mohamed82008 your PR fix will be released with this version

**Comment by glennmoy** [comment]
closing the issue now that new tag is released, thanks all!

**Comment by matbesancon** [comment]
@JuliaRegistrator register()
