### ISSUE TITLE
Update to SpecialFunctions 0.8.0

### ISSUE THREAD

**Issue by guilhermebodin** [JuliaStats/Distributions.jl#978]
If possible could the new patch release have SpecialFunctions 0.8.0 compatibility, right now I think it is fixed to 0.7. If it is possible I can try a PR by the end of the week

**Comment by matbesancon** [comment]
I was about to, but it still has a blocking issue:
https://github.com/JuliaMath/SpecialFunctions.jl/issues/186
it will have to wait for another patch release :/

**Comment by matbesancon** [comment]
Since the other issues are tracking this (along with PR #891), I'll close this one
