### ISSUE TITLE
Misleading error message when `using` Distributions the first time.

### ISSUE THREAD

**Issue by PGS62** [JuliaStats/Distributions.jl#983]
On both Julia 1.1 and 1.2, after `add`ing Distributions and then `using` for the first time, the following error happens for me:

`Please re-run Pkg.build("fvheQ"), and restart Julia`

That error should have read:

`Please re-run Pkg.build("SpecialFunctions"), and restart Julia`

More details at [this question](https://stackoverflow.com/questions/58169042/julia-distributions-package-installation-woes)  on StackOverflow. It looks like parsing a folder structure has picked out the folder name at the wrong "depth".

**Comment by andreasnoack** [comment]
Please comment if this is still an issue
