### ISSUE TITLE
categorical distributions: support() always returning Base.OneTo(n) range

### ISSUE THREAD

**Issue by mattuntergassmair** [JuliaStats/Distributions.jl#998]
```
d = Categorical(SparseVector(10, [2,3,7], [.3, .4, .3]))
support(d)
>>> Base.OneTo(10)
```
should be `[2,3,7]`

**Comment by mattuntergassmair** [comment]
something like this should do the job and be very efficient
```
function Distributions.support(dist::DiscreteNonParametric{Int, P, Base.OneTo{Int}, Ps}) where {P, Ps<:SparseVector}
    return findnz(dist.p)[1]
end
```

**Comment by mattuntergassmair** [comment]
Actually the problem seems to not just affect sparse vectors:
```
julia> v = SparseVector(100,[22,33,44],[.2,.5,.3]);
julia> d = Categorical(v);
julia> support(d)  # should be [22,33,44]
Base.OneTo(100)

julia> v = [.2, 0, .5, 0, .3];
julia> d = Categorical(v);
julia> support(d)  # should be [1,3,5]
Base.OneTo(5)
```

The real problem seems to lie in `src/distributions/univariate/categorical.jl`, line 27

```
const Categorical{P,Ps} = DiscreteNonParametric{Int,P,Base.OneTo{Int},Ps}
```

**Comment by GordStephen** [comment]
This is the intended behaviour - the support of `Categorical` is defined as being `1:N` (whether or not that makes sense is a valid question though). If you want a sparse support instead, you can use the more general [`DiscreteNonParametric`](https://juliastats.github.io/Distributions.jl/stable/univariate/#Distributions.DiscreteNonParametric) directly (as you note, `Categorical` is just a special case of it): 

```julia
julia> d = DiscreteNonParametric([22,33,44], [.2, .5, .3])
julia> support(d)
3-element Array{Int64,1}:
 22
 33
 44
```

**Comment by mattuntergassmair** [comment]
I agree on the "making sense" part, but `DiscreteNonParametric` will do the job.
Thanks a lot, feel free to close the issue then.
